-- ============================================================================
-- 002_fx_deals_seed.sql — 50 realistic FX deals for testing
-- Generated by: scripts/generate_seed_data.py
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Additional Settlement Instructions for counterparties
-- ---------------------------------------------------------------------------
INSERT INTO settlement_instructions (id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, is_default) VALUES ('20000000-0000-0000-0000-000000000009', 'e0000000-0000-0000-0000-000000000004', 'USD', 'COUNTERPARTY', '2001-USD-TCB', 'Techcombank', 'VTCBVNVX', true);
INSERT INTO settlement_instructions (id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, is_default) VALUES ('20000000-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000005', 'USD', 'COUNTERPARTY', '2001-USD-VPB', 'VPBank', 'VPBKVNVX', true);
INSERT INTO settlement_instructions (id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, is_default) VALUES ('20000000-0000-0000-0000-00000000000b', 'e0000000-0000-0000-0000-000000000006', 'USD', 'COUNTERPARTY', '2001-USD-MBB', 'MB Bank', 'MSCBVNVX', true);
INSERT INTO settlement_instructions (id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, is_default) VALUES ('20000000-0000-0000-0000-00000000000c', 'e0000000-0000-0000-0000-000000000007', 'USD', 'COUNTERPARTY', '2001-USD-BID', 'BIDV', 'BIDVVNVX', true);
INSERT INTO settlement_instructions (id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, is_default) VALUES ('20000000-0000-0000-0000-00000000000d', 'e0000000-0000-0000-0000-000000000008', 'USD', 'COUNTERPARTY', '2001-USD-CTG', 'VietinBank', 'ICBVVNVX', true);
INSERT INTO settlement_instructions (id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, is_default) VALUES ('20000000-0000-0000-0000-00000000000e', 'e0000000-0000-0000-0000-000000000009', 'USD', 'COUNTERPARTY', '2001-USD-STB', 'Sacombank', 'SGTTVNVX', true);
INSERT INTO settlement_instructions (id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, is_default) VALUES ('20000000-0000-0000-0000-00000000000f', 'e0000000-0000-0000-0000-000000000010', 'USD', 'COUNTERPARTY', '2001-USD-SHB', 'SHB', 'SHBAVNVX', true);

-- ---------------------------------------------------------------------------
-- FX Deals (50 total: 25 SPOT, 15 FORWARD, 10 SWAP)
-- Status mix: 10 OPEN, 8 PENDING_L2, 8 PENDING_BOOKING,
--             12 COMPLETED, 6 REJECTED, 6 CANCELLED
-- ---------------------------------------------------------------------------

-- Deal 1: FX-20260401-0001 | FORWARD BUY EUR/USD | PENDING_BOOKING
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('5b068add-9d6b-4ddc-9830-c8179e30b2bb', 'FX-20260401-0001', 'e0000000-0000-0000-0000-000000000002', 'FORWARD', 'BUY', 2830000.00, 'EUR', 'EUR/USD', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'PENDING_BOOKING', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:18:53+07:00', '2026-04-01T09:40:39+07:00');

-- Deal 2: FX-20260401-0002 | SPOT BUY USD/VND | PENDING_BOOKING
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('e5d494f8-f466-4747-a640-e4435ae79c17', 'FX-20260401-0002', 'e0000000-0000-0000-0000-000000000004', 'SPOT', 'BUY', 3960000.00, 'USD', 'USD/VND', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'PENDING_BOOKING', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:18:05+07:00', '2026-04-01T09:54:14+07:00');

-- Deal 3: FX-20260401-0003 | SPOT SELL EUR/USD | PENDING_BOOKING
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('00ef85d6-ef1a-439e-9563-1fd2ed03a9ab', 'FX-20260401-0003', 'e0000000-0000-0000-0000-000000000008', 'SPOT', 'SELL', 3260000.00, 'EUR', 'EUR/USD', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'PENDING_BOOKING', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:53:23+07:00', '2026-04-01T09:10:23+07:00');

-- Deal 4: FX-20260401-0004 | SPOT SELL USD/VND | PENDING_L2_APPROVAL
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('af080575-7b3e-4bf1-a15a-bdabf8fca7e0', 'FX-20260401-0004', 'e0000000-0000-0000-0000-000000000010', 'SPOT', 'SELL', 3260000.00, 'USD', 'USD/VND', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'PENDING_L2_APPROVAL', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:10:34+07:00', '2026-04-01T09:46:15+07:00');

-- Deal 5: FX-20260401-0005 | SPOT SELL EUR/USD | OPEN
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('64b6a2fe-f84c-4bd5-82b9-9485e45d2710', 'FX-20260401-0005', 'e0000000-0000-0000-0000-000000000009', 'SPOT', 'SELL', 1130000.00, 'EUR', 'EUR/USD', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'OPEN', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:43:20+07:00', '2026-04-01T09:53:49+07:00');

-- Deal 6: FX-20260401-0006 | SWAP BUY_SELL USD/VND | CANCELLED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason, cancel_requested_by, cancel_requested_at)
VALUES ('e42300a4-f1aa-474a-9008-b75371e6176a', 'FX-20260401-0006', 'e0000000-0000-0000-0000-000000000006', 'SWAP', 'BUY_SELL', 2060000.00, 'USD', 'USD/VND', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'CANCELLED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:04:13+07:00', '2026-04-01T09:58:36+07:00', 'Thay đổi điều kiện thị trường', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T10:00:00+07:00');

-- Deal 7: FX-20260401-0007 | FORWARD SELL EUR/USD | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('9bb04701-28b8-4e0b-807e-5ece7ae0f2e3', 'FX-20260401-0007', 'e0000000-0000-0000-0000-000000000008', 'FORWARD', 'SELL', 740000.00, 'EUR', 'EUR/USD', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:16:08+07:00', '2026-04-01T09:15:47+07:00');

-- Deal 8: FX-20260401-0008 | SPOT SELL EUR/USD | OPEN
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('9ba988bd-20b3-485a-a666-66c3c8297436', 'FX-20260401-0008', 'e0000000-0000-0000-0000-000000000006', 'SPOT', 'SELL', 1130000.00, 'EUR', 'EUR/USD', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'OPEN', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:08:32+07:00', '2026-04-01T09:31:05+07:00');

-- Deal 9: FX-20260401-0009 | FORWARD BUY USD/VND | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('d73d005c-5c62-4c97-9999-0c1e4cbf1b69', 'FX-20260401-0009', 'e0000000-0000-0000-0000-000000000003', 'FORWARD', 'BUY', 4060000.00, 'USD', 'USD/VND', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:43:27+07:00', '2026-04-01T09:38:04+07:00');

-- Deal 10: FX-20260401-0010 | SPOT SELL EUR/USD | PENDING_L2_APPROVAL
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('c103934f-6ec1-440d-a730-2dbfce900edd', 'FX-20260401-0010', 'e0000000-0000-0000-0000-000000000009', 'SPOT', 'SELL', 4410000.00, 'EUR', 'EUR/USD', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'PENDING_L2_APPROVAL', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:00:43+07:00', '2026-04-01T09:46:07+07:00');

-- Deal 11: FX-20260401-0011 | FORWARD SELL EUR/USD | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('7cadce30-4ed1-4307-aa41-9d9ad91eaa38', 'FX-20260401-0011', 'e0000000-0000-0000-0000-000000000002', 'FORWARD', 'SELL', 1510000.00, 'EUR', 'EUR/USD', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:27:10+07:00', '2026-04-01T09:29:00+07:00');

-- Deal 12: FX-20260401-0012 | SPOT BUY USD/VND | PENDING_BOOKING
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('5da0b5df-3d30-4d86-8765-0d3711b7c6e0', 'FX-20260401-0012', 'e0000000-0000-0000-0000-000000000005', 'SPOT', 'BUY', 4310000.00, 'USD', 'USD/VND', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'PENDING_BOOKING', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:40:32+07:00', '2026-04-01T09:38:12+07:00');

-- Deal 13: FX-20260401-0013 | SPOT BUY USD/VND | PENDING_L2_APPROVAL
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('11e00281-c114-4a72-a046-bf8c37faab74', 'FX-20260401-0013', 'e0000000-0000-0000-0000-000000000010', 'SPOT', 'BUY', 1660000.00, 'USD', 'USD/VND', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'PENDING_L2_APPROVAL', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:31:01+07:00', '2026-04-01T09:07:59+07:00');

-- Deal 14: FX-20260401-0014 | SPOT SELL USD/VND | OPEN
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('33137c9f-bd4f-48e2-9c7b-ef4ded7e9696', 'FX-20260401-0014', 'e0000000-0000-0000-0000-000000000001', 'SPOT', 'SELL', 1240000.00, 'USD', 'USD/VND', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'OPEN', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:56:36+07:00', '2026-04-01T09:05:05+07:00');

-- Deal 15: FX-20260401-0015 | FORWARD BUY USD/VND | REJECTED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason)
VALUES ('33179d6a-0ad4-4b36-8e84-e58313214acc', 'FX-20260401-0015', 'e0000000-0000-0000-0000-000000000003', 'FORWARD', 'BUY', 3380000.00, 'USD', 'USD/VND', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'REJECTED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:35:10+07:00', '2026-04-01T09:16:33+07:00', 'Không đủ điều kiện giao dịch');

-- Deal 16: FX-20260401-0016 | FORWARD BUY EUR/USD | REJECTED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason)
VALUES ('c3c52b9f-c82b-4760-880f-6ac86d229173', 'FX-20260401-0016', 'e0000000-0000-0000-0000-000000000007', 'FORWARD', 'BUY', 3440000.00, 'EUR', 'EUR/USD', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'REJECTED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:28:57+07:00', '2026-04-01T09:33:28+07:00', 'Thiếu hồ sơ đối tác');

-- Deal 17: FX-20260401-0017 | SPOT BUY EUR/USD | PENDING_L2_APPROVAL
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('bc885f19-e010-4974-8048-c433cf9a2513', 'FX-20260401-0017', 'e0000000-0000-0000-0000-000000000001', 'SPOT', 'BUY', 3020000.00, 'EUR', 'EUR/USD', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'PENDING_L2_APPROVAL', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:35:14+07:00', '2026-04-01T09:37:14+07:00');

-- Deal 18: FX-20260401-0018 | SPOT BUY USD/VND | PENDING_BOOKING
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('65705263-9050-463e-924e-f5bc9f3d8723', 'FX-20260401-0018', 'e0000000-0000-0000-0000-000000000002', 'SPOT', 'BUY', 4640000.00, 'USD', 'USD/VND', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'PENDING_BOOKING', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:02:55+07:00', '2026-04-01T09:21:04+07:00');

-- Deal 19: FX-20260401-0019 | FORWARD SELL EUR/USD | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('002ab914-153f-4296-ac63-17c104875902', 'FX-20260401-0019', 'e0000000-0000-0000-0000-000000000004', 'FORWARD', 'SELL', 2770000.00, 'EUR', 'EUR/USD', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:08:46+07:00', '2026-04-01T09:59:56+07:00');

-- Deal 20: FX-20260401-0020 | SPOT SELL EUR/USD | OPEN
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('1f7c5c59-1fbd-43ee-a42b-6ca2f89b2140', 'FX-20260401-0020', 'e0000000-0000-0000-0000-000000000004', 'SPOT', 'SELL', 490000.00, 'EUR', 'EUR/USD', '2026-04-01', 'a0000000-0000-0000-0000-000000000001', 'OPEN', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-01T09:06:42+07:00', '2026-04-01T09:27:22+07:00');

-- Deal 21: FX-20260402-0021 | SWAP SELL_BUY USD/VND | REJECTED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason)
VALUES ('a16fe3db-3708-4c36-ac88-4fd1d451c9c1', 'FX-20260402-0021', 'e0000000-0000-0000-0000-000000000002', 'SWAP', 'SELL_BUY', 320000.00, 'USD', 'USD/VND', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'REJECTED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:46:21+07:00', '2026-04-02T09:51:55+07:00', 'Không đủ điều kiện giao dịch');

-- Deal 22: FX-20260402-0022 | SPOT SELL USD/VND | PENDING_BOOKING
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('88069138-edaa-476f-b445-8a168fcbddcf', 'FX-20260402-0022', 'e0000000-0000-0000-0000-000000000007', 'SPOT', 'SELL', 940000.00, 'USD', 'USD/VND', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'PENDING_BOOKING', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:17:29+07:00', '2026-04-02T09:15:55+07:00');

-- Deal 23: FX-20260402-0023 | FORWARD SELL USD/VND | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('e2567841-247c-4b8c-a29b-483002afc13d', 'FX-20260402-0023', 'e0000000-0000-0000-0000-000000000001', 'FORWARD', 'SELL', 3340000.00, 'USD', 'USD/VND', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:34:53+07:00', '2026-04-02T09:00:05+07:00');

-- Deal 24: FX-20260402-0024 | SWAP SELL_BUY EUR/USD | CANCELLED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason, cancel_requested_by, cancel_requested_at)
VALUES ('fef07688-c74f-4ce4-badc-94c11427cc35', 'FX-20260402-0024', 'e0000000-0000-0000-0000-000000000004', 'SWAP', 'SELL_BUY', 4430000.00, 'EUR', 'EUR/USD', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'CANCELLED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:57:03+07:00', '2026-04-02T09:10:24+07:00', 'Thay đổi điều kiện thị trường', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T10:00:00+07:00');

-- Deal 25: FX-20260402-0025 | SWAP SELL_BUY EUR/USD | REJECTED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason)
VALUES ('6f19e726-932f-43a8-8b0a-88b89a17034f', 'FX-20260402-0025', 'e0000000-0000-0000-0000-000000000007', 'SWAP', 'SELL_BUY', 3570000.00, 'EUR', 'EUR/USD', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'REJECTED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:09:12+07:00', '2026-04-02T09:18:13+07:00', 'Không đủ điều kiện giao dịch');

-- Deal 26: FX-20260402-0026 | FORWARD BUY EUR/USD | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('2c06d7a9-b9d0-4bbd-a00f-3795a95b4edb', 'FX-20260402-0026', 'e0000000-0000-0000-0000-000000000001', 'FORWARD', 'BUY', 260000.00, 'EUR', 'EUR/USD', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:37:30+07:00', '2026-04-02T09:32:58+07:00');

-- Deal 27: FX-20260402-0027 | FORWARD BUY USD/VND | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('e64eb259-c3c6-4e1a-875e-d6f52b94e623', 'FX-20260402-0027', 'e0000000-0000-0000-0000-000000000002', 'FORWARD', 'BUY', 3050000.00, 'USD', 'USD/VND', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:04:43+07:00', '2026-04-02T09:55:15+07:00');

-- Deal 28: FX-20260402-0028 | SPOT BUY USD/VND | PENDING_BOOKING
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('797ff607-69dd-493c-812f-2ee0985bf972', 'FX-20260402-0028', 'e0000000-0000-0000-0000-000000000010', 'SPOT', 'BUY', 420000.00, 'USD', 'USD/VND', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'PENDING_BOOKING', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:26:42+07:00', '2026-04-02T09:37:36+07:00');

-- Deal 29: FX-20260402-0029 | SPOT SELL USD/VND | PENDING_BOOKING
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('0ec9e48d-fb04-4093-b845-dee3293675e1', 'FX-20260402-0029', 'e0000000-0000-0000-0000-000000000006', 'SPOT', 'SELL', 1230000.00, 'USD', 'USD/VND', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'PENDING_BOOKING', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:16:25+07:00', '2026-04-02T09:08:42+07:00');

-- Deal 30: FX-20260402-0030 | SWAP SELL_BUY EUR/USD | REJECTED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason)
VALUES ('a3f29731-5c40-49dd-a197-f3207e0a822d', 'FX-20260402-0030', 'e0000000-0000-0000-0000-000000000002', 'SWAP', 'SELL_BUY', 50000.00, 'EUR', 'EUR/USD', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'REJECTED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:39:36+07:00', '2026-04-02T09:06:04+07:00', 'Không đủ điều kiện giao dịch');

-- Deal 31: FX-20260402-0031 | SWAP SELL_BUY USD/VND | CANCELLED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason, cancel_requested_by, cancel_requested_at)
VALUES ('26049f99-0c89-4e76-8bdd-0c422029c477', 'FX-20260402-0031', 'e0000000-0000-0000-0000-000000000004', 'SWAP', 'SELL_BUY', 1900000.00, 'USD', 'USD/VND', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'CANCELLED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:10:28+07:00', '2026-04-02T09:53:34+07:00', 'Thay đổi điều kiện thị trường', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T10:00:00+07:00');

-- Deal 32: FX-20260402-0032 | FORWARD BUY EUR/USD | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('9c0ddd8a-955c-4f67-baa5-f078f3f637cb', 'FX-20260402-0032', 'e0000000-0000-0000-0000-000000000002', 'FORWARD', 'BUY', 4810000.00, 'EUR', 'EUR/USD', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:56:08+07:00', '2026-04-02T09:16:07+07:00');

-- Deal 33: FX-20260402-0033 | FORWARD BUY EUR/USD | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('7b3ced66-9d2e-44d6-a0aa-21de07b354b3', 'FX-20260402-0033', 'e0000000-0000-0000-0000-000000000005', 'FORWARD', 'BUY', 3100000.00, 'EUR', 'EUR/USD', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:13:45+07:00', '2026-04-02T09:21:13+07:00');

-- Deal 34: FX-20260402-0034 | SWAP SELL_BUY USD/VND | CANCELLED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason, cancel_requested_by, cancel_requested_at)
VALUES ('1d7dc31a-048f-425d-802a-3a1615223c4b', 'FX-20260402-0034', 'e0000000-0000-0000-0000-000000000002', 'SWAP', 'SELL_BUY', 3250000.00, 'USD', 'USD/VND', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'CANCELLED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:53:17+07:00', '2026-04-02T09:02:00+07:00', 'Thay đổi điều kiện thị trường', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T10:00:00+07:00');

-- Deal 35: FX-20260402-0035 | SPOT SELL USD/VND | PENDING_L2_APPROVAL
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('89f93405-266b-4281-a75d-3186a6dbe722', 'FX-20260402-0035', 'e0000000-0000-0000-0000-000000000008', 'SPOT', 'SELL', 2830000.00, 'USD', 'USD/VND', '2026-04-02', 'a0000000-0000-0000-0000-000000000001', 'PENDING_L2_APPROVAL', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-02T09:45:27+07:00', '2026-04-02T09:35:00+07:00');

-- Deal 36: FX-20260403-0036 | SWAP BUY_SELL USD/VND | CANCELLED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason, cancel_requested_by, cancel_requested_at)
VALUES ('e8e9ab96-c2b5-4580-9dc6-97ad201f16b6', 'FX-20260403-0036', 'e0000000-0000-0000-0000-000000000006', 'SWAP', 'BUY_SELL', 2990000.00, 'USD', 'USD/VND', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'CANCELLED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:09:27+07:00', '2026-04-03T09:08:02+07:00', 'Deal trùng lặp', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T10:00:00+07:00');

-- Deal 37: FX-20260403-0037 | SWAP BUY_SELL USD/VND | CANCELLED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason, cancel_requested_by, cancel_requested_at)
VALUES ('03f44628-9ab7-4a9f-8654-926a95e7ef41', 'FX-20260403-0037', 'e0000000-0000-0000-0000-000000000002', 'SWAP', 'BUY_SELL', 1820000.00, 'USD', 'USD/VND', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'CANCELLED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:56:55+07:00', '2026-04-03T09:26:39+07:00', 'Deal trùng lặp', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T10:00:00+07:00');

-- Deal 38: FX-20260403-0038 | SPOT BUY EUR/USD | OPEN
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('ec58d7c4-72fa-4a31-b75b-25660a8e324e', 'FX-20260403-0038', 'e0000000-0000-0000-0000-000000000001', 'SPOT', 'BUY', 920000.00, 'EUR', 'EUR/USD', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'OPEN', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:47:59+07:00', '2026-04-03T09:21:50+07:00');

-- Deal 39: FX-20260403-0039 | FORWARD BUY EUR/USD | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('1fc27410-6f54-4d8f-8899-75c2cdf6604c', 'FX-20260403-0039', 'e0000000-0000-0000-0000-000000000003', 'FORWARD', 'BUY', 4040000.00, 'EUR', 'EUR/USD', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:44:06+07:00', '2026-04-03T09:24:55+07:00');

-- Deal 40: FX-20260403-0040 | FORWARD BUY USD/VND | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('0a9e1538-cc0a-4580-8194-27a33549904f', 'FX-20260403-0040', 'e0000000-0000-0000-0000-000000000008', 'FORWARD', 'BUY', 1800000.00, 'USD', 'USD/VND', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:19:52+07:00', '2026-04-03T09:50:55+07:00');

-- Deal 41: FX-20260403-0041 | SPOT BUY EUR/USD | OPEN
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('20ab4065-7c41-48d4-9d40-c131c7796092', 'FX-20260403-0041', 'e0000000-0000-0000-0000-000000000006', 'SPOT', 'BUY', 1430000.00, 'EUR', 'EUR/USD', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'OPEN', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:55:04+07:00', '2026-04-03T09:49:17+07:00');

-- Deal 42: FX-20260403-0042 | FORWARD SELL EUR/USD | COMPLETED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('43455f39-037d-4230-83f9-71e9045948e2', 'FX-20260403-0042', 'e0000000-0000-0000-0000-000000000001', 'FORWARD', 'SELL', 600000.00, 'EUR', 'EUR/USD', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'COMPLETED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:56:16+07:00', '2026-04-03T09:11:37+07:00');

-- Deal 43: FX-20260403-0043 | SPOT SELL EUR/USD | OPEN
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('836856ba-035f-4cb9-9666-f2af3787bffa', 'FX-20260403-0043', 'e0000000-0000-0000-0000-000000000006', 'SPOT', 'SELL', 2240000.00, 'EUR', 'EUR/USD', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'OPEN', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:38:32+07:00', '2026-04-03T09:07:24+07:00');

-- Deal 44: FX-20260403-0044 | SPOT BUY EUR/USD | OPEN
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('ee723e13-1adc-44d3-94c3-0a30f63150a9', 'FX-20260403-0044', 'e0000000-0000-0000-0000-000000000001', 'SPOT', 'BUY', 3630000.00, 'EUR', 'EUR/USD', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'OPEN', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:27:00+07:00', '2026-04-03T09:33:59+07:00');

-- Deal 45: FX-20260403-0045 | SPOT BUY EUR/USD | PENDING_L2_APPROVAL
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('df4ad20e-72f9-4253-bdcd-e8dfef38e7ea', 'FX-20260403-0045', 'e0000000-0000-0000-0000-000000000007', 'SPOT', 'BUY', 360000.00, 'EUR', 'EUR/USD', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'PENDING_L2_APPROVAL', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:42:58+07:00', '2026-04-03T09:21:39+07:00');

-- Deal 46: FX-20260403-0046 | SPOT BUY EUR/USD | PENDING_L2_APPROVAL
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('55bb5538-e2d4-4a1c-8a86-599ad6535607', 'FX-20260403-0046', 'e0000000-0000-0000-0000-000000000009', 'SPOT', 'BUY', 1590000.00, 'EUR', 'EUR/USD', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'PENDING_L2_APPROVAL', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:42:26+07:00', '2026-04-03T09:20:25+07:00');

-- Deal 47: FX-20260403-0047 | SPOT BUY USD/VND | PENDING_L2_APPROVAL
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('7344bdef-0daa-4116-a513-7dbb57c400f6', 'FX-20260403-0047', 'e0000000-0000-0000-0000-000000000007', 'SPOT', 'BUY', 3410000.00, 'USD', 'USD/VND', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'PENDING_L2_APPROVAL', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:24:43+07:00', '2026-04-03T09:47:57+07:00');

-- Deal 48: FX-20260403-0048 | SPOT SELL EUR/USD | OPEN
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('47fdac9f-712e-4ba2-a2af-b40227fc243c', 'FX-20260403-0048', 'e0000000-0000-0000-0000-000000000009', 'SPOT', 'SELL', 4270000.00, 'EUR', 'EUR/USD', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'OPEN', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:00:19+07:00', '2026-04-03T09:18:13+07:00');

-- Deal 49: FX-20260403-0049 | SPOT SELL EUR/USD | OPEN
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at)
VALUES ('3f67e22c-b172-49d7-a19b-77dd8e284185', 'FX-20260403-0049', 'e0000000-0000-0000-0000-000000000008', 'SPOT', 'SELL', 2270000.00, 'EUR', 'EUR/USD', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'OPEN', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:43:13+07:00', '2026-04-03T09:32:30+07:00');

-- Deal 50: FX-20260403-0050 | SWAP BUY_SELL USD/VND | REJECTED
INSERT INTO fx_deals (id, deal_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, status, created_by, updated_by, created_at, updated_at, cancel_reason)
VALUES ('5f8597e0-8c60-4908-90c8-4b896ba4622e', 'FX-20260403-0050', 'e0000000-0000-0000-0000-000000000005', 'SWAP', 'BUY_SELL', 2640000.00, 'USD', 'USD/VND', '2026-04-03', 'a0000000-0000-0000-0000-000000000001', 'REJECTED', 'd0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000001', '2026-04-03T09:05:52+07:00', '2026-04-03T09:48:15+07:00', 'Thiếu hồ sơ đối tác');

-- ---------------------------------------------------------------------------
-- FX Deal Legs (1 per SPOT/FORWARD, 2 per SWAP)
-- ---------------------------------------------------------------------------

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('981e07fe-fd9e-4fd2-b97a-e60f43be02f1', '5b068add-9d6b-4ddc-9830-c8179e30b2bb', 1, '2026-06-30', '2026-06-30', 1.103094, 3121756.02, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('ca332eb0-98a7-438e-bdeb-96cbc27f2c1e', 'e5d494f8-f466-4747-a640-e4435ae79c17', 1, '2026-04-03', '2026-04-03', 26146.59, 103540496400.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000009');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('e9eb7b91-c738-426e-bc82-2b5d352501ab', '00ef85d6-ef1a-439e-9563-1fd2ed03a9ab', 1, '2026-04-03', '2026-04-03', 1.094211, 3567127.86, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000d');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('9ebdeead-7f6a-424e-8355-8968e3fec2db', 'af080575-7b3e-4bf1-a15a-bdabf8fca7e0', 1, '2026-04-03', '2026-04-03', 25865.36, 84321073600.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000f');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('1895e8af-7d69-488a-b488-e8960bf414d3', '64b6a2fe-f84c-4bd5-82b9-9485e45d2710', 1, '2026-04-03', '2026-04-03', 1.111040, 1255475.20, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000e');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('48a23646-a4cb-4817-aa56-48275e1df673', 'e42300a4-f1aa-474a-9008-b75371e6176a', 1, '2026-04-03', '2026-04-03', 26150.55, 53870133000.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000b');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('5ddeecb3-e040-401e-a0fb-6b23c32e684d', 'e42300a4-f1aa-474a-9008-b75371e6176a', 2, '2026-06-30', '2026-06-30', 26143.08, 53854744800.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000b');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('ab877996-3796-4a3b-858f-84fd2655f51c', '9bb04701-28b8-4e0b-807e-5ece7ae0f2e3', 1, '2026-06-30', '2026-06-30', 1.109881, 821311.94, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000d');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('4ffbced6-ff74-4c1f-83e8-733161dc47cf', '9ba988bd-20b3-485a-a666-66c3c8297436', 1, '2026-04-03', '2026-04-03', 1.110231, 1254561.03, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000b');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('90f2fd99-dc29-4dd8-9c2d-f198edfeadf8', 'd73d005c-5c62-4c97-9999-0c1e4cbf1b69', 1, '2026-09-28', '2026-09-28', 25952.65, 105367759000.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000005');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('742348bf-f4d9-4ec8-8a08-d2a82a270c28', 'c103934f-6ec1-440d-a730-2dbfce900edd', 1, '2026-04-03', '2026-04-03', 1.107268, 4883051.88, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000e');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('bb93e84e-1e6d-43ec-8203-8f4e681c7710', '7cadce30-4ed1-4307-aa41-9d9ad91eaa38', 1, '2026-06-30', '2026-06-30', 1.118876, 1689502.76, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('27e347ca-0712-43c8-8c2a-865b58913048', '5da0b5df-3d30-4d86-8765-0d3711b7c6e0', 1, '2026-04-03', '2026-04-03', 25861.14, 111461513400.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000a');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('3dc8ba31-99bd-4f8f-abba-ba5cb7a2dc07', '11e00281-c114-4a72-a046-bf8c37faab74', 1, '2026-04-03', '2026-04-03', 25945.19, 43069015400.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000f');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('f11d7a64-d5eb-4598-8834-e18cbd02fc74', '33137c9f-bd4f-48e2-9c7b-ef4ded7e9696', 1, '2026-04-03', '2026-04-03', 26092.76, 32355022400.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000003');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('630b4ed6-916a-49af-be48-730473b7ba40', '33179d6a-0ad4-4b36-8e84-e58313214acc', 1, '2026-09-28', '2026-09-28', 26185.75, 88507835000.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000005');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('6729b194-0a78-4c66-ad1d-21820b0856c2', 'c3c52b9f-c82b-4760-880f-6ac86d229173', 1, '2026-05-01', '2026-05-01', 1.089916, 3749311.04, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000c');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('7142bb7a-6f99-49d1-9316-e1b64248242d', 'bc885f19-e010-4974-8048-c433cf9a2513', 1, '2026-04-03', '2026-04-03', 1.080288, 3262469.76, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000003');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('bb77902c-b23e-42c4-a26f-8b35a61d96ae', '65705263-9050-463e-924e-f5bc9f3d8723', 1, '2026-04-03', '2026-04-03', 26005.66, 120666262400.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('7e7f502b-5754-42d5-ad7b-1af890d1c3e8', '002ab914-153f-4296-ac63-17c104875902', 1, '2026-09-28', '2026-09-28', 1.089720, 3018524.40, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000009');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('87d19f8e-7b85-4ad5-a915-502163440856', '1f7c5c59-1fbd-43ee-a42b-6ca2f89b2140', 1, '2026-04-03', '2026-04-03', 1.096943, 537502.07, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000009');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('2d3408c8-553c-48a4-8f15-97df7b6dc275', 'a16fe3db-3708-4c36-ac88-4fd1d451c9c1', 1, '2026-04-04', '2026-04-04', 25843.71, 8269987200.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('0b90b815-6e8f-4267-98de-5b697ee045ec', 'a16fe3db-3708-4c36-ac88-4fd1d451c9c1', 2, '2026-06-01', '2026-06-01', 25831.75, 8266160000.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('a1168a7c-db18-41e9-828e-e1c942b06e96', '88069138-edaa-476f-b445-8a168fcbddcf', 1, '2026-04-04', '2026-04-04', 26169.31, 24599151400.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000c');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('72218411-48d2-4f00-a12c-8ea1ec31e217', 'e2567841-247c-4b8c-a29b-483002afc13d', 1, '2026-06-01', '2026-06-01', 25866.52, 86394176800.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000003');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('9769c7b3-027b-4cb7-abbd-92052032f3bc', 'fef07688-c74f-4ce4-badc-94c11427cc35', 1, '2026-04-04', '2026-04-04', 1.080086, 4784780.98, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000009');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('5ca1ae07-02c3-4ba3-9e27-29e805463eed', 'fef07688-c74f-4ce4-badc-94c11427cc35', 2, '2026-09-29', '2026-09-29', 1.080390, 4786127.70, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000009');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('8dafd4ba-3a0d-4b04-b095-07b18b338897', '6f19e726-932f-43a8-8b0a-88b89a17034f', 1, '2026-04-04', '2026-04-04', 1.118748, 3993930.36, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000c');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('e401c31a-b175-426b-bd49-6831ddb8d5a1', '6f19e726-932f-43a8-8b0a-88b89a17034f', 2, '2026-12-28', '2026-12-28', 1.128463, 4028612.91, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000c');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('5fa0838e-5696-4bbb-aed5-3444d200db7c', '2c06d7a9-b9d0-4bbd-a00f-3795a95b4edb', 1, '2026-06-01', '2026-06-01', 1.082275, 281391.50, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000003');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('ad4a5991-d12f-46db-9a00-3e19a2b9ec60', 'e64eb259-c3c6-4e1a-875e-d6f52b94e623', 1, '2026-09-29', '2026-09-29', 25847.95, 78836247500.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('ee255f62-8b27-4d69-b4a8-7934fa13a3b0', '797ff607-69dd-493c-812f-2ee0985bf972', 1, '2026-04-04', '2026-04-04', 26009.11, 10923826200.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000f');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('e7effe2e-df44-491e-811b-22c505388c1c', '0ec9e48d-fb04-4093-b845-dee3293675e1', 1, '2026-04-04', '2026-04-04', 26058.20, 32051586000.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000b');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('b8282edd-520f-4d90-9eed-c4d2480820cd', 'a3f29731-5c40-49dd-a197-f3207e0a822d', 1, '2026-04-04', '2026-04-04', 1.101505, 55075.25, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('755a3f90-606b-4f05-8590-760a9846de5f', 'a3f29731-5c40-49dd-a197-f3207e0a822d', 2, '2026-12-28', '2026-12-28', 1.101809, 55090.45, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('2168de79-cc36-424b-8e53-fd444775f360', '26049f99-0c89-4e76-8bdd-0c422029c477', 1, '2026-04-04', '2026-04-04', 26081.42, 49554698000.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000009');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('37c59bb0-d459-4a6b-b896-66027e3e2643', '26049f99-0c89-4e76-8bdd-0c422029c477', 2, '2026-12-28', '2026-12-28', 26228.19, 49833561000.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000009');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('313cff4f-5b14-4291-8dac-c66dbbf37818', '9c0ddd8a-955c-4f67-baa5-f078f3f637cb', 1, '2026-05-02', '2026-05-02', 1.109697, 5337642.57, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('89337d09-340d-409d-9d0c-e755782c2d43', '7b3ced66-9d2e-44d6-a0aa-21de07b354b3', 1, '2026-07-01', '2026-07-01', 1.100216, 3410669.60, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000a');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('868d033d-6bc9-449e-b70f-f56d3ec820bd', '1d7dc31a-048f-425d-802a-3a1615223c4b', 1, '2026-04-04', '2026-04-04', 25933.42, 84283615000.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('739198fd-7702-4b4d-bb32-8aa08d169369', '1d7dc31a-048f-425d-802a-3a1615223c4b', 2, '2026-06-01', '2026-06-01', 26010.84, 84535230000.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('92ef31e4-fb18-47fa-90a3-5535d2007668', '89f93405-266b-4281-a75d-3186a6dbe722', 1, '2026-04-04', '2026-04-04', 25844.75, 73140642500.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000d');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('2287ecb0-a523-42d9-8aea-c09c25bd11c4', 'e8e9ab96-c2b5-4580-9dc6-97ad201f16b6', 1, '2026-04-05', '2026-04-05', 25923.30, 77510667000.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000b');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('ad92ad43-8f14-4063-be3a-8ad48135bf28', 'e8e9ab96-c2b5-4580-9dc6-97ad201f16b6', 2, '2026-05-03', '2026-05-03', 26053.08, 77898709200.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000b');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('fd184ed3-a295-409a-be20-95e4c509c27e', '03f44628-9ab7-4a9f-8654-926a95e7ef41', 1, '2026-04-05', '2026-04-05', 26099.79, 47501617800.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('10a0ce95-3787-4d02-911c-42802c49db52', '03f44628-9ab7-4a9f-8654-926a95e7ef41', 2, '2026-06-02', '2026-06-02', 26222.71, 47725332200.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000004');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('9a8a7873-4805-4f3f-acc9-fcad8a68bd0c', 'ec58d7c4-72fa-4a31-b75b-25660a8e324e', 1, '2026-04-05', '2026-04-05', 1.117233, 1027854.36, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000003');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('20a4ffdb-0669-4566-8519-33e240ec0b14', '1fc27410-6f54-4d8f-8899-75c2cdf6604c', 1, '2026-05-03', '2026-05-03', 1.114344, 4501949.76, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000005');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('1a739645-aece-46a8-90cf-508c25e29b44', '0a9e1538-cc0a-4580-8194-27a33549904f', 1, '2026-06-02', '2026-06-02', 25889.17, 46600506000.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000d');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('b397354e-60ed-4614-9810-acdaae4f9a75', '20ab4065-7c41-48d4-9d40-c131c7796092', 1, '2026-04-05', '2026-04-05', 1.094046, 1564485.78, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000b');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('1370c690-4bc5-413c-97e8-2ea3ea84fbd2', '43455f39-037d-4230-83f9-71e9045948e2', 1, '2026-07-02', '2026-07-02', 1.081530, 648918.00, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000003');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('635f1eb0-5de4-47bc-ae5b-7a69e8796d2f', '836856ba-035f-4cb9-9666-f2af3787bffa', 1, '2026-04-05', '2026-04-05', 1.115980, 2499795.20, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000b');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('9f41d594-8dd2-4d1f-981f-de102d83f347', 'ee723e13-1adc-44d3-94c3-0a30f63150a9', 1, '2026-04-05', '2026-04-05', 1.112260, 4037503.80, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000003');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('94c7f8ca-3ebd-4d79-b637-55d91b85d349', 'df4ad20e-72f9-4253-bdcd-e8dfef38e7ea', 1, '2026-04-05', '2026-04-05', 1.092557, 393320.52, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000c');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('1f0d71ec-98c0-49aa-99b1-05216fd22109', '55bb5538-e2d4-4a1c-8a86-599ad6535607', 1, '2026-04-05', '2026-04-05', 1.107888, 1761541.92, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000e');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('a88a7110-3578-44cc-a02d-628f016208c5', '7344bdef-0daa-4116-a513-7dbb57c400f6', 1, '2026-04-05', '2026-04-05', 25869.61, 88215370100.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000c');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('8eeb817c-0ac6-4c4f-bcb0-0da99716db42', '47fdac9f-712e-4ba2-a2af-b40227fc243c', 1, '2026-04-05', '2026-04-05', 1.097196, 4685026.92, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000e');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('3bc28481-e45a-460d-8d86-ad48aac13b6d', '3f67e22c-b172-49d7-a19b-77dd8e284185', 1, '2026-04-05', '2026-04-05', 1.111749, 2523670.23, 'USD', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000d');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('4c026db2-de43-4e36-8c95-efa6117356e0', '5f8597e0-8c60-4908-90c8-4b896ba4622e', 1, '2026-04-05', '2026-04-05', 26069.12, 68822476800.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000a');

INSERT INTO fx_deal_legs (id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id)
VALUES ('04f82767-1fdd-48c8-a6ad-4d20e180db43', '5f8597e0-8c60-4908-90c8-4b896ba4622e', 2, '2026-06-02', '2026-06-02', 26180.43, 69116335200.00, 'VND', '20000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-00000000000a');

COMMIT;
