DROP TABLE IF EXISTS cancel_metadata;

DELETE FROM status_transition_rules
WHERE deal_module = 'FX'
  AND from_status IN ('COMPLETED', 'PENDING_SETTLEMENT', 'PENDING_CANCEL_L1', 'PENDING_CANCEL_L2')
  AND to_status IN ('PENDING_CANCEL_L1', 'PENDING_CANCEL_L2', 'CANCELLED', 'COMPLETED', 'PENDING_SETTLEMENT');
