// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approval_actions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countApprovalActionsByDeal = `-- name: CountApprovalActionsByDeal :one
SELECT COUNT(*) FROM approval_actions
WHERE deal_module = $1 AND deal_id = $2
`

type CountApprovalActionsByDealParams struct {
	DealModule string    `json:"deal_module"`
	DealID     uuid.UUID `json:"deal_id"`
}

// Đếm số hành động phê duyệt theo deal
func (q *Queries) CountApprovalActionsByDeal(ctx context.Context, arg CountApprovalActionsByDealParams) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovalActionsByDeal, arg.DealModule, arg.DealID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovalAction = `-- name: CreateApprovalAction :one

INSERT INTO approval_actions (
    id, deal_module, deal_id, action_type,
    status_before, status_after, performed_by,
    performed_at, reason, metadata
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, NOW(), $7, $8
)
RETURNING id, deal_module, deal_id, action_type, status_before, status_after, performed_by, performed_at, reason, metadata
`

type CreateApprovalActionParams struct {
	DealModule   string    `json:"deal_module"`
	DealID       uuid.UUID `json:"deal_id"`
	ActionType   string    `json:"action_type"`
	StatusBefore string    `json:"status_before"`
	StatusAfter  string    `json:"status_after"`
	PerformedBy  uuid.UUID `json:"performed_by"`
	Reason       *string   `json:"reason"`
	Metadata     []byte    `json:"metadata"`
}

// ============================================================================
// approval_actions.sql — Queries for approval_actions table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateApprovalAction(ctx context.Context, arg CreateApprovalActionParams) (ApprovalAction, error) {
	row := q.db.QueryRow(ctx, createApprovalAction,
		arg.DealModule,
		arg.DealID,
		arg.ActionType,
		arg.StatusBefore,
		arg.StatusAfter,
		arg.PerformedBy,
		arg.Reason,
		arg.Metadata,
	)
	var i ApprovalAction
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.DealID,
		&i.ActionType,
		&i.StatusBefore,
		&i.StatusAfter,
		&i.PerformedBy,
		&i.PerformedAt,
		&i.Reason,
		&i.Metadata,
	)
	return i, err
}

const getLatestApprovalActionByDeal = `-- name: GetLatestApprovalActionByDeal :one
SELECT
    aa.id, aa.deal_module, aa.deal_id, aa.action_type, aa.status_before, aa.status_after, aa.performed_by, aa.performed_at, aa.reason, aa.metadata,
    u.full_name AS performer_name
FROM approval_actions aa
JOIN users u ON u.id = aa.performed_by
WHERE aa.deal_module = $1 AND aa.deal_id = $2
ORDER BY aa.performed_at DESC
LIMIT 1
`

type GetLatestApprovalActionByDealParams struct {
	DealModule string    `json:"deal_module"`
	DealID     uuid.UUID `json:"deal_id"`
}

type GetLatestApprovalActionByDealRow struct {
	ID            uuid.UUID `json:"id"`
	DealModule    string    `json:"deal_module"`
	DealID        uuid.UUID `json:"deal_id"`
	ActionType    string    `json:"action_type"`
	StatusBefore  string    `json:"status_before"`
	StatusAfter   string    `json:"status_after"`
	PerformedBy   uuid.UUID `json:"performed_by"`
	PerformedAt   time.Time `json:"performed_at"`
	Reason        *string   `json:"reason"`
	Metadata      []byte    `json:"metadata"`
	PerformerName string    `json:"performer_name"`
}

// Hành động phê duyệt gần nhất — xác định trạng thái hiện tại
func (q *Queries) GetLatestApprovalActionByDeal(ctx context.Context, arg GetLatestApprovalActionByDealParams) (GetLatestApprovalActionByDealRow, error) {
	row := q.db.QueryRow(ctx, getLatestApprovalActionByDeal, arg.DealModule, arg.DealID)
	var i GetLatestApprovalActionByDealRow
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.DealID,
		&i.ActionType,
		&i.StatusBefore,
		&i.StatusAfter,
		&i.PerformedBy,
		&i.PerformedAt,
		&i.Reason,
		&i.Metadata,
		&i.PerformerName,
	)
	return i, err
}

const listApprovalActionsByDateRange = `-- name: ListApprovalActionsByDateRange :many
SELECT
    aa.id, aa.deal_module, aa.deal_id, aa.action_type, aa.status_before, aa.status_after, aa.performed_by, aa.performed_at, aa.reason, aa.metadata,
    u.full_name AS performer_name
FROM approval_actions aa
JOIN users u ON u.id = aa.performed_by
WHERE aa.performed_at BETWEEN $1 AND $2
ORDER BY aa.performed_at DESC
LIMIT $3 OFFSET $4
`

type ListApprovalActionsByDateRangeParams struct {
	PerformedAt   time.Time `json:"performed_at"`
	PerformedAt_2 time.Time `json:"performed_at_2"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

type ListApprovalActionsByDateRangeRow struct {
	ID            uuid.UUID `json:"id"`
	DealModule    string    `json:"deal_module"`
	DealID        uuid.UUID `json:"deal_id"`
	ActionType    string    `json:"action_type"`
	StatusBefore  string    `json:"status_before"`
	StatusAfter   string    `json:"status_after"`
	PerformedBy   uuid.UUID `json:"performed_by"`
	PerformedAt   time.Time `json:"performed_at"`
	Reason        *string   `json:"reason"`
	Metadata      []byte    `json:"metadata"`
	PerformerName string    `json:"performer_name"`
}

// Lịch sử phê duyệt theo khoảng thời gian — báo cáo quản lý
func (q *Queries) ListApprovalActionsByDateRange(ctx context.Context, arg ListApprovalActionsByDateRangeParams) ([]ListApprovalActionsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listApprovalActionsByDateRange,
		arg.PerformedAt,
		arg.PerformedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovalActionsByDateRangeRow{}
	for rows.Next() {
		var i ListApprovalActionsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.DealModule,
			&i.DealID,
			&i.ActionType,
			&i.StatusBefore,
			&i.StatusAfter,
			&i.PerformedBy,
			&i.PerformedAt,
			&i.Reason,
			&i.Metadata,
			&i.PerformerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalActionsByDeal = `-- name: ListApprovalActionsByDeal :many
SELECT
    aa.id, aa.deal_module, aa.deal_id, aa.action_type, aa.status_before, aa.status_after, aa.performed_by, aa.performed_at, aa.reason, aa.metadata,
    u.full_name AS performer_name,
    u.department AS performer_department
FROM approval_actions aa
JOIN users u ON u.id = aa.performed_by
WHERE aa.deal_module = $1 AND aa.deal_id = $2
ORDER BY aa.performed_at ASC
`

type ListApprovalActionsByDealParams struct {
	DealModule string    `json:"deal_module"`
	DealID     uuid.UUID `json:"deal_id"`
}

type ListApprovalActionsByDealRow struct {
	ID                  uuid.UUID `json:"id"`
	DealModule          string    `json:"deal_module"`
	DealID              uuid.UUID `json:"deal_id"`
	ActionType          string    `json:"action_type"`
	StatusBefore        string    `json:"status_before"`
	StatusAfter         string    `json:"status_after"`
	PerformedBy         uuid.UUID `json:"performed_by"`
	PerformedAt         time.Time `json:"performed_at"`
	Reason              *string   `json:"reason"`
	Metadata            []byte    `json:"metadata"`
	PerformerName       string    `json:"performer_name"`
	PerformerDepartment *string   `json:"performer_department"`
}

// Lịch sử phê duyệt theo deal — timeline hiển thị trên UI
func (q *Queries) ListApprovalActionsByDeal(ctx context.Context, arg ListApprovalActionsByDealParams) ([]ListApprovalActionsByDealRow, error) {
	rows, err := q.db.Query(ctx, listApprovalActionsByDeal, arg.DealModule, arg.DealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovalActionsByDealRow{}
	for rows.Next() {
		var i ListApprovalActionsByDealRow
		if err := rows.Scan(
			&i.ID,
			&i.DealModule,
			&i.DealID,
			&i.ActionType,
			&i.StatusBefore,
			&i.StatusAfter,
			&i.PerformedBy,
			&i.PerformedAt,
			&i.Reason,
			&i.Metadata,
			&i.PerformerName,
			&i.PerformerDepartment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalActionsByUser = `-- name: ListApprovalActionsByUser :many
SELECT id, deal_module, deal_id, action_type, status_before, status_after, performed_by, performed_at, reason, metadata FROM approval_actions
WHERE performed_by = $1
ORDER BY performed_at DESC
LIMIT $2 OFFSET $3
`

type ListApprovalActionsByUserParams struct {
	PerformedBy uuid.UUID `json:"performed_by"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

// Lịch sử phê duyệt của user — báo cáo cá nhân
func (q *Queries) ListApprovalActionsByUser(ctx context.Context, arg ListApprovalActionsByUserParams) ([]ApprovalAction, error) {
	rows, err := q.db.Query(ctx, listApprovalActionsByUser, arg.PerformedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalAction{}
	for rows.Next() {
		var i ApprovalAction
		if err := rows.Scan(
			&i.ID,
			&i.DealModule,
			&i.DealID,
			&i.ActionType,
			&i.StatusBefore,
			&i.StatusAfter,
			&i.PerformedBy,
			&i.PerformedAt,
			&i.Reason,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalsByRole = `-- name: ListPendingApprovalsByRole :many
SELECT DISTINCT
    aa.deal_module,
    aa.deal_id,
    aa.status_after AS current_status,
    aa.performed_at AS last_action_at,
    str.to_status AS expected_next_status,
    str.required_role
FROM approval_actions aa
JOIN status_transition_rules str ON
    str.deal_module = aa.deal_module
    AND str.from_status = aa.status_after
    AND str.is_active = true
WHERE str.required_role = $1
  AND aa.performed_at = (
      SELECT MAX(aa2.performed_at)
      FROM approval_actions aa2
      WHERE aa2.deal_module = aa.deal_module
        AND aa2.deal_id = aa.deal_id
  )
ORDER BY aa.performed_at ASC
LIMIT $2 OFFSET $3
`

type ListPendingApprovalsByRoleParams struct {
	RequiredRole string `json:"required_role"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

type ListPendingApprovalsByRoleRow struct {
	DealModule         string    `json:"deal_module"`
	DealID             uuid.UUID `json:"deal_id"`
	CurrentStatus      string    `json:"current_status"`
	LastActionAt       time.Time `json:"last_action_at"`
	ExpectedNextStatus string    `json:"expected_next_status"`
	RequiredRole       string    `json:"required_role"`
}

// Danh sách deal đang chờ role cụ thể phê duyệt
// Join status_transition_rules để biết role nào cần duyệt tiếp
func (q *Queries) ListPendingApprovalsByRole(ctx context.Context, arg ListPendingApprovalsByRoleParams) ([]ListPendingApprovalsByRoleRow, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalsByRole, arg.RequiredRole, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingApprovalsByRoleRow{}
	for rows.Next() {
		var i ListPendingApprovalsByRoleRow
		if err := rows.Scan(
			&i.DealModule,
			&i.DealID,
			&i.CurrentStatus,
			&i.LastActionAt,
			&i.ExpectedNextStatus,
			&i.RequiredRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
