// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogsByAction = `-- name: CountAuditLogsByAction :many
SELECT action, COUNT(*) AS total
FROM audit_logs
WHERE performed_at BETWEEN $1 AND $2
GROUP BY action
ORDER BY total DESC
`

type CountAuditLogsByActionParams struct {
	PerformedAt   time.Time `json:"performed_at"`
	PerformedAt_2 time.Time `json:"performed_at_2"`
}

type CountAuditLogsByActionRow struct {
	Action string `json:"action"`
	Total  int64  `json:"total"`
}

// Thống kê số lượng theo action — dashboard chart
func (q *Queries) CountAuditLogsByAction(ctx context.Context, arg CountAuditLogsByActionParams) ([]CountAuditLogsByActionRow, error) {
	rows, err := q.db.Query(ctx, countAuditLogsByAction, arg.PerformedAt, arg.PerformedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditLogsByActionRow{}
	for rows.Next() {
		var i CountAuditLogsByActionRow
		if err := rows.Scan(&i.Action, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_logs (
    id, user_id, user_full_name, user_department, user_branch_code,
    action, deal_module, deal_id,
    status_before, status_after,
    old_values, new_values, reason,
    ip_address, user_agent, performed_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, NOW()
)
RETURNING id, user_id, user_full_name, user_department, user_branch_code, action, deal_module, deal_id, status_before, status_after, old_values, new_values, reason, ip_address, user_agent, performed_at
`

type CreateAuditLogParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	UserFullName   string      `json:"user_full_name"`
	UserDepartment *string     `json:"user_department"`
	UserBranchCode *string     `json:"user_branch_code"`
	Action         string      `json:"action"`
	DealModule     string      `json:"deal_module"`
	DealID         pgtype.UUID `json:"deal_id"`
	StatusBefore   *string     `json:"status_before"`
	StatusAfter    *string     `json:"status_after"`
	OldValues      []byte      `json:"old_values"`
	NewValues      []byte      `json:"new_values"`
	Reason         *string     `json:"reason"`
	IpAddress      string      `json:"ip_address"`
	UserAgent      *string     `json:"user_agent"`
}

// ============================================================================
// audit_logs.sql — Queries for audit_logs table (partitioned)
// Treasury Management System — KienlongBank
// ============================================================================
// Ghi nhật ký kiểm toán — APPEND-ONLY, không sửa/xóa
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.UserFullName,
		arg.UserDepartment,
		arg.UserBranchCode,
		arg.Action,
		arg.DealModule,
		arg.DealID,
		arg.StatusBefore,
		arg.StatusAfter,
		arg.OldValues,
		arg.NewValues,
		arg.Reason,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserFullName,
		&i.UserDepartment,
		&i.UserBranchCode,
		&i.Action,
		&i.DealModule,
		&i.DealID,
		&i.StatusBefore,
		&i.StatusAfter,
		&i.OldValues,
		&i.NewValues,
		&i.Reason,
		&i.IpAddress,
		&i.UserAgent,
		&i.PerformedAt,
	)
	return i, err
}

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, user_id, user_full_name, user_department, user_branch_code, action, deal_module, deal_id, status_before, status_after, old_values, new_values, reason, ip_address, user_agent, performed_at FROM audit_logs
WHERE id = $1 AND performed_at = $2
`

type GetAuditLogByIDParams struct {
	ID          uuid.UUID `json:"id"`
	PerformedAt time.Time `json:"performed_at"`
}

func (q *Queries) GetAuditLogByID(ctx context.Context, arg GetAuditLogByIDParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, arg.ID, arg.PerformedAt)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserFullName,
		&i.UserDepartment,
		&i.UserBranchCode,
		&i.Action,
		&i.DealModule,
		&i.DealID,
		&i.StatusBefore,
		&i.StatusAfter,
		&i.OldValues,
		&i.NewValues,
		&i.Reason,
		&i.IpAddress,
		&i.UserAgent,
		&i.PerformedAt,
	)
	return i, err
}

const listAuditLogsByDateRange = `-- name: ListAuditLogsByDateRange :many
SELECT id, user_id, user_full_name, user_department, user_branch_code, action, deal_module, deal_id, status_before, status_after, old_values, new_values, reason, ip_address, user_agent, performed_at FROM audit_logs
WHERE performed_at BETWEEN $1 AND $2
ORDER BY performed_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditLogsByDateRangeParams struct {
	PerformedAt   time.Time `json:"performed_at"`
	PerformedAt_2 time.Time `json:"performed_at_2"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

// Nhật ký theo khoảng thời gian — báo cáo kiểm toán định kỳ
// Partition pruning tự động khi filter theo performed_at
func (q *Queries) ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByDateRange,
		arg.PerformedAt,
		arg.PerformedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserFullName,
			&i.UserDepartment,
			&i.UserBranchCode,
			&i.Action,
			&i.DealModule,
			&i.DealID,
			&i.StatusBefore,
			&i.StatusAfter,
			&i.OldValues,
			&i.NewValues,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByDeal = `-- name: ListAuditLogsByDeal :many
SELECT id, user_id, user_full_name, user_department, user_branch_code, action, deal_module, deal_id, status_before, status_after, old_values, new_values, reason, ip_address, user_agent, performed_at FROM audit_logs
WHERE deal_module = $1 AND deal_id = $2
ORDER BY performed_at ASC
`

type ListAuditLogsByDealParams struct {
	DealModule string      `json:"deal_module"`
	DealID     pgtype.UUID `json:"deal_id"`
}

// Lịch sử kiểm toán theo deal — audit trail trên deal detail
func (q *Queries) ListAuditLogsByDeal(ctx context.Context, arg ListAuditLogsByDealParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByDeal, arg.DealModule, arg.DealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserFullName,
			&i.UserDepartment,
			&i.UserBranchCode,
			&i.Action,
			&i.DealModule,
			&i.DealID,
			&i.StatusBefore,
			&i.StatusAfter,
			&i.OldValues,
			&i.NewValues,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByModule = `-- name: ListAuditLogsByModule :many
SELECT id, user_id, user_full_name, user_department, user_branch_code, action, deal_module, deal_id, status_before, status_after, old_values, new_values, reason, ip_address, user_agent, performed_at FROM audit_logs
WHERE deal_module = $1
  AND performed_at BETWEEN $2 AND $3
ORDER BY performed_at DESC
LIMIT $4 OFFSET $5
`

type ListAuditLogsByModuleParams struct {
	DealModule    string    `json:"deal_module"`
	PerformedAt   time.Time `json:"performed_at"`
	PerformedAt_2 time.Time `json:"performed_at_2"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

// Lịch sử theo module — báo cáo theo nghiệp vụ
func (q *Queries) ListAuditLogsByModule(ctx context.Context, arg ListAuditLogsByModuleParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByModule,
		arg.DealModule,
		arg.PerformedAt,
		arg.PerformedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserFullName,
			&i.UserDepartment,
			&i.UserBranchCode,
			&i.Action,
			&i.DealModule,
			&i.DealID,
			&i.StatusBefore,
			&i.StatusAfter,
			&i.OldValues,
			&i.NewValues,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, user_id, user_full_name, user_department, user_branch_code, action, deal_module, deal_id, status_before, status_after, old_values, new_values, reason, ip_address, user_agent, performed_at FROM audit_logs
WHERE user_id = $1
ORDER BY performed_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

// Lịch sử thao tác của user — user activity report
func (q *Queries) ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserFullName,
			&i.UserDepartment,
			&i.UserBranchCode,
			&i.Action,
			&i.DealModule,
			&i.DealID,
			&i.StatusBefore,
			&i.StatusAfter,
			&i.OldValues,
			&i.NewValues,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUserAndModule = `-- name: ListAuditLogsByUserAndModule :many
SELECT id, user_id, user_full_name, user_department, user_branch_code, action, deal_module, deal_id, status_before, status_after, old_values, new_values, reason, ip_address, user_agent, performed_at FROM audit_logs
WHERE user_id = $1
  AND deal_module = $2
  AND performed_at BETWEEN $3 AND $4
ORDER BY performed_at DESC
LIMIT $5 OFFSET $6
`

type ListAuditLogsByUserAndModuleParams struct {
	UserID        uuid.UUID `json:"user_id"`
	DealModule    string    `json:"deal_module"`
	PerformedAt   time.Time `json:"performed_at"`
	PerformedAt_2 time.Time `json:"performed_at_2"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

// Lịch sử user trên module cụ thể — compliance check
func (q *Queries) ListAuditLogsByUserAndModule(ctx context.Context, arg ListAuditLogsByUserAndModuleParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByUserAndModule,
		arg.UserID,
		arg.DealModule,
		arg.PerformedAt,
		arg.PerformedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserFullName,
			&i.UserDepartment,
			&i.UserBranchCode,
			&i.Action,
			&i.DealModule,
			&i.DealID,
			&i.StatusBefore,
			&i.StatusAfter,
			&i.OldValues,
			&i.NewValues,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAuditLogsByAction = `-- name: SearchAuditLogsByAction :many
SELECT id, user_id, user_full_name, user_department, user_branch_code, action, deal_module, deal_id, status_before, status_after, old_values, new_values, reason, ip_address, user_agent, performed_at FROM audit_logs
WHERE action = $1
  AND performed_at BETWEEN $2 AND $3
ORDER BY performed_at DESC
LIMIT $4 OFFSET $5
`

type SearchAuditLogsByActionParams struct {
	Action        string    `json:"action"`
	PerformedAt   time.Time `json:"performed_at"`
	PerformedAt_2 time.Time `json:"performed_at_2"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

// Tìm theo loại hành động — vd: tất cả REJECT trong tháng
func (q *Queries) SearchAuditLogsByAction(ctx context.Context, arg SearchAuditLogsByActionParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, searchAuditLogsByAction,
		arg.Action,
		arg.PerformedAt,
		arg.PerformedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserFullName,
			&i.UserDepartment,
			&i.UserBranchCode,
			&i.Action,
			&i.DealModule,
			&i.DealID,
			&i.StatusBefore,
			&i.StatusAfter,
			&i.OldValues,
			&i.NewValues,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
