// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bond_inventory.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBondInventory = `-- name: CreateBondInventory :one

INSERT INTO bond_inventory (
    id, bond_catalog_id, bond_code, bond_category, portfolio_type,
    available_quantity, acquisition_date, acquisition_price,
    version, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7,
    1, NOW(), $8
)
RETURNING id, bond_catalog_id, bond_code, bond_category, portfolio_type, available_quantity, acquisition_date, acquisition_price, version, updated_at, updated_by
`

type CreateBondInventoryParams struct {
	BondCatalogID     pgtype.UUID    `json:"bond_catalog_id"`
	BondCode          string         `json:"bond_code"`
	BondCategory      string         `json:"bond_category"`
	PortfolioType     string         `json:"portfolio_type"`
	AvailableQuantity int64          `json:"available_quantity"`
	AcquisitionDate   pgtype.Date    `json:"acquisition_date"`
	AcquisitionPrice  pgtype.Numeric `json:"acquisition_price"`
	UpdatedBy         pgtype.UUID    `json:"updated_by"`
}

// ============================================================================
// bond_inventory.sql — Queries for bond_inventory table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateBondInventory(ctx context.Context, arg CreateBondInventoryParams) (BondInventory, error) {
	row := q.db.QueryRow(ctx, createBondInventory,
		arg.BondCatalogID,
		arg.BondCode,
		arg.BondCategory,
		arg.PortfolioType,
		arg.AvailableQuantity,
		arg.AcquisitionDate,
		arg.AcquisitionPrice,
		arg.UpdatedBy,
	)
	var i BondInventory
	err := row.Scan(
		&i.ID,
		&i.BondCatalogID,
		&i.BondCode,
		&i.BondCategory,
		&i.PortfolioType,
		&i.AvailableQuantity,
		&i.AcquisitionDate,
		&i.AcquisitionPrice,
		&i.Version,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const decrementBondQuantity = `-- name: DecrementBondQuantity :one
UPDATE bond_inventory SET
    available_quantity = available_quantity - $5::BIGINT,
    version = version + 1,
    updated_by = $1
WHERE bond_code = $2
  AND bond_category = $3
  AND portfolio_type = $4
  AND version = $6::INT
  AND available_quantity >= $5::BIGINT
RETURNING id, bond_catalog_id, bond_code, bond_category, portfolio_type, available_quantity, acquisition_date, acquisition_price, version, updated_at, updated_by
`

type DecrementBondQuantityParams struct {
	UpdatedBy       pgtype.UUID `json:"updated_by"`
	BondCode        string      `json:"bond_code"`
	BondCategory    string      `json:"bond_category"`
	PortfolioType   string      `json:"portfolio_type"`
	SellQuantity    int64       `json:"sell_quantity"`
	ExpectedVersion int32       `json:"expected_version"`
}

// Giảm tồn kho khi bán — OPTIMISTIC LOCKING qua version check
// Nếu version không khớp → row không được update → application retry
// Nếu available_quantity < sell_quantity → CHECK constraint fail → error
func (q *Queries) DecrementBondQuantity(ctx context.Context, arg DecrementBondQuantityParams) (BondInventory, error) {
	row := q.db.QueryRow(ctx, decrementBondQuantity,
		arg.UpdatedBy,
		arg.BondCode,
		arg.BondCategory,
		arg.PortfolioType,
		arg.SellQuantity,
		arg.ExpectedVersion,
	)
	var i BondInventory
	err := row.Scan(
		&i.ID,
		&i.BondCatalogID,
		&i.BondCode,
		&i.BondCategory,
		&i.PortfolioType,
		&i.AvailableQuantity,
		&i.AcquisitionDate,
		&i.AcquisitionPrice,
		&i.Version,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAvailableQuantity = `-- name: GetAvailableQuantity :one
SELECT available_quantity FROM bond_inventory
WHERE bond_code = $1 AND bond_category = $2 AND portfolio_type = $3
`

type GetAvailableQuantityParams struct {
	BondCode      string `json:"bond_code"`
	BondCategory  string `json:"bond_category"`
	PortfolioType string `json:"portfolio_type"`
}

// Lấy số lượng khả dụng — dùng cho validation trước khi bán
func (q *Queries) GetAvailableQuantity(ctx context.Context, arg GetAvailableQuantityParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAvailableQuantity, arg.BondCode, arg.BondCategory, arg.PortfolioType)
	var available_quantity int64
	err := row.Scan(&available_quantity)
	return available_quantity, err
}

const getBondInventoryByBondCode = `-- name: GetBondInventoryByBondCode :one
SELECT id, bond_catalog_id, bond_code, bond_category, portfolio_type, available_quantity, acquisition_date, acquisition_price, version, updated_at, updated_by FROM bond_inventory
WHERE bond_code = $1 AND bond_category = $2 AND portfolio_type = $3
`

type GetBondInventoryByBondCodeParams struct {
	BondCode      string `json:"bond_code"`
	BondCategory  string `json:"bond_category"`
	PortfolioType string `json:"portfolio_type"`
}

// Lấy tồn kho theo bond_code + category + portfolio
func (q *Queries) GetBondInventoryByBondCode(ctx context.Context, arg GetBondInventoryByBondCodeParams) (BondInventory, error) {
	row := q.db.QueryRow(ctx, getBondInventoryByBondCode, arg.BondCode, arg.BondCategory, arg.PortfolioType)
	var i BondInventory
	err := row.Scan(
		&i.ID,
		&i.BondCatalogID,
		&i.BondCode,
		&i.BondCategory,
		&i.PortfolioType,
		&i.AvailableQuantity,
		&i.AcquisitionDate,
		&i.AcquisitionPrice,
		&i.Version,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getBondInventoryByID = `-- name: GetBondInventoryByID :one
SELECT id, bond_catalog_id, bond_code, bond_category, portfolio_type, available_quantity, acquisition_date, acquisition_price, version, updated_at, updated_by FROM bond_inventory WHERE id = $1
`

func (q *Queries) GetBondInventoryByID(ctx context.Context, id uuid.UUID) (BondInventory, error) {
	row := q.db.QueryRow(ctx, getBondInventoryByID, id)
	var i BondInventory
	err := row.Scan(
		&i.ID,
		&i.BondCatalogID,
		&i.BondCode,
		&i.BondCategory,
		&i.PortfolioType,
		&i.AvailableQuantity,
		&i.AcquisitionDate,
		&i.AcquisitionPrice,
		&i.Version,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const incrementBondQuantity = `-- name: IncrementBondQuantity :one
UPDATE bond_inventory SET
    available_quantity = available_quantity + $5::BIGINT,
    version = version + 1,
    updated_by = $1
WHERE bond_code = $2 AND bond_category = $3 AND portfolio_type = $4
RETURNING id, bond_catalog_id, bond_code, bond_category, portfolio_type, available_quantity, acquisition_date, acquisition_price, version, updated_at, updated_by
`

type IncrementBondQuantityParams struct {
	UpdatedBy     pgtype.UUID `json:"updated_by"`
	BondCode      string      `json:"bond_code"`
	BondCategory  string      `json:"bond_category"`
	PortfolioType string      `json:"portfolio_type"`
	BuyQuantity   int64       `json:"buy_quantity"`
}

// Tăng tồn kho khi mua hoàn thành
func (q *Queries) IncrementBondQuantity(ctx context.Context, arg IncrementBondQuantityParams) (BondInventory, error) {
	row := q.db.QueryRow(ctx, incrementBondQuantity,
		arg.UpdatedBy,
		arg.BondCode,
		arg.BondCategory,
		arg.PortfolioType,
		arg.BuyQuantity,
	)
	var i BondInventory
	err := row.Scan(
		&i.ID,
		&i.BondCatalogID,
		&i.BondCode,
		&i.BondCategory,
		&i.PortfolioType,
		&i.AvailableQuantity,
		&i.AcquisitionDate,
		&i.AcquisitionPrice,
		&i.Version,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listBondInventory = `-- name: ListBondInventory :many
SELECT id, bond_catalog_id, bond_code, bond_category, portfolio_type, available_quantity, acquisition_date, acquisition_price, version, updated_at, updated_by FROM bond_inventory
WHERE available_quantity > 0
ORDER BY bond_code ASC
LIMIT $1 OFFSET $2
`

type ListBondInventoryParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBondInventory(ctx context.Context, arg ListBondInventoryParams) ([]BondInventory, error) {
	rows, err := q.db.Query(ctx, listBondInventory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BondInventory{}
	for rows.Next() {
		var i BondInventory
		if err := rows.Scan(
			&i.ID,
			&i.BondCatalogID,
			&i.BondCode,
			&i.BondCategory,
			&i.PortfolioType,
			&i.AvailableQuantity,
			&i.AcquisitionDate,
			&i.AcquisitionPrice,
			&i.Version,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBondInventoryByCategory = `-- name: ListBondInventoryByCategory :many
SELECT id, bond_catalog_id, bond_code, bond_category, portfolio_type, available_quantity, acquisition_date, acquisition_price, version, updated_at, updated_by FROM bond_inventory
WHERE bond_category = $1 AND available_quantity > 0
ORDER BY bond_code ASC
LIMIT $2 OFFSET $3
`

type ListBondInventoryByCategoryParams struct {
	BondCategory string `json:"bond_category"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListBondInventoryByCategory(ctx context.Context, arg ListBondInventoryByCategoryParams) ([]BondInventory, error) {
	rows, err := q.db.Query(ctx, listBondInventoryByCategory, arg.BondCategory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BondInventory{}
	for rows.Next() {
		var i BondInventory
		if err := rows.Scan(
			&i.ID,
			&i.BondCatalogID,
			&i.BondCode,
			&i.BondCategory,
			&i.PortfolioType,
			&i.AvailableQuantity,
			&i.AcquisitionDate,
			&i.AcquisitionPrice,
			&i.Version,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBondInventory = `-- name: UpsertBondInventory :one
INSERT INTO bond_inventory (
    id, bond_catalog_id, bond_code, bond_category, portfolio_type,
    available_quantity, acquisition_date, acquisition_price,
    version, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, 1, NOW(), $8
)
ON CONFLICT (bond_code, bond_category, portfolio_type) DO UPDATE SET
    available_quantity = bond_inventory.available_quantity + EXCLUDED.available_quantity,
    version = bond_inventory.version + 1,
    updated_by = EXCLUDED.updated_by
RETURNING id, bond_catalog_id, bond_code, bond_category, portfolio_type, available_quantity, acquisition_date, acquisition_price, version, updated_at, updated_by
`

type UpsertBondInventoryParams struct {
	BondCatalogID     pgtype.UUID    `json:"bond_catalog_id"`
	BondCode          string         `json:"bond_code"`
	BondCategory      string         `json:"bond_category"`
	PortfolioType     string         `json:"portfolio_type"`
	AvailableQuantity int64          `json:"available_quantity"`
	AcquisitionDate   pgtype.Date    `json:"acquisition_date"`
	AcquisitionPrice  pgtype.Numeric `json:"acquisition_price"`
	UpdatedBy         pgtype.UUID    `json:"updated_by"`
}

// Insert hoặc update tồn kho — dùng khi mua bond mới chưa có record
func (q *Queries) UpsertBondInventory(ctx context.Context, arg UpsertBondInventoryParams) (BondInventory, error) {
	row := q.db.QueryRow(ctx, upsertBondInventory,
		arg.BondCatalogID,
		arg.BondCode,
		arg.BondCategory,
		arg.PortfolioType,
		arg.AvailableQuantity,
		arg.AcquisitionDate,
		arg.AcquisitionPrice,
		arg.UpdatedBy,
	)
	var i BondInventory
	err := row.Scan(
		&i.ID,
		&i.BondCatalogID,
		&i.BondCode,
		&i.BondCategory,
		&i.PortfolioType,
		&i.AvailableQuantity,
		&i.AcquisitionDate,
		&i.AcquisitionPrice,
		&i.Version,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
