// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bond_deals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkInventoryBeforeSell = `-- name: CheckInventoryBeforeSell :one
SELECT COALESCE(bi.available_quantity, 0) AS available_quantity
FROM bond_inventory bi
WHERE bi.bond_code = $1
  AND bi.bond_category = $2
  AND bi.portfolio_type = $3
`

type CheckInventoryBeforeSellParams struct {
	BondCode      string `json:"bond_code"`
	BondCategory  string `json:"bond_category"`
	PortfolioType string `json:"portfolio_type"`
}

// Kiểm tra tồn kho trước khi bán — hard block nếu không đủ
// Trả về available_quantity: 0 nếu không tìm thấy record
func (q *Queries) CheckInventoryBeforeSell(ctx context.Context, arg CheckInventoryBeforeSellParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkInventoryBeforeSell, arg.BondCode, arg.BondCategory, arg.PortfolioType)
	var available_quantity int64
	err := row.Scan(&available_quantity)
	return available_quantity, err
}

const countBondDeals = `-- name: CountBondDeals :one
SELECT COUNT(*) FROM bond_deals WHERE deleted_at IS NULL
`

func (q *Queries) CountBondDeals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBondDeals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBondDeal = `-- name: CreateBondDeal :one

INSERT INTO bond_deals (
    id, deal_number, bond_category, trade_date, branch_id,
    order_date, value_date, direction, counterparty_id,
    transaction_type, transaction_type_other,
    bond_catalog_id, bond_code_manual, issuer, coupon_rate,
    issue_date, maturity_date, quantity, face_value,
    discount_rate, clean_price, settlement_price, total_value,
    portfolio_type, payment_date, remaining_tenor_days,
    confirmation_method, confirmation_other, contract_prepared_by,
    status, note, cloned_from_id,
    created_at, created_by, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22,
    $23, $24, $25, $26, $27, $28,
    'OPEN', $29, $30,
    NOW(), $31, NOW(), $31
)
RETURNING id, deal_number, bond_category, trade_date, branch_id, order_date, value_date, direction, counterparty_id, transaction_type, transaction_type_other, bond_catalog_id, bond_code_manual, issuer, coupon_rate, issue_date, maturity_date, quantity, face_value, discount_rate, clean_price, settlement_price, total_value, portfolio_type, payment_date, remaining_tenor_days, confirmation_method, confirmation_other, contract_prepared_by, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type CreateBondDealParams struct {
	DealNumber           string         `json:"deal_number"`
	BondCategory         string         `json:"bond_category"`
	TradeDate            pgtype.Date    `json:"trade_date"`
	BranchID             uuid.UUID      `json:"branch_id"`
	OrderDate            pgtype.Date    `json:"order_date"`
	ValueDate            pgtype.Date    `json:"value_date"`
	Direction            string         `json:"direction"`
	CounterpartyID       uuid.UUID      `json:"counterparty_id"`
	TransactionType      string         `json:"transaction_type"`
	TransactionTypeOther *string        `json:"transaction_type_other"`
	BondCatalogID        pgtype.UUID    `json:"bond_catalog_id"`
	BondCodeManual       *string        `json:"bond_code_manual"`
	Issuer               string         `json:"issuer"`
	CouponRate           pgtype.Numeric `json:"coupon_rate"`
	IssueDate            pgtype.Date    `json:"issue_date"`
	MaturityDate         pgtype.Date    `json:"maturity_date"`
	Quantity             int64          `json:"quantity"`
	FaceValue            pgtype.Numeric `json:"face_value"`
	DiscountRate         pgtype.Numeric `json:"discount_rate"`
	CleanPrice           pgtype.Numeric `json:"clean_price"`
	SettlementPrice      pgtype.Numeric `json:"settlement_price"`
	TotalValue           pgtype.Numeric `json:"total_value"`
	PortfolioType        *string        `json:"portfolio_type"`
	PaymentDate          pgtype.Date    `json:"payment_date"`
	RemainingTenorDays   int32          `json:"remaining_tenor_days"`
	ConfirmationMethod   string         `json:"confirmation_method"`
	ConfirmationOther    *string        `json:"confirmation_other"`
	ContractPreparedBy   string         `json:"contract_prepared_by"`
	Note                 *string        `json:"note"`
	ClonedFromID         pgtype.UUID    `json:"cloned_from_id"`
	CreatedBy            uuid.UUID      `json:"created_by"`
}

// ============================================================================
// bond_deals.sql — Queries for bond_deals table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateBondDeal(ctx context.Context, arg CreateBondDealParams) (BondDeal, error) {
	row := q.db.QueryRow(ctx, createBondDeal,
		arg.DealNumber,
		arg.BondCategory,
		arg.TradeDate,
		arg.BranchID,
		arg.OrderDate,
		arg.ValueDate,
		arg.Direction,
		arg.CounterpartyID,
		arg.TransactionType,
		arg.TransactionTypeOther,
		arg.BondCatalogID,
		arg.BondCodeManual,
		arg.Issuer,
		arg.CouponRate,
		arg.IssueDate,
		arg.MaturityDate,
		arg.Quantity,
		arg.FaceValue,
		arg.DiscountRate,
		arg.CleanPrice,
		arg.SettlementPrice,
		arg.TotalValue,
		arg.PortfolioType,
		arg.PaymentDate,
		arg.RemainingTenorDays,
		arg.ConfirmationMethod,
		arg.ConfirmationOther,
		arg.ContractPreparedBy,
		arg.Note,
		arg.ClonedFromID,
		arg.CreatedBy,
	)
	var i BondDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.BondCategory,
		&i.TradeDate,
		&i.BranchID,
		&i.OrderDate,
		&i.ValueDate,
		&i.Direction,
		&i.CounterpartyID,
		&i.TransactionType,
		&i.TransactionTypeOther,
		&i.BondCatalogID,
		&i.BondCodeManual,
		&i.Issuer,
		&i.CouponRate,
		&i.IssueDate,
		&i.MaturityDate,
		&i.Quantity,
		&i.FaceValue,
		&i.DiscountRate,
		&i.CleanPrice,
		&i.SettlementPrice,
		&i.TotalValue,
		&i.PortfolioType,
		&i.PaymentDate,
		&i.RemainingTenorDays,
		&i.ConfirmationMethod,
		&i.ConfirmationOther,
		&i.ContractPreparedBy,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getBondDealByID = `-- name: GetBondDealByID :one
SELECT id, deal_number, bond_category, trade_date, branch_id, order_date, value_date, direction, counterparty_id, transaction_type, transaction_type_other, bond_catalog_id, bond_code_manual, issuer, coupon_rate, issue_date, maturity_date, quantity, face_value, discount_rate, clean_price, settlement_price, total_value, portfolio_type, payment_date, remaining_tenor_days, confirmation_method, confirmation_other, contract_prepared_by, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM bond_deals
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBondDealByID(ctx context.Context, id uuid.UUID) (BondDeal, error) {
	row := q.db.QueryRow(ctx, getBondDealByID, id)
	var i BondDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.BondCategory,
		&i.TradeDate,
		&i.BranchID,
		&i.OrderDate,
		&i.ValueDate,
		&i.Direction,
		&i.CounterpartyID,
		&i.TransactionType,
		&i.TransactionTypeOther,
		&i.BondCatalogID,
		&i.BondCodeManual,
		&i.Issuer,
		&i.CouponRate,
		&i.IssueDate,
		&i.MaturityDate,
		&i.Quantity,
		&i.FaceValue,
		&i.DiscountRate,
		&i.CleanPrice,
		&i.SettlementPrice,
		&i.TotalValue,
		&i.PortfolioType,
		&i.PaymentDate,
		&i.RemainingTenorDays,
		&i.ConfirmationMethod,
		&i.ConfirmationOther,
		&i.ContractPreparedBy,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getNextBondDealCode = `-- name: GetNextBondDealCode :one
SELECT
    CASE
        WHEN $1 = 'GOVERNMENT' THEN 'G'
        ELSE 'F'
    END AS prefix
`

// Lấy deal code tiếp theo để sinh prefix: G (Govi) hoặc F (FI/CD)
// Application logic: bond_category = 'GOVERNMENT' → prefix 'G', else 'F'
func (q *Queries) GetNextBondDealCode(ctx context.Context, dollar_1 interface{}) (string, error) {
	row := q.db.QueryRow(ctx, getNextBondDealCode, dollar_1)
	var prefix string
	err := row.Scan(&prefix)
	return prefix, err
}

const listBondDeals = `-- name: ListBondDeals :many
SELECT id, deal_number, bond_category, trade_date, branch_id, order_date, value_date, direction, counterparty_id, transaction_type, transaction_type_other, bond_catalog_id, bond_code_manual, issuer, coupon_rate, issue_date, maturity_date, quantity, face_value, discount_rate, clean_price, settlement_price, total_value, portfolio_type, payment_date, remaining_tenor_days, confirmation_method, confirmation_other, contract_prepared_by, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM bond_deals
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBondDealsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBondDeals(ctx context.Context, arg ListBondDealsParams) ([]BondDeal, error) {
	rows, err := q.db.Query(ctx, listBondDeals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BondDeal{}
	for rows.Next() {
		var i BondDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.BondCategory,
			&i.TradeDate,
			&i.BranchID,
			&i.OrderDate,
			&i.ValueDate,
			&i.Direction,
			&i.CounterpartyID,
			&i.TransactionType,
			&i.TransactionTypeOther,
			&i.BondCatalogID,
			&i.BondCodeManual,
			&i.Issuer,
			&i.CouponRate,
			&i.IssueDate,
			&i.MaturityDate,
			&i.Quantity,
			&i.FaceValue,
			&i.DiscountRate,
			&i.CleanPrice,
			&i.SettlementPrice,
			&i.TotalValue,
			&i.PortfolioType,
			&i.PaymentDate,
			&i.RemainingTenorDays,
			&i.ConfirmationMethod,
			&i.ConfirmationOther,
			&i.ContractPreparedBy,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBondDealsByCategory = `-- name: ListBondDealsByCategory :many
SELECT id, deal_number, bond_category, trade_date, branch_id, order_date, value_date, direction, counterparty_id, transaction_type, transaction_type_other, bond_catalog_id, bond_code_manual, issuer, coupon_rate, issue_date, maturity_date, quantity, face_value, discount_rate, clean_price, settlement_price, total_value, portfolio_type, payment_date, remaining_tenor_days, confirmation_method, confirmation_other, contract_prepared_by, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM bond_deals
WHERE bond_category = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBondDealsByCategoryParams struct {
	BondCategory string `json:"bond_category"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

// Lọc theo loại: GOVERNMENT (TPCP), FINANCIAL_INSTITUTION (TCTC), CERTIFICATE_OF_DEPOSIT (GTCG)
func (q *Queries) ListBondDealsByCategory(ctx context.Context, arg ListBondDealsByCategoryParams) ([]BondDeal, error) {
	rows, err := q.db.Query(ctx, listBondDealsByCategory, arg.BondCategory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BondDeal{}
	for rows.Next() {
		var i BondDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.BondCategory,
			&i.TradeDate,
			&i.BranchID,
			&i.OrderDate,
			&i.ValueDate,
			&i.Direction,
			&i.CounterpartyID,
			&i.TransactionType,
			&i.TransactionTypeOther,
			&i.BondCatalogID,
			&i.BondCodeManual,
			&i.Issuer,
			&i.CouponRate,
			&i.IssueDate,
			&i.MaturityDate,
			&i.Quantity,
			&i.FaceValue,
			&i.DiscountRate,
			&i.CleanPrice,
			&i.SettlementPrice,
			&i.TotalValue,
			&i.PortfolioType,
			&i.PaymentDate,
			&i.RemainingTenorDays,
			&i.ConfirmationMethod,
			&i.ConfirmationOther,
			&i.ContractPreparedBy,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBondDealsByStatus = `-- name: ListBondDealsByStatus :many
SELECT id, deal_number, bond_category, trade_date, branch_id, order_date, value_date, direction, counterparty_id, transaction_type, transaction_type_other, bond_catalog_id, bond_code_manual, issuer, coupon_rate, issue_date, maturity_date, quantity, face_value, discount_rate, clean_price, settlement_price, total_value, portfolio_type, payment_date, remaining_tenor_days, confirmation_method, confirmation_other, contract_prepared_by, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM bond_deals
WHERE status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBondDealsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListBondDealsByStatus(ctx context.Context, arg ListBondDealsByStatusParams) ([]BondDeal, error) {
	rows, err := q.db.Query(ctx, listBondDealsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BondDeal{}
	for rows.Next() {
		var i BondDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.BondCategory,
			&i.TradeDate,
			&i.BranchID,
			&i.OrderDate,
			&i.ValueDate,
			&i.Direction,
			&i.CounterpartyID,
			&i.TransactionType,
			&i.TransactionTypeOther,
			&i.BondCatalogID,
			&i.BondCodeManual,
			&i.Issuer,
			&i.CouponRate,
			&i.IssueDate,
			&i.MaturityDate,
			&i.Quantity,
			&i.FaceValue,
			&i.DiscountRate,
			&i.CleanPrice,
			&i.SettlementPrice,
			&i.TotalValue,
			&i.PortfolioType,
			&i.PaymentDate,
			&i.RemainingTenorDays,
			&i.ConfirmationMethod,
			&i.ConfirmationOther,
			&i.ContractPreparedBy,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBondDealsPendingBooking = `-- name: ListBondDealsPendingBooking :many
SELECT id, deal_number, bond_category, trade_date, branch_id, order_date, value_date, direction, counterparty_id, transaction_type, transaction_type_other, bond_catalog_id, bond_code_manual, issuer, coupon_rate, issue_date, maturity_date, quantity, face_value, discount_rate, clean_price, settlement_price, total_value, portfolio_type, payment_date, remaining_tenor_days, confirmation_method, confirmation_other, contract_prepared_by, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM bond_deals
WHERE status IN ('PENDING_BOOKING', 'PENDING_CHIEF_ACCOUNTANT')
  AND deleted_at IS NULL
ORDER BY trade_date ASC, created_at ASC
LIMIT $1 OFFSET $2
`

type ListBondDealsPendingBookingParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// View cho KTTC: deals chờ hạch toán (L1 hoặc L2)
func (q *Queries) ListBondDealsPendingBooking(ctx context.Context, arg ListBondDealsPendingBookingParams) ([]BondDeal, error) {
	rows, err := q.db.Query(ctx, listBondDealsPendingBooking, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BondDeal{}
	for rows.Next() {
		var i BondDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.BondCategory,
			&i.TradeDate,
			&i.BranchID,
			&i.OrderDate,
			&i.ValueDate,
			&i.Direction,
			&i.CounterpartyID,
			&i.TransactionType,
			&i.TransactionTypeOther,
			&i.BondCatalogID,
			&i.BondCodeManual,
			&i.Issuer,
			&i.CouponRate,
			&i.IssueDate,
			&i.MaturityDate,
			&i.Quantity,
			&i.FaceValue,
			&i.DiscountRate,
			&i.CleanPrice,
			&i.SettlementPrice,
			&i.TotalValue,
			&i.PortfolioType,
			&i.PaymentDate,
			&i.RemainingTenorDays,
			&i.ConfirmationMethod,
			&i.ConfirmationOther,
			&i.ContractPreparedBy,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBondDealCancelRequest = `-- name: SetBondDealCancelRequest :one
UPDATE bond_deals SET
    cancel_reason = $3,
    cancel_requested_by = $1,
    cancel_requested_at = NOW(),
    status = 'CANCELLED',
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = $4
RETURNING id, deal_number, bond_category, trade_date, branch_id, order_date, value_date, direction, counterparty_id, transaction_type, transaction_type_other, bond_catalog_id, bond_code_manual, issuer, coupon_rate, issue_date, maturity_date, quantity, face_value, discount_rate, clean_price, settlement_price, total_value, portfolio_type, payment_date, remaining_tenor_days, confirmation_method, confirmation_other, contract_prepared_by, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type SetBondDealCancelRequestParams struct {
	CancelRequestedBy pgtype.UUID `json:"cancel_requested_by"`
	ID                uuid.UUID   `json:"id"`
	CancelReason      *string     `json:"cancel_reason"`
	Status            string      `json:"status"`
}

func (q *Queries) SetBondDealCancelRequest(ctx context.Context, arg SetBondDealCancelRequestParams) (BondDeal, error) {
	row := q.db.QueryRow(ctx, setBondDealCancelRequest,
		arg.CancelRequestedBy,
		arg.ID,
		arg.CancelReason,
		arg.Status,
	)
	var i BondDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.BondCategory,
		&i.TradeDate,
		&i.BranchID,
		&i.OrderDate,
		&i.ValueDate,
		&i.Direction,
		&i.CounterpartyID,
		&i.TransactionType,
		&i.TransactionTypeOther,
		&i.BondCatalogID,
		&i.BondCodeManual,
		&i.Issuer,
		&i.CouponRate,
		&i.IssueDate,
		&i.MaturityDate,
		&i.Quantity,
		&i.FaceValue,
		&i.DiscountRate,
		&i.CleanPrice,
		&i.SettlementPrice,
		&i.TotalValue,
		&i.PortfolioType,
		&i.PaymentDate,
		&i.RemainingTenorDays,
		&i.ConfirmationMethod,
		&i.ConfirmationOther,
		&i.ContractPreparedBy,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteBondDeal = `-- name: SoftDeleteBondDeal :exec
UPDATE bond_deals SET deleted_at = NOW(), updated_by = $2
WHERE id = $1 AND deleted_at IS NULL AND status = 'OPEN'
`

type SoftDeleteBondDealParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedBy uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteBondDeal(ctx context.Context, arg SoftDeleteBondDealParams) error {
	_, err := q.db.Exec(ctx, softDeleteBondDeal, arg.ID, arg.UpdatedBy)
	return err
}

const updateBondDeal = `-- name: UpdateBondDeal :one
UPDATE bond_deals SET
    order_date = COALESCE($3, order_date),
    value_date = COALESCE($4, value_date),
    counterparty_id = COALESCE($5, counterparty_id),
    transaction_type = COALESCE($6, transaction_type),
    transaction_type_other = COALESCE($7, transaction_type_other),
    bond_catalog_id = COALESCE($8, bond_catalog_id),
    bond_code_manual = COALESCE($9, bond_code_manual),
    issuer = COALESCE($10, issuer),
    coupon_rate = COALESCE($11, coupon_rate),
    quantity = COALESCE($12, quantity),
    face_value = COALESCE($13, face_value),
    discount_rate = COALESCE($14, discount_rate),
    clean_price = COALESCE($15, clean_price),
    settlement_price = COALESCE($16, settlement_price),
    total_value = COALESCE($17, total_value),
    portfolio_type = COALESCE($18, portfolio_type),
    payment_date = COALESCE($19, payment_date),
    remaining_tenor_days = COALESCE($20, remaining_tenor_days),
    note = COALESCE($21, note),
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = 'OPEN'
RETURNING id, deal_number, bond_category, trade_date, branch_id, order_date, value_date, direction, counterparty_id, transaction_type, transaction_type_other, bond_catalog_id, bond_code_manual, issuer, coupon_rate, issue_date, maturity_date, quantity, face_value, discount_rate, clean_price, settlement_price, total_value, portfolio_type, payment_date, remaining_tenor_days, confirmation_method, confirmation_other, contract_prepared_by, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type UpdateBondDealParams struct {
	UpdatedBy            uuid.UUID      `json:"updated_by"`
	ID                   uuid.UUID      `json:"id"`
	OrderDate            pgtype.Date    `json:"order_date"`
	ValueDate            pgtype.Date    `json:"value_date"`
	CounterpartyID       pgtype.UUID    `json:"counterparty_id"`
	TransactionType      *string        `json:"transaction_type"`
	TransactionTypeOther *string        `json:"transaction_type_other"`
	BondCatalogID        pgtype.UUID    `json:"bond_catalog_id"`
	BondCodeManual       *string        `json:"bond_code_manual"`
	Issuer               *string        `json:"issuer"`
	CouponRate           pgtype.Numeric `json:"coupon_rate"`
	Quantity             *int64         `json:"quantity"`
	FaceValue            pgtype.Numeric `json:"face_value"`
	DiscountRate         pgtype.Numeric `json:"discount_rate"`
	CleanPrice           pgtype.Numeric `json:"clean_price"`
	SettlementPrice      pgtype.Numeric `json:"settlement_price"`
	TotalValue           pgtype.Numeric `json:"total_value"`
	PortfolioType        *string        `json:"portfolio_type"`
	PaymentDate          pgtype.Date    `json:"payment_date"`
	RemainingTenorDays   *int32         `json:"remaining_tenor_days"`
	Note                 *string        `json:"note"`
}

// Chỉ cập nhật khi OPEN
func (q *Queries) UpdateBondDeal(ctx context.Context, arg UpdateBondDealParams) (BondDeal, error) {
	row := q.db.QueryRow(ctx, updateBondDeal,
		arg.UpdatedBy,
		arg.ID,
		arg.OrderDate,
		arg.ValueDate,
		arg.CounterpartyID,
		arg.TransactionType,
		arg.TransactionTypeOther,
		arg.BondCatalogID,
		arg.BondCodeManual,
		arg.Issuer,
		arg.CouponRate,
		arg.Quantity,
		arg.FaceValue,
		arg.DiscountRate,
		arg.CleanPrice,
		arg.SettlementPrice,
		arg.TotalValue,
		arg.PortfolioType,
		arg.PaymentDate,
		arg.RemainingTenorDays,
		arg.Note,
	)
	var i BondDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.BondCategory,
		&i.TradeDate,
		&i.BranchID,
		&i.OrderDate,
		&i.ValueDate,
		&i.Direction,
		&i.CounterpartyID,
		&i.TransactionType,
		&i.TransactionTypeOther,
		&i.BondCatalogID,
		&i.BondCodeManual,
		&i.Issuer,
		&i.CouponRate,
		&i.IssueDate,
		&i.MaturityDate,
		&i.Quantity,
		&i.FaceValue,
		&i.DiscountRate,
		&i.CleanPrice,
		&i.SettlementPrice,
		&i.TotalValue,
		&i.PortfolioType,
		&i.PaymentDate,
		&i.RemainingTenorDays,
		&i.ConfirmationMethod,
		&i.ConfirmationOther,
		&i.ContractPreparedBy,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const updateBondDealStatus = `-- name: UpdateBondDealStatus :one
UPDATE bond_deals SET
    status = $3,
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = $4
RETURNING id, deal_number, bond_category, trade_date, branch_id, order_date, value_date, direction, counterparty_id, transaction_type, transaction_type_other, bond_catalog_id, bond_code_manual, issuer, coupon_rate, issue_date, maturity_date, quantity, face_value, discount_rate, clean_price, settlement_price, total_value, portfolio_type, payment_date, remaining_tenor_days, confirmation_method, confirmation_other, contract_prepared_by, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type UpdateBondDealStatusParams struct {
	UpdatedBy uuid.UUID `json:"updated_by"`
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	Status_2  string    `json:"status_2"`
}

// Optimistic status update
func (q *Queries) UpdateBondDealStatus(ctx context.Context, arg UpdateBondDealStatusParams) (BondDeal, error) {
	row := q.db.QueryRow(ctx, updateBondDealStatus,
		arg.UpdatedBy,
		arg.ID,
		arg.Status,
		arg.Status_2,
	)
	var i BondDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.BondCategory,
		&i.TradeDate,
		&i.BranchID,
		&i.OrderDate,
		&i.ValueDate,
		&i.Direction,
		&i.CounterpartyID,
		&i.TransactionType,
		&i.TransactionTypeOther,
		&i.BondCatalogID,
		&i.BondCodeManual,
		&i.Issuer,
		&i.CouponRate,
		&i.IssueDate,
		&i.MaturityDate,
		&i.Quantity,
		&i.FaceValue,
		&i.DiscountRate,
		&i.CleanPrice,
		&i.SettlementPrice,
		&i.TotalValue,
		&i.PortfolioType,
		&i.PaymentDate,
		&i.RemainingTenorDays,
		&i.ConfirmationMethod,
		&i.ConfirmationOther,
		&i.ContractPreparedBy,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}
