// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bond_catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBondCatalog = `-- name: CreateBondCatalog :one

INSERT INTO bond_catalog (
    id, bond_code, issuer, coupon_rate, payment_frequency,
    issue_date, maturity_date, face_value, bond_type,
    is_active, created_at, created_by, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8,
    true, NOW(), $9, NOW(), $9
)
RETURNING id, bond_code, issuer, coupon_rate, payment_frequency, issue_date, maturity_date, face_value, bond_type, is_active, created_at, created_by, updated_at, updated_by
`

type CreateBondCatalogParams struct {
	BondCode         string         `json:"bond_code"`
	Issuer           string         `json:"issuer"`
	CouponRate       pgtype.Numeric `json:"coupon_rate"`
	PaymentFrequency *string        `json:"payment_frequency"`
	IssueDate        pgtype.Date    `json:"issue_date"`
	MaturityDate     pgtype.Date    `json:"maturity_date"`
	FaceValue        pgtype.Numeric `json:"face_value"`
	BondType         string         `json:"bond_type"`
	CreatedBy        pgtype.UUID    `json:"created_by"`
}

// ============================================================================
// bond_catalog.sql — Queries for bond_catalog table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateBondCatalog(ctx context.Context, arg CreateBondCatalogParams) (BondCatalog, error) {
	row := q.db.QueryRow(ctx, createBondCatalog,
		arg.BondCode,
		arg.Issuer,
		arg.CouponRate,
		arg.PaymentFrequency,
		arg.IssueDate,
		arg.MaturityDate,
		arg.FaceValue,
		arg.BondType,
		arg.CreatedBy,
	)
	var i BondCatalog
	err := row.Scan(
		&i.ID,
		&i.BondCode,
		&i.Issuer,
		&i.CouponRate,
		&i.PaymentFrequency,
		&i.IssueDate,
		&i.MaturityDate,
		&i.FaceValue,
		&i.BondType,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getBondCatalogByCode = `-- name: GetBondCatalogByCode :one
SELECT id, bond_code, issuer, coupon_rate, payment_frequency, issue_date, maturity_date, face_value, bond_type, is_active, created_at, created_by, updated_at, updated_by FROM bond_catalog WHERE bond_code = $1
`

func (q *Queries) GetBondCatalogByCode(ctx context.Context, bondCode string) (BondCatalog, error) {
	row := q.db.QueryRow(ctx, getBondCatalogByCode, bondCode)
	var i BondCatalog
	err := row.Scan(
		&i.ID,
		&i.BondCode,
		&i.Issuer,
		&i.CouponRate,
		&i.PaymentFrequency,
		&i.IssueDate,
		&i.MaturityDate,
		&i.FaceValue,
		&i.BondType,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getBondCatalogByID = `-- name: GetBondCatalogByID :one
SELECT id, bond_code, issuer, coupon_rate, payment_frequency, issue_date, maturity_date, face_value, bond_type, is_active, created_at, created_by, updated_at, updated_by FROM bond_catalog WHERE id = $1
`

func (q *Queries) GetBondCatalogByID(ctx context.Context, id uuid.UUID) (BondCatalog, error) {
	row := q.db.QueryRow(ctx, getBondCatalogByID, id)
	var i BondCatalog
	err := row.Scan(
		&i.ID,
		&i.BondCode,
		&i.Issuer,
		&i.CouponRate,
		&i.PaymentFrequency,
		&i.IssueDate,
		&i.MaturityDate,
		&i.FaceValue,
		&i.BondType,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listBondCatalog = `-- name: ListBondCatalog :many
SELECT id, bond_code, issuer, coupon_rate, payment_frequency, issue_date, maturity_date, face_value, bond_type, is_active, created_at, created_by, updated_at, updated_by FROM bond_catalog
WHERE is_active = true
ORDER BY bond_code ASC
LIMIT $1 OFFSET $2
`

type ListBondCatalogParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBondCatalog(ctx context.Context, arg ListBondCatalogParams) ([]BondCatalog, error) {
	rows, err := q.db.Query(ctx, listBondCatalog, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BondCatalog{}
	for rows.Next() {
		var i BondCatalog
		if err := rows.Scan(
			&i.ID,
			&i.BondCode,
			&i.Issuer,
			&i.CouponRate,
			&i.PaymentFrequency,
			&i.IssueDate,
			&i.MaturityDate,
			&i.FaceValue,
			&i.BondType,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBondCatalogByMaturityRange = `-- name: ListBondCatalogByMaturityRange :many
SELECT id, bond_code, issuer, coupon_rate, payment_frequency, issue_date, maturity_date, face_value, bond_type, is_active, created_at, created_by, updated_at, updated_by FROM bond_catalog
WHERE maturity_date BETWEEN $1 AND $2
  AND is_active = true
ORDER BY maturity_date ASC
LIMIT $3 OFFSET $4
`

type ListBondCatalogByMaturityRangeParams struct {
	MaturityDate   pgtype.Date `json:"maturity_date"`
	MaturityDate_2 pgtype.Date `json:"maturity_date_2"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

// Tìm trái phiếu theo khoảng ngày đáo hạn
func (q *Queries) ListBondCatalogByMaturityRange(ctx context.Context, arg ListBondCatalogByMaturityRangeParams) ([]BondCatalog, error) {
	rows, err := q.db.Query(ctx, listBondCatalogByMaturityRange,
		arg.MaturityDate,
		arg.MaturityDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BondCatalog{}
	for rows.Next() {
		var i BondCatalog
		if err := rows.Scan(
			&i.ID,
			&i.BondCode,
			&i.Issuer,
			&i.CouponRate,
			&i.PaymentFrequency,
			&i.IssueDate,
			&i.MaturityDate,
			&i.FaceValue,
			&i.BondType,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBondCatalogByType = `-- name: ListBondCatalogByType :many
SELECT id, bond_code, issuer, coupon_rate, payment_frequency, issue_date, maturity_date, face_value, bond_type, is_active, created_at, created_by, updated_at, updated_by FROM bond_catalog
WHERE bond_type = $1 AND is_active = true
ORDER BY bond_code ASC
LIMIT $2 OFFSET $3
`

type ListBondCatalogByTypeParams struct {
	BondType string `json:"bond_type"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListBondCatalogByType(ctx context.Context, arg ListBondCatalogByTypeParams) ([]BondCatalog, error) {
	rows, err := q.db.Query(ctx, listBondCatalogByType, arg.BondType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BondCatalog{}
	for rows.Next() {
		var i BondCatalog
		if err := rows.Scan(
			&i.ID,
			&i.BondCode,
			&i.Issuer,
			&i.CouponRate,
			&i.PaymentFrequency,
			&i.IssueDate,
			&i.MaturityDate,
			&i.FaceValue,
			&i.BondType,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBondCatalog = `-- name: SearchBondCatalog :many
SELECT id, bond_code, issuer, coupon_rate, payment_frequency, issue_date, maturity_date, face_value, bond_type, is_active, created_at, created_by, updated_at, updated_by FROM bond_catalog
WHERE is_active = true
  AND (bond_code ILIKE '%' || $1 || '%' OR issuer ILIKE '%' || $1 || '%')
ORDER BY bond_code ASC
LIMIT $2 OFFSET $3
`

type SearchBondCatalogParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

// Tìm kiếm theo mã hoặc tổ chức phát hành
func (q *Queries) SearchBondCatalog(ctx context.Context, arg SearchBondCatalogParams) ([]BondCatalog, error) {
	rows, err := q.db.Query(ctx, searchBondCatalog, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BondCatalog{}
	for rows.Next() {
		var i BondCatalog
		if err := rows.Scan(
			&i.ID,
			&i.BondCode,
			&i.Issuer,
			&i.CouponRate,
			&i.PaymentFrequency,
			&i.IssueDate,
			&i.MaturityDate,
			&i.FaceValue,
			&i.BondType,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBondCatalog = `-- name: UpdateBondCatalog :one
UPDATE bond_catalog SET
    issuer = COALESCE($3, issuer),
    coupon_rate = COALESCE($4, coupon_rate),
    payment_frequency = COALESCE($5, payment_frequency),
    face_value = COALESCE($6, face_value),
    is_active = COALESCE($7, is_active),
    updated_by = $1
WHERE id = $2
RETURNING id, bond_code, issuer, coupon_rate, payment_frequency, issue_date, maturity_date, face_value, bond_type, is_active, created_at, created_by, updated_at, updated_by
`

type UpdateBondCatalogParams struct {
	UpdatedBy        pgtype.UUID    `json:"updated_by"`
	ID               uuid.UUID      `json:"id"`
	Issuer           *string        `json:"issuer"`
	CouponRate       pgtype.Numeric `json:"coupon_rate"`
	PaymentFrequency *string        `json:"payment_frequency"`
	FaceValue        pgtype.Numeric `json:"face_value"`
	IsActive         *bool          `json:"is_active"`
}

func (q *Queries) UpdateBondCatalog(ctx context.Context, arg UpdateBondCatalogParams) (BondCatalog, error) {
	row := q.db.QueryRow(ctx, updateBondCatalog,
		arg.UpdatedBy,
		arg.ID,
		arg.Issuer,
		arg.CouponRate,
		arg.PaymentFrequency,
		arg.FaceValue,
		arg.IsActive,
	)
	var i BondCatalog
	err := row.Scan(
		&i.ID,
		&i.BondCode,
		&i.Issuer,
		&i.CouponRate,
		&i.PaymentFrequency,
		&i.IssueDate,
		&i.MaturityDate,
		&i.FaceValue,
		&i.BondType,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
