// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branches.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBranch = `-- name: CreateBranch :one

INSERT INTO branches (
    id, code, name, branch_type, parent_branch_id,
    flexcube_branch_code, swift_branch_code, address,
    is_active, created_at, created_by, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7,
    true, NOW(), $8, NOW(), $8
)
RETURNING id, code, name, branch_type, parent_branch_id, flexcube_branch_code, swift_branch_code, address, is_active, created_at, created_by, updated_at, updated_by
`

type CreateBranchParams struct {
	Code               string      `json:"code"`
	Name               string      `json:"name"`
	BranchType         string      `json:"branch_type"`
	ParentBranchID     pgtype.UUID `json:"parent_branch_id"`
	FlexcubeBranchCode *string     `json:"flexcube_branch_code"`
	SwiftBranchCode    *string     `json:"swift_branch_code"`
	Address            *string     `json:"address"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

// ============================================================================
// branches.sql — Queries for branches table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.Code,
		arg.Name,
		arg.BranchType,
		arg.ParentBranchID,
		arg.FlexcubeBranchCode,
		arg.SwiftBranchCode,
		arg.Address,
		arg.CreatedBy,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.BranchType,
		&i.ParentBranchID,
		&i.FlexcubeBranchCode,
		&i.SwiftBranchCode,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getBranchByCode = `-- name: GetBranchByCode :one
SELECT id, code, name, branch_type, parent_branch_id, flexcube_branch_code, swift_branch_code, address, is_active, created_at, created_by, updated_at, updated_by FROM branches WHERE code = $1
`

func (q *Queries) GetBranchByCode(ctx context.Context, code string) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByCode, code)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.BranchType,
		&i.ParentBranchID,
		&i.FlexcubeBranchCode,
		&i.SwiftBranchCode,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT id, code, name, branch_type, parent_branch_id, flexcube_branch_code, swift_branch_code, address, is_active, created_at, created_by, updated_at, updated_by FROM branches WHERE id = $1
`

func (q *Queries) GetBranchByID(ctx context.Context, id uuid.UUID) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByID, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.BranchType,
		&i.ParentBranchID,
		&i.FlexcubeBranchCode,
		&i.SwiftBranchCode,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listBranches = `-- name: ListBranches :many
SELECT id, code, name, branch_type, parent_branch_id, flexcube_branch_code, swift_branch_code, address, is_active, created_at, created_by, updated_at, updated_by FROM branches
WHERE is_active = true
ORDER BY code ASC
LIMIT $1 OFFSET $2
`

type ListBranchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBranches(ctx context.Context, arg ListBranchesParams) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.BranchType,
			&i.ParentBranchID,
			&i.FlexcubeBranchCode,
			&i.SwiftBranchCode,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchesByType = `-- name: ListBranchesByType :many
SELECT id, code, name, branch_type, parent_branch_id, flexcube_branch_code, swift_branch_code, address, is_active, created_at, created_by, updated_at, updated_by FROM branches
WHERE branch_type = $1 AND is_active = true
ORDER BY code ASC
`

func (q *Queries) ListBranchesByType(ctx context.Context, branchType string) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranchesByType, branchType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.BranchType,
			&i.ParentBranchID,
			&i.FlexcubeBranchCode,
			&i.SwiftBranchCode,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildBranches = `-- name: ListChildBranches :many
SELECT id, code, name, branch_type, parent_branch_id, flexcube_branch_code, swift_branch_code, address, is_active, created_at, created_by, updated_at, updated_by FROM branches
WHERE parent_branch_id = $1 AND is_active = true
ORDER BY code ASC
`

// Lấy danh sách chi nhánh con trực tiếp
func (q *Queries) ListChildBranches(ctx context.Context, parentBranchID pgtype.UUID) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listChildBranches, parentBranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.BranchType,
			&i.ParentBranchID,
			&i.FlexcubeBranchCode,
			&i.SwiftBranchCode,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches SET
    name = COALESCE($3, name),
    branch_type = COALESCE($4, branch_type),
    parent_branch_id = COALESCE($5, parent_branch_id),
    flexcube_branch_code = COALESCE($6, flexcube_branch_code),
    swift_branch_code = COALESCE($7, swift_branch_code),
    address = COALESCE($8, address),
    is_active = COALESCE($9, is_active),
    updated_by = $1
WHERE id = $2
RETURNING id, code, name, branch_type, parent_branch_id, flexcube_branch_code, swift_branch_code, address, is_active, created_at, created_by, updated_at, updated_by
`

type UpdateBranchParams struct {
	UpdatedBy          pgtype.UUID `json:"updated_by"`
	ID                 uuid.UUID   `json:"id"`
	Name               *string     `json:"name"`
	BranchType         *string     `json:"branch_type"`
	ParentBranchID     pgtype.UUID `json:"parent_branch_id"`
	FlexcubeBranchCode *string     `json:"flexcube_branch_code"`
	SwiftBranchCode    *string     `json:"swift_branch_code"`
	Address            *string     `json:"address"`
	IsActive           *bool       `json:"is_active"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.UpdatedBy,
		arg.ID,
		arg.Name,
		arg.BranchType,
		arg.ParentBranchID,
		arg.FlexcubeBranchCode,
		arg.SwiftBranchCode,
		arg.Address,
		arg.IsActive,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.BranchType,
		&i.ParentBranchID,
		&i.FlexcubeBranchCode,
		&i.SwiftBranchCode,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
