// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_calendar.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkInsertBusinessCalendar = `-- name: BulkInsertBusinessCalendar :exec
INSERT INTO business_calendar (id, calendar_date, country_code, is_business_day, holiday_name, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, NOW())
ON CONFLICT (calendar_date, country_code) DO UPDATE SET
    is_business_day = EXCLUDED.is_business_day,
    holiday_name = EXCLUDED.holiday_name
`

type BulkInsertBusinessCalendarParams struct {
	CalendarDate  pgtype.Date `json:"calendar_date"`
	CountryCode   string      `json:"country_code"`
	IsBusinessDay bool        `json:"is_business_day"`
	HolidayName   *string     `json:"holiday_name"`
}

// Batch insert cho preload lịch cả năm
func (q *Queries) BulkInsertBusinessCalendar(ctx context.Context, arg BulkInsertBusinessCalendarParams) error {
	_, err := q.db.Exec(ctx, bulkInsertBusinessCalendar,
		arg.CalendarDate,
		arg.CountryCode,
		arg.IsBusinessDay,
		arg.HolidayName,
	)
	return err
}

const createBusinessCalendarEntry = `-- name: CreateBusinessCalendarEntry :one

INSERT INTO business_calendar (id, calendar_date, country_code, is_business_day, holiday_name, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, NOW())
RETURNING id, calendar_date, country_code, is_business_day, holiday_name, created_at
`

type CreateBusinessCalendarEntryParams struct {
	CalendarDate  pgtype.Date `json:"calendar_date"`
	CountryCode   string      `json:"country_code"`
	IsBusinessDay bool        `json:"is_business_day"`
	HolidayName   *string     `json:"holiday_name"`
}

// ============================================================================
// business_calendar.sql — Queries for business_calendar table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateBusinessCalendarEntry(ctx context.Context, arg CreateBusinessCalendarEntryParams) (BusinessCalendar, error) {
	row := q.db.QueryRow(ctx, createBusinessCalendarEntry,
		arg.CalendarDate,
		arg.CountryCode,
		arg.IsBusinessDay,
		arg.HolidayName,
	)
	var i BusinessCalendar
	err := row.Scan(
		&i.ID,
		&i.CalendarDate,
		&i.CountryCode,
		&i.IsBusinessDay,
		&i.HolidayName,
		&i.CreatedAt,
	)
	return i, err
}

const getNextBusinessDay = `-- name: GetNextBusinessDay :one
SELECT calendar_date FROM business_calendar
WHERE calendar_date > $1
  AND country_code = COALESCE($2, 'VN')
  AND is_business_day = true
ORDER BY calendar_date ASC
LIMIT 1
`

type GetNextBusinessDayParams struct {
	CalendarDate pgtype.Date `json:"calendar_date"`
	CountryCode  *string     `json:"country_code"`
}

// Lấy ngày làm việc tiếp theo — dùng cho tính settlement date T+1, T+2
func (q *Queries) GetNextBusinessDay(ctx context.Context, arg GetNextBusinessDayParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getNextBusinessDay, arg.CalendarDate, arg.CountryCode)
	var calendar_date pgtype.Date
	err := row.Scan(&calendar_date)
	return calendar_date, err
}

const getNthBusinessDayAfter = `-- name: GetNthBusinessDayAfter :one
SELECT calendar_date FROM business_calendar
WHERE calendar_date > $1
  AND country_code = COALESCE($3, 'VN')
  AND is_business_day = true
ORDER BY calendar_date ASC
LIMIT 1 OFFSET ($2 - 1)
`

type GetNthBusinessDayAfterParams struct {
	CalendarDate pgtype.Date `json:"calendar_date"`
	Column2      interface{} `json:"column_2"`
	CountryCode  *string     `json:"country_code"`
}

// Lấy ngày làm việc thứ N sau một ngày — T+N calculation
// Ví dụ: T+2 = GetNthBusinessDayAfter(trade_date, 2)
func (q *Queries) GetNthBusinessDayAfter(ctx context.Context, arg GetNthBusinessDayAfterParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getNthBusinessDayAfter, arg.CalendarDate, arg.Column2, arg.CountryCode)
	var calendar_date pgtype.Date
	err := row.Scan(&calendar_date)
	return calendar_date, err
}

const getPreviousBusinessDay = `-- name: GetPreviousBusinessDay :one
SELECT calendar_date FROM business_calendar
WHERE calendar_date < $1
  AND country_code = COALESCE($2, 'VN')
  AND is_business_day = true
ORDER BY calendar_date DESC
LIMIT 1
`

type GetPreviousBusinessDayParams struct {
	CalendarDate pgtype.Date `json:"calendar_date"`
	CountryCode  *string     `json:"country_code"`
}

// Lấy ngày làm việc trước đó — dùng cho tra cứu tỷ giá "ngày làm việc liền trước"
func (q *Queries) GetPreviousBusinessDay(ctx context.Context, arg GetPreviousBusinessDayParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getPreviousBusinessDay, arg.CalendarDate, arg.CountryCode)
	var calendar_date pgtype.Date
	err := row.Scan(&calendar_date)
	return calendar_date, err
}

const isBusinessDay = `-- name: IsBusinessDay :one
SELECT is_business_day FROM business_calendar
WHERE calendar_date = $1 AND country_code = COALESCE($2, 'VN')
`

type IsBusinessDayParams struct {
	CalendarDate pgtype.Date `json:"calendar_date"`
	CountryCode  *string     `json:"country_code"`
}

// Kiểm tra một ngày có phải ngày làm việc không
func (q *Queries) IsBusinessDay(ctx context.Context, arg IsBusinessDayParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBusinessDay, arg.CalendarDate, arg.CountryCode)
	var is_business_day bool
	err := row.Scan(&is_business_day)
	return is_business_day, err
}

const listBusinessDaysByRange = `-- name: ListBusinessDaysByRange :many
SELECT id, calendar_date, country_code, is_business_day, holiday_name, created_at FROM business_calendar
WHERE calendar_date BETWEEN $1 AND $2
  AND country_code = COALESCE($3, 'VN')
  AND is_business_day = true
ORDER BY calendar_date ASC
`

type ListBusinessDaysByRangeParams struct {
	CalendarDate   pgtype.Date `json:"calendar_date"`
	CalendarDate_2 pgtype.Date `json:"calendar_date_2"`
	CountryCode    *string     `json:"country_code"`
}

// Liệt kê ngày làm việc trong khoảng — dùng cho tính tenor
func (q *Queries) ListBusinessDaysByRange(ctx context.Context, arg ListBusinessDaysByRangeParams) ([]BusinessCalendar, error) {
	rows, err := q.db.Query(ctx, listBusinessDaysByRange, arg.CalendarDate, arg.CalendarDate_2, arg.CountryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessCalendar{}
	for rows.Next() {
		var i BusinessCalendar
		if err := rows.Scan(
			&i.ID,
			&i.CalendarDate,
			&i.CountryCode,
			&i.IsBusinessDay,
			&i.HolidayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHolidaysByYear = `-- name: ListHolidaysByYear :many
SELECT id, calendar_date, country_code, is_business_day, holiday_name, created_at FROM business_calendar
WHERE EXTRACT(YEAR FROM calendar_date) = $1
  AND country_code = COALESCE($2, 'VN')
  AND is_business_day = false
ORDER BY calendar_date ASC
`

type ListHolidaysByYearParams struct {
	CalendarDate pgtype.Date `json:"calendar_date"`
	CountryCode  *string     `json:"country_code"`
}

// Liệt kê ngày nghỉ/lễ trong năm — dùng cho admin quản lý lịch
func (q *Queries) ListHolidaysByYear(ctx context.Context, arg ListHolidaysByYearParams) ([]BusinessCalendar, error) {
	rows, err := q.db.Query(ctx, listHolidaysByYear, arg.CalendarDate, arg.CountryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessCalendar{}
	for rows.Next() {
		var i BusinessCalendar
		if err := rows.Scan(
			&i.ID,
			&i.CalendarDate,
			&i.CountryCode,
			&i.IsBusinessDay,
			&i.HolidayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
