// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counterparties.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCounterparties = `-- name: CountCounterparties :one
SELECT COUNT(*) FROM counterparties WHERE deleted_at IS NULL
`

func (q *Queries) CountCounterparties(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCounterparties)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCounterparty = `-- name: CreateCounterparty :one

INSERT INTO counterparties (
    id, code, full_name, short_name, cif, swift_code, country_code,
    tax_id, address, fx_uses_limit, is_active,
    created_at, created_by, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, true,
    NOW(), $10, NOW(), $10
)
RETURNING id, code, full_name, short_name, cif, swift_code, country_code, tax_id, address, fx_uses_limit, is_active, created_at, created_by, updated_at, updated_by, deleted_at
`

type CreateCounterpartyParams struct {
	Code        string      `json:"code"`
	FullName    string      `json:"full_name"`
	ShortName   *string     `json:"short_name"`
	Cif         string      `json:"cif"`
	SwiftCode   *string     `json:"swift_code"`
	CountryCode *string     `json:"country_code"`
	TaxID       *string     `json:"tax_id"`
	Address     *string     `json:"address"`
	FxUsesLimit bool        `json:"fx_uses_limit"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

// ============================================================================
// counterparties.sql — Queries for counterparties table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateCounterparty(ctx context.Context, arg CreateCounterpartyParams) (Counterparty, error) {
	row := q.db.QueryRow(ctx, createCounterparty,
		arg.Code,
		arg.FullName,
		arg.ShortName,
		arg.Cif,
		arg.SwiftCode,
		arg.CountryCode,
		arg.TaxID,
		arg.Address,
		arg.FxUsesLimit,
		arg.CreatedBy,
	)
	var i Counterparty
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.FullName,
		&i.ShortName,
		&i.Cif,
		&i.SwiftCode,
		&i.CountryCode,
		&i.TaxID,
		&i.Address,
		&i.FxUsesLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getCounterpartyByCode = `-- name: GetCounterpartyByCode :one
SELECT id, code, full_name, short_name, cif, swift_code, country_code, tax_id, address, fx_uses_limit, is_active, created_at, created_by, updated_at, updated_by, deleted_at FROM counterparties
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCounterpartyByCode(ctx context.Context, code string) (Counterparty, error) {
	row := q.db.QueryRow(ctx, getCounterpartyByCode, code)
	var i Counterparty
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.FullName,
		&i.ShortName,
		&i.Cif,
		&i.SwiftCode,
		&i.CountryCode,
		&i.TaxID,
		&i.Address,
		&i.FxUsesLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getCounterpartyByID = `-- name: GetCounterpartyByID :one
SELECT id, code, full_name, short_name, cif, swift_code, country_code, tax_id, address, fx_uses_limit, is_active, created_at, created_by, updated_at, updated_by, deleted_at FROM counterparties
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCounterpartyByID(ctx context.Context, id uuid.UUID) (Counterparty, error) {
	row := q.db.QueryRow(ctx, getCounterpartyByID, id)
	var i Counterparty
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.FullName,
		&i.ShortName,
		&i.Cif,
		&i.SwiftCode,
		&i.CountryCode,
		&i.TaxID,
		&i.Address,
		&i.FxUsesLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveCounterparties = `-- name: ListActiveCounterparties :many
SELECT id, code, full_name, short_name, cif, swift_code, country_code, tax_id, address, fx_uses_limit, is_active, created_at, created_by, updated_at, updated_by, deleted_at FROM counterparties
WHERE is_active = true AND deleted_at IS NULL
ORDER BY code ASC
LIMIT $1 OFFSET $2
`

type ListActiveCounterpartiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveCounterparties(ctx context.Context, arg ListActiveCounterpartiesParams) ([]Counterparty, error) {
	rows, err := q.db.Query(ctx, listActiveCounterparties, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Counterparty{}
	for rows.Next() {
		var i Counterparty
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.FullName,
			&i.ShortName,
			&i.Cif,
			&i.SwiftCode,
			&i.CountryCode,
			&i.TaxID,
			&i.Address,
			&i.FxUsesLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounterparties = `-- name: ListCounterparties :many
SELECT id, code, full_name, short_name, cif, swift_code, country_code, tax_id, address, fx_uses_limit, is_active, created_at, created_by, updated_at, updated_by, deleted_at FROM counterparties
WHERE deleted_at IS NULL
ORDER BY code ASC
LIMIT $1 OFFSET $2
`

type ListCounterpartiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCounterparties(ctx context.Context, arg ListCounterpartiesParams) ([]Counterparty, error) {
	rows, err := q.db.Query(ctx, listCounterparties, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Counterparty{}
	for rows.Next() {
		var i Counterparty
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.FullName,
			&i.ShortName,
			&i.Cif,
			&i.SwiftCode,
			&i.CountryCode,
			&i.TaxID,
			&i.Address,
			&i.FxUsesLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounterpartiesWithLimits = `-- name: ListCounterpartiesWithLimits :many
SELECT
    c.id, c.code, c.full_name, c.short_name, c.cif, c.swift_code, c.country_code, c.tax_id, c.address, c.fx_uses_limit, c.is_active, c.created_at, c.created_by, c.updated_at, c.updated_by, c.deleted_at,
    cl_unc.limit_amount AS uncollateralized_limit,
    cl_unc.is_unlimited AS uncollateralized_unlimited,
    cl_col.limit_amount AS collateralized_limit,
    cl_col.is_unlimited AS collateralized_unlimited
FROM counterparties c
LEFT JOIN credit_limits cl_unc ON cl_unc.counterparty_id = c.id
    AND cl_unc.limit_type = 'UNCOLLATERALIZED'
    AND cl_unc.is_current = true
LEFT JOIN credit_limits cl_col ON cl_col.counterparty_id = c.id
    AND cl_col.limit_type = 'COLLATERALIZED'
    AND cl_col.is_current = true
WHERE c.deleted_at IS NULL AND c.is_active = true
ORDER BY c.code ASC
LIMIT $1 OFFSET $2
`

type ListCounterpartiesWithLimitsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCounterpartiesWithLimitsRow struct {
	ID                        uuid.UUID          `json:"id"`
	Code                      string             `json:"code"`
	FullName                  string             `json:"full_name"`
	ShortName                 *string            `json:"short_name"`
	Cif                       string             `json:"cif"`
	SwiftCode                 *string            `json:"swift_code"`
	CountryCode               *string            `json:"country_code"`
	TaxID                     *string            `json:"tax_id"`
	Address                   *string            `json:"address"`
	FxUsesLimit               bool               `json:"fx_uses_limit"`
	IsActive                  bool               `json:"is_active"`
	CreatedAt                 time.Time          `json:"created_at"`
	CreatedBy                 pgtype.UUID        `json:"created_by"`
	UpdatedAt                 time.Time          `json:"updated_at"`
	UpdatedBy                 pgtype.UUID        `json:"updated_by"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	UncollateralizedLimit     pgtype.Numeric     `json:"uncollateralized_limit"`
	UncollateralizedUnlimited *bool              `json:"uncollateralized_unlimited"`
	CollateralizedLimit       pgtype.Numeric     `json:"collateralized_limit"`
	CollateralizedUnlimited   *bool              `json:"collateralized_unlimited"`
}

// Liệt kê đối tác kèm hạn mức hiện tại — dùng cho màn hình credit limit
func (q *Queries) ListCounterpartiesWithLimits(ctx context.Context, arg ListCounterpartiesWithLimitsParams) ([]ListCounterpartiesWithLimitsRow, error) {
	rows, err := q.db.Query(ctx, listCounterpartiesWithLimits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCounterpartiesWithLimitsRow{}
	for rows.Next() {
		var i ListCounterpartiesWithLimitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.FullName,
			&i.ShortName,
			&i.Cif,
			&i.SwiftCode,
			&i.CountryCode,
			&i.TaxID,
			&i.Address,
			&i.FxUsesLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.UncollateralizedLimit,
			&i.UncollateralizedUnlimited,
			&i.CollateralizedLimit,
			&i.CollateralizedUnlimited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCounterpartiesByName = `-- name: SearchCounterpartiesByName :many
SELECT id, code, full_name, short_name, cif, swift_code, country_code, tax_id, address, fx_uses_limit, is_active, created_at, created_by, updated_at, updated_by, deleted_at FROM counterparties
WHERE deleted_at IS NULL
  AND (full_name ILIKE '%' || $1 || '%' OR short_name ILIKE '%' || $1 || '%')
ORDER BY code ASC
LIMIT $2 OFFSET $3
`

type SearchCounterpartiesByNameParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

// Tìm kiếm đối tác theo tên (ILIKE — case insensitive)
func (q *Queries) SearchCounterpartiesByName(ctx context.Context, arg SearchCounterpartiesByNameParams) ([]Counterparty, error) {
	rows, err := q.db.Query(ctx, searchCounterpartiesByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Counterparty{}
	for rows.Next() {
		var i Counterparty
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.FullName,
			&i.ShortName,
			&i.Cif,
			&i.SwiftCode,
			&i.CountryCode,
			&i.TaxID,
			&i.Address,
			&i.FxUsesLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCounterparty = `-- name: SoftDeleteCounterparty :exec
UPDATE counterparties SET deleted_at = NOW(), updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteCounterpartyParams struct {
	ID        uuid.UUID   `json:"id"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteCounterparty(ctx context.Context, arg SoftDeleteCounterpartyParams) error {
	_, err := q.db.Exec(ctx, softDeleteCounterparty, arg.ID, arg.UpdatedBy)
	return err
}

const updateCounterparty = `-- name: UpdateCounterparty :one
UPDATE counterparties SET
    full_name = COALESCE($3, full_name),
    short_name = COALESCE($4, short_name),
    cif = COALESCE($5, cif),
    swift_code = COALESCE($6, swift_code),
    country_code = COALESCE($7, country_code),
    tax_id = COALESCE($8, tax_id),
    address = COALESCE($9, address),
    fx_uses_limit = COALESCE($10, fx_uses_limit),
    is_active = COALESCE($11, is_active),
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, code, full_name, short_name, cif, swift_code, country_code, tax_id, address, fx_uses_limit, is_active, created_at, created_by, updated_at, updated_by, deleted_at
`

type UpdateCounterpartyParams struct {
	UpdatedBy   pgtype.UUID `json:"updated_by"`
	ID          uuid.UUID   `json:"id"`
	FullName    *string     `json:"full_name"`
	ShortName   *string     `json:"short_name"`
	Cif         *string     `json:"cif"`
	SwiftCode   *string     `json:"swift_code"`
	CountryCode *string     `json:"country_code"`
	TaxID       *string     `json:"tax_id"`
	Address     *string     `json:"address"`
	FxUsesLimit *bool       `json:"fx_uses_limit"`
	IsActive    *bool       `json:"is_active"`
}

func (q *Queries) UpdateCounterparty(ctx context.Context, arg UpdateCounterpartyParams) (Counterparty, error) {
	row := q.db.QueryRow(ctx, updateCounterparty,
		arg.UpdatedBy,
		arg.ID,
		arg.FullName,
		arg.ShortName,
		arg.Cif,
		arg.SwiftCode,
		arg.CountryCode,
		arg.TaxID,
		arg.Address,
		arg.FxUsesLimit,
		arg.IsActive,
	)
	var i Counterparty
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.FullName,
		&i.ShortName,
		&i.Cif,
		&i.SwiftCode,
		&i.CountryCode,
		&i.TaxID,
		&i.Address,
		&i.FxUsesLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}
