// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit_limits.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const calculateUtilization = `-- name: CalculateUtilization :one
WITH uncollateralized_deals AS (
    -- MM Interbank (LEND/PLACE không có TSBĐ)
    SELECT
        mm.counterparty_id,
        CASE
            WHEN mm.currency_code = 'VND' THEN mm.principal_amount
            ELSE mm.principal_amount * $2::NUMERIC
        END AS utilized_amount
    FROM mm_interbank_deals mm
    WHERE mm.counterparty_id = $1
      AND mm.has_collateral = false
      AND mm.direction IN ('LEND', 'PLACE')
      AND mm.status IN ('COMPLETED', 'PENDING_SETTLEMENT')
      AND mm.maturity_date > NOW()::DATE
      AND mm.deleted_at IS NULL

    UNION ALL

    -- FX Deals (nếu có consume limit)
    SELECT
        fx.counterparty_id,
        CASE
            WHEN fx.currency_code = 'VND' THEN fx.notional_amount
            ELSE fx.notional_amount * $2::NUMERIC
        END AS utilized_amount
    FROM fx_deals fx
    WHERE fx.counterparty_id = $1
      AND fx.uses_credit_limit = true
      AND fx.status IN ('COMPLETED', 'PENDING_SETTLEMENT')
      AND fx.deleted_at IS NULL
    -- NOTE: Cần logic nghiệp vụ để xác định leg nào của deal FX sẽ được tính vào utilization

    UNION ALL

    -- Bond Deals (FI/CD - bán Repo)
    SELECT
        bd.counterparty_id,
        bd.total_value AS utilized_amount
    FROM bond_deals bd
    WHERE bd.counterparty_id = $1
      AND bd.direction = 'SELL'
      AND bd.transaction_type = 'REPO'
      AND bd.bond_category IN ('FINANCIAL_INSTITUTION', 'CERTIFICATE_OF_DEPOSIT')
      AND bd.status IN ('COMPLETED')
      AND bd.payment_date > NOW()::DATE
      AND bd.deleted_at IS NULL
)
SELECT
    COALESCE(SUM(utilized_amount), 0)::NUMERIC(20, 2) AS total_utilization
FROM uncollateralized_deals
`

type CalculateUtilizationParams struct {
	CounterpartyID uuid.UUID      `json:"counterparty_id"`
	UsdMidRate     pgtype.Numeric `json:"usd_mid_rate"`
}

// Tính toán utilization tổng hợp (MM + FX + Bond) cho uncollateralized limit
// Query phức tạp này join các deals đã được duyệt nhưng chưa đáo hạn/settle
func (q *Queries) CalculateUtilization(ctx context.Context, arg CalculateUtilizationParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, calculateUtilization, arg.CounterpartyID, arg.UsdMidRate)
	var total_utilization pgtype.Numeric
	err := row.Scan(&total_utilization)
	return total_utilization, err
}

const createCreditLimit = `-- name: CreateCreditLimit :one

INSERT INTO credit_limits (
    id, counterparty_id, limit_type, limit_amount, is_unlimited,
    effective_from, effective_to, is_current, expiry_date,
    approval_reference, created_at, created_by, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, NULL, true, $6, $7,
    NOW(), $8, NOW(), $8
)
RETURNING id, counterparty_id, limit_type, limit_amount, is_unlimited, effective_from, effective_to, is_current, expiry_date, approval_reference, created_at, created_by, updated_at, updated_by
`

type CreateCreditLimitParams struct {
	CounterpartyID    uuid.UUID      `json:"counterparty_id"`
	LimitType         string         `json:"limit_type"`
	LimitAmount       pgtype.Numeric `json:"limit_amount"`
	IsUnlimited       bool           `json:"is_unlimited"`
	EffectiveFrom     pgtype.Date    `json:"effective_from"`
	ExpiryDate        pgtype.Date    `json:"expiry_date"`
	ApprovalReference *string        `json:"approval_reference"`
	CreatedBy         pgtype.UUID    `json:"created_by"`
}

// ============================================================================
// credit_limits.sql — Queries for credit_limits table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateCreditLimit(ctx context.Context, arg CreateCreditLimitParams) (CreditLimit, error) {
	row := q.db.QueryRow(ctx, createCreditLimit,
		arg.CounterpartyID,
		arg.LimitType,
		arg.LimitAmount,
		arg.IsUnlimited,
		arg.EffectiveFrom,
		arg.ExpiryDate,
		arg.ApprovalReference,
		arg.CreatedBy,
	)
	var i CreditLimit
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.LimitType,
		&i.LimitAmount,
		&i.IsUnlimited,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsCurrent,
		&i.ExpiryDate,
		&i.ApprovalReference,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deactivateCurrentLimit = `-- name: DeactivateCurrentLimit :one
UPDATE credit_limits SET
    effective_to = $3,
    is_current = false,
    updated_by = $1
WHERE id = $2
RETURNING id, counterparty_id, limit_type, limit_amount, is_unlimited, effective_from, effective_to, is_current, expiry_date, approval_reference, created_at, created_by, updated_at, updated_by
`

type DeactivateCurrentLimitParams struct {
	UpdatedBy   pgtype.UUID `json:"updated_by"`
	ID          uuid.UUID   `json:"id"`
	EffectiveTo pgtype.Date `json:"effective_to"`
}

// SCD Type 2: đóng bản ghi hiện tại lại khi có update
func (q *Queries) DeactivateCurrentLimit(ctx context.Context, arg DeactivateCurrentLimitParams) (CreditLimit, error) {
	row := q.db.QueryRow(ctx, deactivateCurrentLimit, arg.UpdatedBy, arg.ID, arg.EffectiveTo)
	var i CreditLimit
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.LimitType,
		&i.LimitAmount,
		&i.IsUnlimited,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsCurrent,
		&i.ExpiryDate,
		&i.ApprovalReference,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCreditLimitByID = `-- name: GetCreditLimitByID :one
SELECT id, counterparty_id, limit_type, limit_amount, is_unlimited, effective_from, effective_to, is_current, expiry_date, approval_reference, created_at, created_by, updated_at, updated_by FROM credit_limits WHERE id = $1
`

func (q *Queries) GetCreditLimitByID(ctx context.Context, id uuid.UUID) (CreditLimit, error) {
	row := q.db.QueryRow(ctx, getCreditLimitByID, id)
	var i CreditLimit
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.LimitType,
		&i.LimitAmount,
		&i.IsUnlimited,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsCurrent,
		&i.ExpiryDate,
		&i.ApprovalReference,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCurrentLimit = `-- name: GetCurrentLimit :one
SELECT id, counterparty_id, limit_type, limit_amount, is_unlimited, effective_from, effective_to, is_current, expiry_date, approval_reference, created_at, created_by, updated_at, updated_by FROM credit_limits
WHERE counterparty_id = $1
  AND limit_type = $2
  AND is_current = true
`

type GetCurrentLimitParams struct {
	CounterpartyID uuid.UUID `json:"counterparty_id"`
	LimitType      string    `json:"limit_type"`
}

// Lấy hạn mức hiện tại cho đối tác + loại
func (q *Queries) GetCurrentLimit(ctx context.Context, arg GetCurrentLimitParams) (CreditLimit, error) {
	row := q.db.QueryRow(ctx, getCurrentLimit, arg.CounterpartyID, arg.LimitType)
	var i CreditLimit
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.LimitType,
		&i.LimitAmount,
		&i.IsUnlimited,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsCurrent,
		&i.ExpiryDate,
		&i.ApprovalReference,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getDailyLimitSummary = `-- name: GetDailyLimitSummary :many
SELECT
    c.code AS counterparty_code,
    c.full_name AS counterparty_name,
    cl.limit_amount AS granted_limit,
    COALESCE(ls.utilized_opening, 0) AS opening_utilization,
    COALESCE(ls.utilized_intraday, 0) AS intraday_utilization,
    COALESCE(ls.utilized_total, 0) AS total_utilization,
    COALESCE(ls.remaining, cl.limit_amount) AS remaining_limit,
    cl.expiry_date
FROM counterparties c
JOIN credit_limits cl ON c.id = cl.counterparty_id
LEFT JOIN limit_utilization_snapshots ls ON c.id = ls.counterparty_id
    AND ls.snapshot_date = $3::DATE
WHERE c.deleted_at IS NULL
  AND c.is_active = true
  AND cl.is_current = true
  AND cl.limit_type = 'UNCOLLATERALIZED'
ORDER BY c.code
LIMIT $1 OFFSET $2
`

type GetDailyLimitSummaryParams struct {
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	SnapshotDate pgtype.Date `json:"snapshot_date"`
}

type GetDailyLimitSummaryRow struct {
	CounterpartyCode    string         `json:"counterparty_code"`
	CounterpartyName    string         `json:"counterparty_name"`
	GrantedLimit        pgtype.Numeric `json:"granted_limit"`
	OpeningUtilization  pgtype.Numeric `json:"opening_utilization"`
	IntradayUtilization pgtype.Numeric `json:"intraday_utilization"`
	TotalUtilization    pgtype.Numeric `json:"total_utilization"`
	RemainingLimit      pgtype.Numeric `json:"remaining_limit"`
	ExpiryDate          pgtype.Date    `json:"expiry_date"`
}

// Lấy summary 11 cột theo BRD
// Query này rất phức tạp và cần snapshot để có performance tốt
// Dưới đây là query mẫu, trong thực tế sẽ chạy trên bảng snapshot
func (q *Queries) GetDailyLimitSummary(ctx context.Context, arg GetDailyLimitSummaryParams) ([]GetDailyLimitSummaryRow, error) {
	rows, err := q.db.Query(ctx, getDailyLimitSummary, arg.Limit, arg.Offset, arg.SnapshotDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyLimitSummaryRow{}
	for rows.Next() {
		var i GetDailyLimitSummaryRow
		if err := rows.Scan(
			&i.CounterpartyCode,
			&i.CounterpartyName,
			&i.GrantedLimit,
			&i.OpeningUtilization,
			&i.IntradayUtilization,
			&i.TotalUtilization,
			&i.RemainingLimit,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLimitHistory = `-- name: GetLimitHistory :many
SELECT id, counterparty_id, limit_type, limit_amount, is_unlimited, effective_from, effective_to, is_current, expiry_date, approval_reference, created_at, created_by, updated_at, updated_by FROM credit_limits
WHERE counterparty_id = $1
  AND limit_type = $2
ORDER BY effective_from DESC
`

type GetLimitHistoryParams struct {
	CounterpartyID uuid.UUID `json:"counterparty_id"`
	LimitType      string    `json:"limit_type"`
}

// Lấy lịch sử thay đổi hạn mức của đối tác
func (q *Queries) GetLimitHistory(ctx context.Context, arg GetLimitHistoryParams) ([]CreditLimit, error) {
	rows, err := q.db.Query(ctx, getLimitHistory, arg.CounterpartyID, arg.LimitType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreditLimit{}
	for rows.Next() {
		var i CreditLimit
		if err := rows.Scan(
			&i.ID,
			&i.CounterpartyID,
			&i.LimitType,
			&i.LimitAmount,
			&i.IsUnlimited,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.IsCurrent,
			&i.ExpiryDate,
			&i.ApprovalReference,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentLimits = `-- name: ListCurrentLimits :many
SELECT id, counterparty_id, limit_type, limit_amount, is_unlimited, effective_from, effective_to, is_current, expiry_date, approval_reference, created_at, created_by, updated_at, updated_by FROM credit_limits
WHERE is_current = true
ORDER BY counterparty_id, limit_type
LIMIT $1 OFFSET $2
`

type ListCurrentLimitsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Liệt kê tất cả hạn mức hiện tại
func (q *Queries) ListCurrentLimits(ctx context.Context, arg ListCurrentLimitsParams) ([]CreditLimit, error) {
	rows, err := q.db.Query(ctx, listCurrentLimits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreditLimit{}
	for rows.Next() {
		var i CreditLimit
		if err := rows.Scan(
			&i.ID,
			&i.CounterpartyID,
			&i.LimitType,
			&i.LimitAmount,
			&i.IsUnlimited,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.IsCurrent,
			&i.ExpiryDate,
			&i.ApprovalReference,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
