// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currency_pairs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCurrencyPair = `-- name: CreateCurrencyPair :one

INSERT INTO currency_pairs (
    id, base_currency, quote_currency, pair_code,
    rate_decimal_places, calculation_rule, result_currency, is_active
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, true
)
RETURNING id, base_currency, quote_currency, pair_code, rate_decimal_places, calculation_rule, result_currency, is_active
`

type CreateCurrencyPairParams struct {
	BaseCurrency      string `json:"base_currency"`
	QuoteCurrency     string `json:"quote_currency"`
	PairCode          string `json:"pair_code"`
	RateDecimalPlaces int16  `json:"rate_decimal_places"`
	CalculationRule   string `json:"calculation_rule"`
	ResultCurrency    string `json:"result_currency"`
}

// ============================================================================
// currency_pairs.sql — Queries for currency_pairs table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateCurrencyPair(ctx context.Context, arg CreateCurrencyPairParams) (CurrencyPair, error) {
	row := q.db.QueryRow(ctx, createCurrencyPair,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.PairCode,
		arg.RateDecimalPlaces,
		arg.CalculationRule,
		arg.ResultCurrency,
	)
	var i CurrencyPair
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.PairCode,
		&i.RateDecimalPlaces,
		&i.CalculationRule,
		&i.ResultCurrency,
		&i.IsActive,
	)
	return i, err
}

const getCurrencyPairByCode = `-- name: GetCurrencyPairByCode :one
SELECT id, base_currency, quote_currency, pair_code, rate_decimal_places, calculation_rule, result_currency, is_active FROM currency_pairs WHERE pair_code = $1
`

func (q *Queries) GetCurrencyPairByCode(ctx context.Context, pairCode string) (CurrencyPair, error) {
	row := q.db.QueryRow(ctx, getCurrencyPairByCode, pairCode)
	var i CurrencyPair
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.PairCode,
		&i.RateDecimalPlaces,
		&i.CalculationRule,
		&i.ResultCurrency,
		&i.IsActive,
	)
	return i, err
}

const getCurrencyPairByCurrencies = `-- name: GetCurrencyPairByCurrencies :one
SELECT id, base_currency, quote_currency, pair_code, rate_decimal_places, calculation_rule, result_currency, is_active FROM currency_pairs
WHERE base_currency = $1 AND quote_currency = $2 AND is_active = true
`

type GetCurrencyPairByCurrenciesParams struct {
	BaseCurrency  string `json:"base_currency"`
	QuoteCurrency string `json:"quote_currency"`
}

// Tìm cặp tiền tệ theo base + quote currency
func (q *Queries) GetCurrencyPairByCurrencies(ctx context.Context, arg GetCurrencyPairByCurrenciesParams) (CurrencyPair, error) {
	row := q.db.QueryRow(ctx, getCurrencyPairByCurrencies, arg.BaseCurrency, arg.QuoteCurrency)
	var i CurrencyPair
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.PairCode,
		&i.RateDecimalPlaces,
		&i.CalculationRule,
		&i.ResultCurrency,
		&i.IsActive,
	)
	return i, err
}

const getCurrencyPairByID = `-- name: GetCurrencyPairByID :one
SELECT id, base_currency, quote_currency, pair_code, rate_decimal_places, calculation_rule, result_currency, is_active FROM currency_pairs WHERE id = $1
`

func (q *Queries) GetCurrencyPairByID(ctx context.Context, id uuid.UUID) (CurrencyPair, error) {
	row := q.db.QueryRow(ctx, getCurrencyPairByID, id)
	var i CurrencyPair
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.PairCode,
		&i.RateDecimalPlaces,
		&i.CalculationRule,
		&i.ResultCurrency,
		&i.IsActive,
	)
	return i, err
}

const listActiveCurrencyPairs = `-- name: ListActiveCurrencyPairs :many
SELECT id, base_currency, quote_currency, pair_code, rate_decimal_places, calculation_rule, result_currency, is_active FROM currency_pairs
WHERE is_active = true
ORDER BY pair_code ASC
`

func (q *Queries) ListActiveCurrencyPairs(ctx context.Context) ([]CurrencyPair, error) {
	rows, err := q.db.Query(ctx, listActiveCurrencyPairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrencyPair{}
	for rows.Next() {
		var i CurrencyPair
		if err := rows.Scan(
			&i.ID,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.PairCode,
			&i.RateDecimalPlaces,
			&i.CalculationRule,
			&i.ResultCurrency,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrencyPairs = `-- name: ListCurrencyPairs :many
SELECT id, base_currency, quote_currency, pair_code, rate_decimal_places, calculation_rule, result_currency, is_active FROM currency_pairs
ORDER BY pair_code ASC
`

func (q *Queries) ListCurrencyPairs(ctx context.Context) ([]CurrencyPair, error) {
	rows, err := q.db.Query(ctx, listCurrencyPairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrencyPair{}
	for rows.Next() {
		var i CurrencyPair
		if err := rows.Scan(
			&i.ID,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.PairCode,
			&i.RateDecimalPlaces,
			&i.CalculationRule,
			&i.ResultCurrency,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurrencyPair = `-- name: UpdateCurrencyPair :one
UPDATE currency_pairs SET
    rate_decimal_places = COALESCE($2, rate_decimal_places),
    calculation_rule = COALESCE($3, calculation_rule),
    result_currency = COALESCE($4, result_currency),
    is_active = COALESCE($5, is_active)
WHERE id = $1
RETURNING id, base_currency, quote_currency, pair_code, rate_decimal_places, calculation_rule, result_currency, is_active
`

type UpdateCurrencyPairParams struct {
	ID                uuid.UUID `json:"id"`
	RateDecimalPlaces *int16    `json:"rate_decimal_places"`
	CalculationRule   *string   `json:"calculation_rule"`
	ResultCurrency    *string   `json:"result_currency"`
	IsActive          *bool     `json:"is_active"`
}

func (q *Queries) UpdateCurrencyPair(ctx context.Context, arg UpdateCurrencyPairParams) (CurrencyPair, error) {
	row := q.db.QueryRow(ctx, updateCurrencyPair,
		arg.ID,
		arg.RateDecimalPlaces,
		arg.CalculationRule,
		arg.ResultCurrency,
		arg.IsActive,
	)
	var i CurrencyPair
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.PairCode,
		&i.RateDecimalPlaces,
		&i.CalculationRule,
		&i.ResultCurrency,
		&i.IsActive,
	)
	return i, err
}
