// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currencies.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCurrency = `-- name: CreateCurrency :one

INSERT INTO currencies (id, code, numeric_code, name, decimal_places, is_active)
VALUES (gen_random_uuid(), $1, $2, $3, $4, true)
RETURNING id, code, numeric_code, name, decimal_places, is_active
`

type CreateCurrencyParams struct {
	Code          string `json:"code"`
	NumericCode   *int16 `json:"numeric_code"`
	Name          string `json:"name"`
	DecimalPlaces int16  `json:"decimal_places"`
}

// ============================================================================
// currencies.sql — Queries for currencies table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error) {
	row := q.db.QueryRow(ctx, createCurrency,
		arg.Code,
		arg.NumericCode,
		arg.Name,
		arg.DecimalPlaces,
	)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NumericCode,
		&i.Name,
		&i.DecimalPlaces,
		&i.IsActive,
	)
	return i, err
}

const getCurrencyByCode = `-- name: GetCurrencyByCode :one
SELECT id, code, numeric_code, name, decimal_places, is_active FROM currencies WHERE code = $1
`

func (q *Queries) GetCurrencyByCode(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrencyByCode, code)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NumericCode,
		&i.Name,
		&i.DecimalPlaces,
		&i.IsActive,
	)
	return i, err
}

const getCurrencyByID = `-- name: GetCurrencyByID :one
SELECT id, code, numeric_code, name, decimal_places, is_active FROM currencies WHERE id = $1
`

func (q *Queries) GetCurrencyByID(ctx context.Context, id uuid.UUID) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrencyByID, id)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NumericCode,
		&i.Name,
		&i.DecimalPlaces,
		&i.IsActive,
	)
	return i, err
}

const listActiveCurrencies = `-- name: ListActiveCurrencies :many
SELECT id, code, numeric_code, name, decimal_places, is_active FROM currencies
WHERE is_active = true
ORDER BY code ASC
`

func (q *Queries) ListActiveCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listActiveCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.NumericCode,
			&i.Name,
			&i.DecimalPlaces,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT id, code, numeric_code, name, decimal_places, is_active FROM currencies
ORDER BY code ASC
`

func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.NumericCode,
			&i.Name,
			&i.DecimalPlaces,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurrency = `-- name: UpdateCurrency :one
UPDATE currencies SET
    name = COALESCE($2, name),
    numeric_code = COALESCE($3, numeric_code),
    decimal_places = COALESCE($4, decimal_places),
    is_active = COALESCE($5, is_active)
WHERE id = $1
RETURNING id, code, numeric_code, name, decimal_places, is_active
`

type UpdateCurrencyParams struct {
	ID            uuid.UUID `json:"id"`
	Name          *string   `json:"name"`
	NumericCode   *int16    `json:"numeric_code"`
	DecimalPlaces *int16    `json:"decimal_places"`
	IsActive      *bool     `json:"is_active"`
}

func (q *Queries) UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error) {
	row := q.db.QueryRow(ctx, updateCurrency,
		arg.ID,
		arg.Name,
		arg.NumericCode,
		arg.DecimalPlaces,
		arg.IsActive,
	)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NumericCode,
		&i.Name,
		&i.DecimalPlaces,
		&i.IsActive,
	)
	return i, err
}
