// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deal_sequences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentSequence = `-- name: GetCurrentSequence :one
SELECT id, module, prefix, date_partition, last_sequence, updated_at FROM deal_sequences
WHERE module = $1
  AND prefix = $2
  AND date_partition = $3
`

type GetCurrentSequenceParams struct {
	Module        string      `json:"module"`
	Prefix        string      `json:"prefix"`
	DatePartition pgtype.Date `json:"date_partition"`
}

// Xem sequence hiện tại mà không tăng — dùng cho báo cáo/monitoring
func (q *Queries) GetCurrentSequence(ctx context.Context, arg GetCurrentSequenceParams) (DealSequence, error) {
	row := q.db.QueryRow(ctx, getCurrentSequence, arg.Module, arg.Prefix, arg.DatePartition)
	var i DealSequence
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Prefix,
		&i.DatePartition,
		&i.LastSequence,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextSequence = `-- name: GetNextSequence :one

INSERT INTO deal_sequences (id, module, prefix, date_partition, last_sequence, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, 1, NOW())
ON CONFLICT (module, prefix, date_partition)
DO UPDATE SET
    last_sequence = deal_sequences.last_sequence + 1,
    updated_at = NOW()
RETURNING id, module, prefix, date_partition, last_sequence, updated_at
`

type GetNextSequenceParams struct {
	Module        string      `json:"module"`
	Prefix        string      `json:"prefix"`
	DatePartition pgtype.Date `json:"date_partition"`
}

// ============================================================================
// deal_sequences.sql — Queries for deal_sequences table
// Treasury Management System — KienlongBank
// ============================================================================
// Lấy và tăng sequence number — PHẢI chạy trong transaction
// Pattern: SELECT FOR UPDATE → UPDATE → return new value
// Tạo row mới nếu chưa tồn tại (first deal of the day)
func (q *Queries) GetNextSequence(ctx context.Context, arg GetNextSequenceParams) (DealSequence, error) {
	row := q.db.QueryRow(ctx, getNextSequence, arg.Module, arg.Prefix, arg.DatePartition)
	var i DealSequence
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Prefix,
		&i.DatePartition,
		&i.LastSequence,
		&i.UpdatedAt,
	)
	return i, err
}

const listSequencesByDate = `-- name: ListSequencesByDate :many
SELECT id, module, prefix, date_partition, last_sequence, updated_at FROM deal_sequences
WHERE date_partition = $1
ORDER BY module ASC, prefix ASC
`

// Liệt kê tất cả sequence trong ngày — monitoring dashboard
func (q *Queries) ListSequencesByDate(ctx context.Context, datePartition pgtype.Date) ([]DealSequence, error) {
	rows, err := q.db.Query(ctx, listSequencesByDate, datePartition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DealSequence{}
	for rows.Next() {
		var i DealSequence
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Prefix,
			&i.DatePartition,
			&i.LastSequence,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSequencesByModule = `-- name: ListSequencesByModule :many
SELECT id, module, prefix, date_partition, last_sequence, updated_at FROM deal_sequences
WHERE module = $1
ORDER BY date_partition DESC
LIMIT $2 OFFSET $3
`

type ListSequencesByModuleParams struct {
	Module string `json:"module"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

// Lịch sử sequence theo module — dùng cho báo cáo
func (q *Queries) ListSequencesByModule(ctx context.Context, arg ListSequencesByModuleParams) ([]DealSequence, error) {
	rows, err := q.db.Query(ctx, listSequencesByModule, arg.Module, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DealSequence{}
	for rows.Next() {
		var i DealSequence
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Prefix,
			&i.DatePartition,
			&i.LastSequence,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
