// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (
    id, deal_module, deal_id, document_type,
    file_name, storage_bucket, storage_key,
    file_size, mime_type, checksum_sha256,
    scan_status, version, is_current,
    uploaded_by, uploaded_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9,
    'PENDING', $10, true, $11, NOW()
)
RETURNING id, deal_module, deal_id, document_type, file_name, storage_bucket, storage_key, file_size, mime_type, checksum_sha256, scan_status, scanned_at, version, is_current, uploaded_by, uploaded_at, deleted_at
`

type CreateDocumentParams struct {
	DealModule     string    `json:"deal_module"`
	DealID         uuid.UUID `json:"deal_id"`
	DocumentType   string    `json:"document_type"`
	FileName       string    `json:"file_name"`
	StorageBucket  string    `json:"storage_bucket"`
	StorageKey     string    `json:"storage_key"`
	FileSize       int64     `json:"file_size"`
	MimeType       string    `json:"mime_type"`
	ChecksumSha256 string    `json:"checksum_sha256"`
	Version        int32     `json:"version"`
	UploadedBy     uuid.UUID `json:"uploaded_by"`
}

// ============================================================================
// documents.sql — Queries for documents table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.DealModule,
		arg.DealID,
		arg.DocumentType,
		arg.FileName,
		arg.StorageBucket,
		arg.StorageKey,
		arg.FileSize,
		arg.MimeType,
		arg.ChecksumSha256,
		arg.Version,
		arg.UploadedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.DealID,
		&i.DocumentType,
		&i.FileName,
		&i.StorageBucket,
		&i.StorageKey,
		&i.FileSize,
		&i.MimeType,
		&i.ChecksumSha256,
		&i.ScanStatus,
		&i.ScannedAt,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, deal_module, deal_id, document_type, file_name, storage_bucket, storage_key, file_size, mime_type, checksum_sha256, scan_status, scanned_at, version, is_current, uploaded_by, uploaded_at, deleted_at FROM documents
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.DealID,
		&i.DocumentType,
		&i.FileName,
		&i.StorageBucket,
		&i.StorageKey,
		&i.FileSize,
		&i.MimeType,
		&i.ChecksumSha256,
		&i.ScanStatus,
		&i.ScannedAt,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentByStorageKey = `-- name: GetDocumentByStorageKey :one
SELECT id, deal_module, deal_id, document_type, file_name, storage_bucket, storage_key, file_size, mime_type, checksum_sha256, scan_status, scanned_at, version, is_current, uploaded_by, uploaded_at, deleted_at FROM documents
WHERE storage_key = $1 AND deleted_at IS NULL
`

// Tìm document theo storage key — dùng khi cần verify
func (q *Queries) GetDocumentByStorageKey(ctx context.Context, storageKey string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByStorageKey, storageKey)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.DealID,
		&i.DocumentType,
		&i.FileName,
		&i.StorageBucket,
		&i.StorageKey,
		&i.FileSize,
		&i.MimeType,
		&i.ChecksumSha256,
		&i.ScanStatus,
		&i.ScannedAt,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestDocumentVersion = `-- name: GetLatestDocumentVersion :one
SELECT id, deal_module, deal_id, document_type, file_name, storage_bucket, storage_key, file_size, mime_type, checksum_sha256, scan_status, scanned_at, version, is_current, uploaded_by, uploaded_at, deleted_at FROM documents
WHERE deal_module = $1
  AND deal_id = $2
  AND file_name = $3
  AND is_current = true
  AND deleted_at IS NULL
`

type GetLatestDocumentVersionParams struct {
	DealModule string    `json:"deal_module"`
	DealID     uuid.UUID `json:"deal_id"`
	FileName   string    `json:"file_name"`
}

// Lấy phiên bản mới nhất của tài liệu theo tên file
func (q *Queries) GetLatestDocumentVersion(ctx context.Context, arg GetLatestDocumentVersionParams) (Document, error) {
	row := q.db.QueryRow(ctx, getLatestDocumentVersion, arg.DealModule, arg.DealID, arg.FileName)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.DealID,
		&i.DocumentType,
		&i.FileName,
		&i.StorageBucket,
		&i.StorageKey,
		&i.FileSize,
		&i.MimeType,
		&i.ChecksumSha256,
		&i.ScanStatus,
		&i.ScannedAt,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT
    d.id, d.deal_module, d.deal_id, d.document_type, d.file_name, d.storage_bucket, d.storage_key, d.file_size, d.mime_type, d.checksum_sha256, d.scan_status, d.scanned_at, d.version, d.is_current, d.uploaded_by, d.uploaded_at, d.deleted_at,
    u.full_name AS uploader_name
FROM documents d
JOIN users u ON u.id = d.uploaded_by
WHERE d.deal_module = $1
  AND d.deal_id = $2
  AND d.file_name = $3
  AND d.deleted_at IS NULL
ORDER BY d.version DESC
`

type ListDocumentVersionsParams struct {
	DealModule string    `json:"deal_module"`
	DealID     uuid.UUID `json:"deal_id"`
	FileName   string    `json:"file_name"`
}

type ListDocumentVersionsRow struct {
	ID             uuid.UUID          `json:"id"`
	DealModule     string             `json:"deal_module"`
	DealID         uuid.UUID          `json:"deal_id"`
	DocumentType   string             `json:"document_type"`
	FileName       string             `json:"file_name"`
	StorageBucket  string             `json:"storage_bucket"`
	StorageKey     string             `json:"storage_key"`
	FileSize       int64              `json:"file_size"`
	MimeType       string             `json:"mime_type"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	ScanStatus     string             `json:"scan_status"`
	ScannedAt      pgtype.Timestamptz `json:"scanned_at"`
	Version        int32              `json:"version"`
	IsCurrent      bool               `json:"is_current"`
	UploadedBy     uuid.UUID          `json:"uploaded_by"`
	UploadedAt     time.Time          `json:"uploaded_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	UploaderName   string             `json:"uploader_name"`
}

// Lấy tất cả version của một file — version history
func (q *Queries) ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]ListDocumentVersionsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, arg.DealModule, arg.DealID, arg.FileName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentVersionsRow{}
	for rows.Next() {
		var i ListDocumentVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DealModule,
			&i.DealID,
			&i.DocumentType,
			&i.FileName,
			&i.StorageBucket,
			&i.StorageKey,
			&i.FileSize,
			&i.MimeType,
			&i.ChecksumSha256,
			&i.ScanStatus,
			&i.ScannedAt,
			&i.Version,
			&i.IsCurrent,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.DeletedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByDeal = `-- name: ListDocumentsByDeal :many
SELECT
    d.id, d.deal_module, d.deal_id, d.document_type, d.file_name, d.storage_bucket, d.storage_key, d.file_size, d.mime_type, d.checksum_sha256, d.scan_status, d.scanned_at, d.version, d.is_current, d.uploaded_by, d.uploaded_at, d.deleted_at,
    u.full_name AS uploader_name
FROM documents d
JOIN users u ON u.id = d.uploaded_by
WHERE d.deal_module = $1
  AND d.deal_id = $2
  AND d.is_current = true
  AND d.deleted_at IS NULL
ORDER BY d.document_type ASC, d.uploaded_at DESC
`

type ListDocumentsByDealParams struct {
	DealModule string    `json:"deal_module"`
	DealID     uuid.UUID `json:"deal_id"`
}

type ListDocumentsByDealRow struct {
	ID             uuid.UUID          `json:"id"`
	DealModule     string             `json:"deal_module"`
	DealID         uuid.UUID          `json:"deal_id"`
	DocumentType   string             `json:"document_type"`
	FileName       string             `json:"file_name"`
	StorageBucket  string             `json:"storage_bucket"`
	StorageKey     string             `json:"storage_key"`
	FileSize       int64              `json:"file_size"`
	MimeType       string             `json:"mime_type"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	ScanStatus     string             `json:"scan_status"`
	ScannedAt      pgtype.Timestamptz `json:"scanned_at"`
	Version        int32              `json:"version"`
	IsCurrent      bool               `json:"is_current"`
	UploadedBy     uuid.UUID          `json:"uploaded_by"`
	UploadedAt     time.Time          `json:"uploaded_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	UploaderName   string             `json:"uploader_name"`
}

// Lấy tất cả tài liệu của deal — chỉ version hiện tại
func (q *Queries) ListDocumentsByDeal(ctx context.Context, arg ListDocumentsByDealParams) ([]ListDocumentsByDealRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByDeal, arg.DealModule, arg.DealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsByDealRow{}
	for rows.Next() {
		var i ListDocumentsByDealRow
		if err := rows.Scan(
			&i.ID,
			&i.DealModule,
			&i.DealID,
			&i.DocumentType,
			&i.FileName,
			&i.StorageBucket,
			&i.StorageKey,
			&i.FileSize,
			&i.MimeType,
			&i.ChecksumSha256,
			&i.ScanStatus,
			&i.ScannedAt,
			&i.Version,
			&i.IsCurrent,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.DeletedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingScanDocuments = `-- name: ListPendingScanDocuments :many
SELECT id, deal_module, deal_id, document_type, file_name, storage_bucket, storage_key, file_size, mime_type, checksum_sha256, scan_status, scanned_at, version, is_current, uploaded_by, uploaded_at, deleted_at FROM documents
WHERE scan_status = 'PENDING'
  AND deleted_at IS NULL
ORDER BY uploaded_at ASC
LIMIT $1
`

// Lấy tài liệu chờ quét virus — antivirus worker
func (q *Queries) ListPendingScanDocuments(ctx context.Context, limit int32) ([]Document, error) {
	rows, err := q.db.Query(ctx, listPendingScanDocuments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.DealModule,
			&i.DealID,
			&i.DocumentType,
			&i.FileName,
			&i.StorageBucket,
			&i.StorageKey,
			&i.FileSize,
			&i.MimeType,
			&i.ChecksumSha256,
			&i.ScanStatus,
			&i.ScannedAt,
			&i.Version,
			&i.IsCurrent,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentScanned = `-- name: MarkDocumentScanned :one
UPDATE documents SET
    scan_status = $2,
    scanned_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, deal_module, deal_id, document_type, file_name, storage_bucket, storage_key, file_size, mime_type, checksum_sha256, scan_status, scanned_at, version, is_current, uploaded_by, uploaded_at, deleted_at
`

type MarkDocumentScannedParams struct {
	ID         uuid.UUID `json:"id"`
	ScanStatus string    `json:"scan_status"`
}

// Cập nhật kết quả quét virus
func (q *Queries) MarkDocumentScanned(ctx context.Context, arg MarkDocumentScannedParams) (Document, error) {
	row := q.db.QueryRow(ctx, markDocumentScanned, arg.ID, arg.ScanStatus)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.DealID,
		&i.DocumentType,
		&i.FileName,
		&i.StorageBucket,
		&i.StorageKey,
		&i.FileSize,
		&i.MimeType,
		&i.ChecksumSha256,
		&i.ScanStatus,
		&i.ScannedAt,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markOldVersions = `-- name: MarkOldVersions :exec
UPDATE documents SET is_current = false
WHERE deal_module = $1
  AND deal_id = $2
  AND file_name = $3
  AND is_current = true
  AND deleted_at IS NULL
  AND id != $4
`

type MarkOldVersionsParams struct {
	DealModule string    `json:"deal_module"`
	DealID     uuid.UUID `json:"deal_id"`
	FileName   string    `json:"file_name"`
	ID         uuid.UUID `json:"id"`
}

// Đánh dấu các version cũ khi upload version mới
func (q *Queries) MarkOldVersions(ctx context.Context, arg MarkOldVersionsParams) error {
	_, err := q.db.Exec(ctx, markOldVersions,
		arg.DealModule,
		arg.DealID,
		arg.FileName,
		arg.ID,
	)
	return err
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
UPDATE documents SET
    deleted_at = NOW(),
    is_current = false
WHERE id = $1 AND deleted_at IS NULL
`

// Xóa mềm tài liệu
func (q *Queries) SoftDeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteDocument, id)
	return err
}
