// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exchange_rates.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExchangeRate = `-- name: CreateExchangeRate :one

INSERT INTO exchange_rates (
    id, currency_code, effective_date,
    buy_transfer_rate, sell_transfer_rate, mid_rate,
    source, created_at, created_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, NOW(), $7
)
RETURNING id, currency_code, effective_date, buy_transfer_rate, sell_transfer_rate, mid_rate, source, created_at, created_by
`

type CreateExchangeRateParams struct {
	CurrencyCode     string         `json:"currency_code"`
	EffectiveDate    pgtype.Date    `json:"effective_date"`
	BuyTransferRate  pgtype.Numeric `json:"buy_transfer_rate"`
	SellTransferRate pgtype.Numeric `json:"sell_transfer_rate"`
	MidRate          pgtype.Numeric `json:"mid_rate"`
	Source           string         `json:"source"`
	CreatedBy        pgtype.UUID    `json:"created_by"`
}

// ============================================================================
// exchange_rates.sql — Queries for exchange_rates table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, createExchangeRate,
		arg.CurrencyCode,
		arg.EffectiveDate,
		arg.BuyTransferRate,
		arg.SellTransferRate,
		arg.MidRate,
		arg.Source,
		arg.CreatedBy,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CurrencyCode,
		&i.EffectiveDate,
		&i.BuyTransferRate,
		&i.SellTransferRate,
		&i.MidRate,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getExchangeRateByID = `-- name: GetExchangeRateByID :one
SELECT id, currency_code, effective_date, buy_transfer_rate, sell_transfer_rate, mid_rate, source, created_at, created_by FROM exchange_rates WHERE id = $1
`

func (q *Queries) GetExchangeRateByID(ctx context.Context, id uuid.UUID) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getExchangeRateByID, id)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CurrencyCode,
		&i.EffectiveDate,
		&i.BuyTransferRate,
		&i.SellTransferRate,
		&i.MidRate,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLatestRateByDate = `-- name: GetLatestRateByDate :one
SELECT id, currency_code, effective_date, buy_transfer_rate, sell_transfer_rate, mid_rate, source, created_at, created_by FROM exchange_rates
WHERE currency_code = $1 AND effective_date <= $2
ORDER BY effective_date DESC
LIMIT 1
`

type GetLatestRateByDateParams struct {
	CurrencyCode  string      `json:"currency_code"`
	EffectiveDate pgtype.Date `json:"effective_date"`
}

// Lấy tỷ giá mới nhất cho một currency tính đến ngày chỉ định
// Logic "ngày làm việc trước đó": ứng dụng tính previous business day rồi truyền vào
func (q *Queries) GetLatestRateByDate(ctx context.Context, arg GetLatestRateByDateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getLatestRateByDate, arg.CurrencyCode, arg.EffectiveDate)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CurrencyCode,
		&i.EffectiveDate,
		&i.BuyTransferRate,
		&i.SellTransferRate,
		&i.MidRate,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getMidRate = `-- name: GetMidRate :one
SELECT mid_rate FROM exchange_rates
WHERE currency_code = $1 AND effective_date = $2
`

type GetMidRateParams struct {
	CurrencyCode  string      `json:"currency_code"`
	EffectiveDate pgtype.Date `json:"effective_date"`
}

// Lấy mid rate cho quy đổi credit limit
func (q *Queries) GetMidRate(ctx context.Context, arg GetMidRateParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getMidRate, arg.CurrencyCode, arg.EffectiveDate)
	var mid_rate pgtype.Numeric
	err := row.Scan(&mid_rate)
	return mid_rate, err
}

const listRatesByCurrencyAndDateRange = `-- name: ListRatesByCurrencyAndDateRange :many
SELECT id, currency_code, effective_date, buy_transfer_rate, sell_transfer_rate, mid_rate, source, created_at, created_by FROM exchange_rates
WHERE currency_code = $1
  AND effective_date BETWEEN $2 AND $3
ORDER BY effective_date DESC
LIMIT $4 OFFSET $5
`

type ListRatesByCurrencyAndDateRangeParams struct {
	CurrencyCode    string      `json:"currency_code"`
	EffectiveDate   pgtype.Date `json:"effective_date"`
	EffectiveDate_2 pgtype.Date `json:"effective_date_2"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

func (q *Queries) ListRatesByCurrencyAndDateRange(ctx context.Context, arg ListRatesByCurrencyAndDateRangeParams) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, listRatesByCurrencyAndDateRange,
		arg.CurrencyCode,
		arg.EffectiveDate,
		arg.EffectiveDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.ID,
			&i.CurrencyCode,
			&i.EffectiveDate,
			&i.BuyTransferRate,
			&i.SellTransferRate,
			&i.MidRate,
			&i.Source,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatesByDate = `-- name: ListRatesByDate :many
SELECT id, currency_code, effective_date, buy_transfer_rate, sell_transfer_rate, mid_rate, source, created_at, created_by FROM exchange_rates
WHERE effective_date = $1
ORDER BY currency_code ASC
`

// Lấy tất cả tỷ giá của một ngày
func (q *Queries) ListRatesByDate(ctx context.Context, effectiveDate pgtype.Date) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, listRatesByDate, effectiveDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.ID,
			&i.CurrencyCode,
			&i.EffectiveDate,
			&i.BuyTransferRate,
			&i.SellTransferRate,
			&i.MidRate,
			&i.Source,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :one
INSERT INTO exchange_rates (
    id, currency_code, effective_date,
    buy_transfer_rate, sell_transfer_rate, mid_rate,
    source, created_at, created_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, NOW(), $7
)
ON CONFLICT (currency_code, effective_date) DO UPDATE SET
    buy_transfer_rate = EXCLUDED.buy_transfer_rate,
    sell_transfer_rate = EXCLUDED.sell_transfer_rate,
    mid_rate = EXCLUDED.mid_rate,
    source = EXCLUDED.source,
    created_by = EXCLUDED.created_by
RETURNING id, currency_code, effective_date, buy_transfer_rate, sell_transfer_rate, mid_rate, source, created_at, created_by
`

type UpsertExchangeRateParams struct {
	CurrencyCode     string         `json:"currency_code"`
	EffectiveDate    pgtype.Date    `json:"effective_date"`
	BuyTransferRate  pgtype.Numeric `json:"buy_transfer_rate"`
	SellTransferRate pgtype.Numeric `json:"sell_transfer_rate"`
	MidRate          pgtype.Numeric `json:"mid_rate"`
	Source           string         `json:"source"`
	CreatedBy        pgtype.UUID    `json:"created_by"`
}

// Insert or update tỷ giá — unique on (currency_code, effective_date)
func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, upsertExchangeRate,
		arg.CurrencyCode,
		arg.EffectiveDate,
		arg.BuyTransferRate,
		arg.SellTransferRate,
		arg.MidRate,
		arg.Source,
		arg.CreatedBy,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CurrencyCode,
		&i.EffectiveDate,
		&i.BuyTransferRate,
		&i.SellTransferRate,
		&i.MidRate,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
