// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fx_deals.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFxDeals = `-- name: CountFxDeals :one
SELECT COUNT(*) FROM fx_deals WHERE deleted_at IS NULL
`

func (q *Queries) CountFxDeals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFxDeals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFxDealsByStatusAndDate = `-- name: CountFxDealsByStatusAndDate :many
SELECT status, COUNT(*) AS deal_count
FROM fx_deals
WHERE trade_date = $1 AND deleted_at IS NULL
GROUP BY status
ORDER BY status
`

type CountFxDealsByStatusAndDateRow struct {
	Status    string `json:"status"`
	DealCount int64  `json:"deal_count"`
}

// Dashboard: đếm deal theo status cho một ngày — hiển thị summary cards
func (q *Queries) CountFxDealsByStatusAndDate(ctx context.Context, tradeDate pgtype.Date) ([]CountFxDealsByStatusAndDateRow, error) {
	rows, err := q.db.Query(ctx, countFxDealsByStatusAndDate, tradeDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFxDealsByStatusAndDateRow{}
	for rows.Next() {
		var i CountFxDealsByStatusAndDateRow
		if err := rows.Scan(&i.Status, &i.DealCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createFxDeal = `-- name: CreateFxDeal :one

INSERT INTO fx_deals (
    id, deal_number, ticket_number, counterparty_id,
    deal_type, direction, notional_amount, currency_code, pair_code,
    trade_date, branch_id, uses_credit_limit, status, note,
    cloned_from_id, created_at, created_by, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, 'OPEN', $12,
    $13, NOW(), $14, NOW(), $14
)
RETURNING id, deal_number, ticket_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, uses_credit_limit, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type CreateFxDealParams struct {
	DealNumber      string         `json:"deal_number"`
	TicketNumber    *string        `json:"ticket_number"`
	CounterpartyID  uuid.UUID      `json:"counterparty_id"`
	DealType        string         `json:"deal_type"`
	Direction       string         `json:"direction"`
	NotionalAmount  pgtype.Numeric `json:"notional_amount"`
	CurrencyCode    string         `json:"currency_code"`
	PairCode        string         `json:"pair_code"`
	TradeDate       pgtype.Date    `json:"trade_date"`
	BranchID        uuid.UUID      `json:"branch_id"`
	UsesCreditLimit bool           `json:"uses_credit_limit"`
	Note            *string        `json:"note"`
	ClonedFromID    pgtype.UUID    `json:"cloned_from_id"`
	CreatedBy       uuid.UUID      `json:"created_by"`
}

// ============================================================================
// fx_deals.sql — Queries for fx_deals table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateFxDeal(ctx context.Context, arg CreateFxDealParams) (FxDeal, error) {
	row := q.db.QueryRow(ctx, createFxDeal,
		arg.DealNumber,
		arg.TicketNumber,
		arg.CounterpartyID,
		arg.DealType,
		arg.Direction,
		arg.NotionalAmount,
		arg.CurrencyCode,
		arg.PairCode,
		arg.TradeDate,
		arg.BranchID,
		arg.UsesCreditLimit,
		arg.Note,
		arg.ClonedFromID,
		arg.CreatedBy,
	)
	var i FxDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.TicketNumber,
		&i.CounterpartyID,
		&i.DealType,
		&i.Direction,
		&i.NotionalAmount,
		&i.CurrencyCode,
		&i.PairCode,
		&i.TradeDate,
		&i.BranchID,
		&i.UsesCreditLimit,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getFxDealByID = `-- name: GetFxDealByID :one
SELECT id, deal_number, ticket_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, uses_credit_limit, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM fx_deals
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFxDealByID(ctx context.Context, id uuid.UUID) (FxDeal, error) {
	row := q.db.QueryRow(ctx, getFxDealByID, id)
	var i FxDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.TicketNumber,
		&i.CounterpartyID,
		&i.DealType,
		&i.Direction,
		&i.NotionalAmount,
		&i.CurrencyCode,
		&i.PairCode,
		&i.TradeDate,
		&i.BranchID,
		&i.UsesCreditLimit,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getFxDealWithLegs = `-- name: GetFxDealWithLegs :many
SELECT
    d.id, d.deal_number, d.ticket_number, d.counterparty_id, d.deal_type, d.direction, d.notional_amount, d.currency_code, d.pair_code, d.trade_date, d.branch_id, d.uses_credit_limit, d.status, d.note, d.cloned_from_id, d.cancel_reason, d.cancel_requested_by, d.cancel_requested_at, d.created_at, d.created_by, d.updated_at, d.updated_by, d.deleted_at,
    l.id AS leg_id,
    l.leg_number,
    l.value_date,
    l.settlement_date,
    l.exchange_rate AS leg_exchange_rate,
    l.converted_amount,
    l.converted_currency,
    l.internal_ssi_id,
    l.counterparty_ssi_id,
    l.requires_international_settlement
FROM fx_deals d
LEFT JOIN fx_deal_legs l ON l.deal_id = d.id
WHERE d.id = $1 AND d.deleted_at IS NULL
ORDER BY l.leg_number ASC
`

type GetFxDealWithLegsRow struct {
	ID                              uuid.UUID          `json:"id"`
	DealNumber                      string             `json:"deal_number"`
	TicketNumber                    *string            `json:"ticket_number"`
	CounterpartyID                  uuid.UUID          `json:"counterparty_id"`
	DealType                        string             `json:"deal_type"`
	Direction                       string             `json:"direction"`
	NotionalAmount                  pgtype.Numeric     `json:"notional_amount"`
	CurrencyCode                    string             `json:"currency_code"`
	PairCode                        string             `json:"pair_code"`
	TradeDate                       pgtype.Date        `json:"trade_date"`
	BranchID                        uuid.UUID          `json:"branch_id"`
	UsesCreditLimit                 bool               `json:"uses_credit_limit"`
	Status                          string             `json:"status"`
	Note                            *string            `json:"note"`
	ClonedFromID                    pgtype.UUID        `json:"cloned_from_id"`
	CancelReason                    *string            `json:"cancel_reason"`
	CancelRequestedBy               pgtype.UUID        `json:"cancel_requested_by"`
	CancelRequestedAt               pgtype.Timestamptz `json:"cancel_requested_at"`
	CreatedAt                       time.Time          `json:"created_at"`
	CreatedBy                       uuid.UUID          `json:"created_by"`
	UpdatedAt                       time.Time          `json:"updated_at"`
	UpdatedBy                       uuid.UUID          `json:"updated_by"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
	LegID                           pgtype.UUID        `json:"leg_id"`
	LegNumber                       *int16             `json:"leg_number"`
	ValueDate                       pgtype.Date        `json:"value_date"`
	SettlementDate                  pgtype.Date        `json:"settlement_date"`
	LegExchangeRate                 pgtype.Numeric     `json:"leg_exchange_rate"`
	ConvertedAmount                 pgtype.Numeric     `json:"converted_amount"`
	ConvertedCurrency               *string            `json:"converted_currency"`
	InternalSsiID                   pgtype.UUID        `json:"internal_ssi_id"`
	CounterpartySsiID               pgtype.UUID        `json:"counterparty_ssi_id"`
	RequiresInternationalSettlement *bool              `json:"requires_international_settlement"`
}

// Lấy deal header kèm tất cả legs — dùng cho chi tiết deal
func (q *Queries) GetFxDealWithLegs(ctx context.Context, id uuid.UUID) ([]GetFxDealWithLegsRow, error) {
	rows, err := q.db.Query(ctx, getFxDealWithLegs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFxDealWithLegsRow{}
	for rows.Next() {
		var i GetFxDealWithLegsRow
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.DealType,
			&i.Direction,
			&i.NotionalAmount,
			&i.CurrencyCode,
			&i.PairCode,
			&i.TradeDate,
			&i.BranchID,
			&i.UsesCreditLimit,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.LegID,
			&i.LegNumber,
			&i.ValueDate,
			&i.SettlementDate,
			&i.LegExchangeRate,
			&i.ConvertedAmount,
			&i.ConvertedCurrency,
			&i.InternalSsiID,
			&i.CounterpartySsiID,
			&i.RequiresInternationalSettlement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFxDeals = `-- name: ListFxDeals :many
SELECT id, deal_number, ticket_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, uses_credit_limit, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM fx_deals
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListFxDealsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFxDeals(ctx context.Context, arg ListFxDealsParams) ([]FxDeal, error) {
	rows, err := q.db.Query(ctx, listFxDeals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxDeal{}
	for rows.Next() {
		var i FxDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.DealType,
			&i.Direction,
			&i.NotionalAmount,
			&i.CurrencyCode,
			&i.PairCode,
			&i.TradeDate,
			&i.BranchID,
			&i.UsesCreditLimit,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFxDealsByCounterpartyAndDateRange = `-- name: ListFxDealsByCounterpartyAndDateRange :many
SELECT id, deal_number, ticket_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, uses_credit_limit, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM fx_deals
WHERE counterparty_id = $1
  AND trade_date BETWEEN $2 AND $3
  AND deleted_at IS NULL
ORDER BY trade_date DESC, created_at DESC
LIMIT $4 OFFSET $5
`

type ListFxDealsByCounterpartyAndDateRangeParams struct {
	CounterpartyID uuid.UUID   `json:"counterparty_id"`
	TradeDate      pgtype.Date `json:"trade_date"`
	TradeDate_2    pgtype.Date `json:"trade_date_2"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListFxDealsByCounterpartyAndDateRange(ctx context.Context, arg ListFxDealsByCounterpartyAndDateRangeParams) ([]FxDeal, error) {
	rows, err := q.db.Query(ctx, listFxDealsByCounterpartyAndDateRange,
		arg.CounterpartyID,
		arg.TradeDate,
		arg.TradeDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxDeal{}
	for rows.Next() {
		var i FxDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.DealType,
			&i.Direction,
			&i.NotionalAmount,
			&i.CurrencyCode,
			&i.PairCode,
			&i.TradeDate,
			&i.BranchID,
			&i.UsesCreditLimit,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFxDealsByStatus = `-- name: ListFxDealsByStatus :many
SELECT id, deal_number, ticket_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, uses_credit_limit, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM fx_deals
WHERE status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFxDealsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListFxDealsByStatus(ctx context.Context, arg ListFxDealsByStatusParams) ([]FxDeal, error) {
	rows, err := q.db.Query(ctx, listFxDealsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxDeal{}
	for rows.Next() {
		var i FxDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.DealType,
			&i.Direction,
			&i.NotionalAmount,
			&i.CurrencyCode,
			&i.PairCode,
			&i.TradeDate,
			&i.BranchID,
			&i.UsesCreditLimit,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFxDealsByTradeDate = `-- name: ListFxDealsByTradeDate :many
SELECT id, deal_number, ticket_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, uses_credit_limit, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM fx_deals
WHERE trade_date = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFxDealsByTradeDateParams struct {
	TradeDate pgtype.Date `json:"trade_date"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListFxDealsByTradeDate(ctx context.Context, arg ListFxDealsByTradeDateParams) ([]FxDeal, error) {
	rows, err := q.db.Query(ctx, listFxDealsByTradeDate, arg.TradeDate, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxDeal{}
	for rows.Next() {
		var i FxDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.DealType,
			&i.Direction,
			&i.NotionalAmount,
			&i.CurrencyCode,
			&i.PairCode,
			&i.TradeDate,
			&i.BranchID,
			&i.UsesCreditLimit,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFxDealsForSettlement = `-- name: ListFxDealsForSettlement :many
SELECT d.id, d.deal_number, d.ticket_number, d.counterparty_id, d.deal_type, d.direction, d.notional_amount, d.currency_code, d.pair_code, d.trade_date, d.branch_id, d.uses_credit_limit, d.status, d.note, d.cloned_from_id, d.cancel_reason, d.cancel_requested_by, d.cancel_requested_at, d.created_at, d.created_by, d.updated_at, d.updated_by, d.deleted_at FROM fx_deals d
JOIN fx_deal_legs l ON l.deal_id = d.id
WHERE d.status = 'PENDING_SETTLEMENT'
  AND d.deleted_at IS NULL
  AND l.requires_international_settlement = true
  AND l.settlement_date = $1
ORDER BY d.created_at ASC
LIMIT $2 OFFSET $3
`

type ListFxDealsForSettlementParams struct {
	SettlementDate pgtype.Date `json:"settlement_date"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

// Deals cần thanh toán quốc tế — chỉ deals đã qua phê duyệt booking
func (q *Queries) ListFxDealsForSettlement(ctx context.Context, arg ListFxDealsForSettlementParams) ([]FxDeal, error) {
	rows, err := q.db.Query(ctx, listFxDealsForSettlement, arg.SettlementDate, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxDeal{}
	for rows.Next() {
		var i FxDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.DealType,
			&i.Direction,
			&i.NotionalAmount,
			&i.CurrencyCode,
			&i.PairCode,
			&i.TradeDate,
			&i.BranchID,
			&i.UsesCreditLimit,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFxDealsPendingApproval = `-- name: ListFxDealsPendingApproval :many
SELECT id, deal_number, ticket_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, uses_credit_limit, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM fx_deals
WHERE status = $1 AND deleted_at IS NULL
ORDER BY trade_date ASC, created_at ASC
LIMIT $2 OFFSET $3
`

type ListFxDealsPendingApprovalParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

// Deals chờ phê duyệt — view cho Desk Head / Director / Accountant
func (q *Queries) ListFxDealsPendingApproval(ctx context.Context, arg ListFxDealsPendingApprovalParams) ([]FxDeal, error) {
	rows, err := q.db.Query(ctx, listFxDealsPendingApproval, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxDeal{}
	for rows.Next() {
		var i FxDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.DealType,
			&i.Direction,
			&i.NotionalAmount,
			&i.CurrencyCode,
			&i.PairCode,
			&i.TradeDate,
			&i.BranchID,
			&i.UsesCreditLimit,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFxDealCancelRequest = `-- name: SetFxDealCancelRequest :one
UPDATE fx_deals SET
    cancel_reason = $3,
    cancel_requested_by = $1,
    cancel_requested_at = NOW(),
    status = 'CANCELLED',
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = $4
RETURNING id, deal_number, ticket_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, uses_credit_limit, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type SetFxDealCancelRequestParams struct {
	CancelRequestedBy pgtype.UUID `json:"cancel_requested_by"`
	ID                uuid.UUID   `json:"id"`
	CancelReason      *string     `json:"cancel_reason"`
	Status            string      `json:"status"`
}

// Dealer yêu cầu hủy deal đã hoàn thành
func (q *Queries) SetFxDealCancelRequest(ctx context.Context, arg SetFxDealCancelRequestParams) (FxDeal, error) {
	row := q.db.QueryRow(ctx, setFxDealCancelRequest,
		arg.CancelRequestedBy,
		arg.ID,
		arg.CancelReason,
		arg.Status,
	)
	var i FxDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.TicketNumber,
		&i.CounterpartyID,
		&i.DealType,
		&i.Direction,
		&i.NotionalAmount,
		&i.CurrencyCode,
		&i.PairCode,
		&i.TradeDate,
		&i.BranchID,
		&i.UsesCreditLimit,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteFxDeal = `-- name: SoftDeleteFxDeal :exec
UPDATE fx_deals SET deleted_at = NOW(), updated_by = $2
WHERE id = $1 AND deleted_at IS NULL AND status = 'OPEN'
`

type SoftDeleteFxDealParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedBy uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteFxDeal(ctx context.Context, arg SoftDeleteFxDealParams) error {
	_, err := q.db.Exec(ctx, softDeleteFxDeal, arg.ID, arg.UpdatedBy)
	return err
}

const updateFxDeal = `-- name: UpdateFxDeal :one
UPDATE fx_deals SET
    ticket_number = COALESCE($3, ticket_number),
    counterparty_id = COALESCE($4, counterparty_id),
    deal_type = COALESCE($5, deal_type),
    direction = COALESCE($6, direction),
    notional_amount = COALESCE($7, notional_amount),
    currency_code = COALESCE($8, currency_code),
    pair_code = COALESCE($9, pair_code),
    trade_date = COALESCE($10, trade_date),
    uses_credit_limit = COALESCE($11, uses_credit_limit),
    note = COALESCE($12, note),
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = 'OPEN'
RETURNING id, deal_number, ticket_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, uses_credit_limit, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type UpdateFxDealParams struct {
	UpdatedBy       uuid.UUID      `json:"updated_by"`
	ID              uuid.UUID      `json:"id"`
	TicketNumber    *string        `json:"ticket_number"`
	CounterpartyID  pgtype.UUID    `json:"counterparty_id"`
	DealType        *string        `json:"deal_type"`
	Direction       *string        `json:"direction"`
	NotionalAmount  pgtype.Numeric `json:"notional_amount"`
	CurrencyCode    *string        `json:"currency_code"`
	PairCode        *string        `json:"pair_code"`
	TradeDate       pgtype.Date    `json:"trade_date"`
	UsesCreditLimit *bool          `json:"uses_credit_limit"`
	Note            *string        `json:"note"`
}

// Chỉ cập nhật khi deal ở trạng thái OPEN
func (q *Queries) UpdateFxDeal(ctx context.Context, arg UpdateFxDealParams) (FxDeal, error) {
	row := q.db.QueryRow(ctx, updateFxDeal,
		arg.UpdatedBy,
		arg.ID,
		arg.TicketNumber,
		arg.CounterpartyID,
		arg.DealType,
		arg.Direction,
		arg.NotionalAmount,
		arg.CurrencyCode,
		arg.PairCode,
		arg.TradeDate,
		arg.UsesCreditLimit,
		arg.Note,
	)
	var i FxDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.TicketNumber,
		&i.CounterpartyID,
		&i.DealType,
		&i.Direction,
		&i.NotionalAmount,
		&i.CurrencyCode,
		&i.PairCode,
		&i.TradeDate,
		&i.BranchID,
		&i.UsesCreditLimit,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const updateFxDealStatus = `-- name: UpdateFxDealStatus :one
UPDATE fx_deals SET
    status = $3,
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = $4
RETURNING id, deal_number, ticket_number, counterparty_id, deal_type, direction, notional_amount, currency_code, pair_code, trade_date, branch_id, uses_credit_limit, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type UpdateFxDealStatusParams struct {
	UpdatedBy uuid.UUID `json:"updated_by"`
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	Status_2  string    `json:"status_2"`
}

// Optimistic status transition: chỉ cập nhật nếu status hiện tại khớp
// Application phải kiểm tra status_transition_rules trước khi gọi
func (q *Queries) UpdateFxDealStatus(ctx context.Context, arg UpdateFxDealStatusParams) (FxDeal, error) {
	row := q.db.QueryRow(ctx, updateFxDealStatus,
		arg.UpdatedBy,
		arg.ID,
		arg.Status,
		arg.Status_2,
	)
	var i FxDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.TicketNumber,
		&i.CounterpartyID,
		&i.DealType,
		&i.Direction,
		&i.NotionalAmount,
		&i.CurrencyCode,
		&i.PairCode,
		&i.TradeDate,
		&i.BranchID,
		&i.UsesCreditLimit,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}
