// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fx_deal_legs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFxDealLeg = `-- name: CreateFxDealLeg :one

INSERT INTO fx_deal_legs (
    id, deal_id, leg_number, value_date, settlement_date,
    exchange_rate, converted_amount, converted_currency,
    internal_ssi_id, counterparty_ssi_id,
    requires_international_settlement,
    created_at, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    NOW(), NOW(), $11
)
RETURNING id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id, requires_international_settlement, created_at, updated_at, updated_by
`

type CreateFxDealLegParams struct {
	DealID                          uuid.UUID      `json:"deal_id"`
	LegNumber                       int16          `json:"leg_number"`
	ValueDate                       pgtype.Date    `json:"value_date"`
	SettlementDate                  pgtype.Date    `json:"settlement_date"`
	ExchangeRate                    pgtype.Numeric `json:"exchange_rate"`
	ConvertedAmount                 pgtype.Numeric `json:"converted_amount"`
	ConvertedCurrency               string         `json:"converted_currency"`
	InternalSsiID                   uuid.UUID      `json:"internal_ssi_id"`
	CounterpartySsiID               uuid.UUID      `json:"counterparty_ssi_id"`
	RequiresInternationalSettlement bool           `json:"requires_international_settlement"`
	UpdatedBy                       pgtype.UUID    `json:"updated_by"`
}

// ============================================================================
// fx_deal_legs.sql — Queries for fx_deal_legs table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateFxDealLeg(ctx context.Context, arg CreateFxDealLegParams) (FxDealLeg, error) {
	row := q.db.QueryRow(ctx, createFxDealLeg,
		arg.DealID,
		arg.LegNumber,
		arg.ValueDate,
		arg.SettlementDate,
		arg.ExchangeRate,
		arg.ConvertedAmount,
		arg.ConvertedCurrency,
		arg.InternalSsiID,
		arg.CounterpartySsiID,
		arg.RequiresInternationalSettlement,
		arg.UpdatedBy,
	)
	var i FxDealLeg
	err := row.Scan(
		&i.ID,
		&i.DealID,
		&i.LegNumber,
		&i.ValueDate,
		&i.SettlementDate,
		&i.ExchangeRate,
		&i.ConvertedAmount,
		&i.ConvertedCurrency,
		&i.InternalSsiID,
		&i.CounterpartySsiID,
		&i.RequiresInternationalSettlement,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteFxDealLegsByDealID = `-- name: DeleteFxDealLegsByDealID :exec
DELETE FROM fx_deal_legs WHERE deal_id = $1
`

// Xóa tất cả legs — dùng khi thay đổi deal type (e.g. Swap → Spot)
func (q *Queries) DeleteFxDealLegsByDealID(ctx context.Context, dealID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFxDealLegsByDealID, dealID)
	return err
}

const getFxDealLegByDealIDAndLeg = `-- name: GetFxDealLegByDealIDAndLeg :one
SELECT id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id, requires_international_settlement, created_at, updated_at, updated_by FROM fx_deal_legs
WHERE deal_id = $1 AND leg_number = $2
`

type GetFxDealLegByDealIDAndLegParams struct {
	DealID    uuid.UUID `json:"deal_id"`
	LegNumber int16     `json:"leg_number"`
}

// Lấy leg cụ thể của deal (near=1, far=2)
func (q *Queries) GetFxDealLegByDealIDAndLeg(ctx context.Context, arg GetFxDealLegByDealIDAndLegParams) (FxDealLeg, error) {
	row := q.db.QueryRow(ctx, getFxDealLegByDealIDAndLeg, arg.DealID, arg.LegNumber)
	var i FxDealLeg
	err := row.Scan(
		&i.ID,
		&i.DealID,
		&i.LegNumber,
		&i.ValueDate,
		&i.SettlementDate,
		&i.ExchangeRate,
		&i.ConvertedAmount,
		&i.ConvertedCurrency,
		&i.InternalSsiID,
		&i.CounterpartySsiID,
		&i.RequiresInternationalSettlement,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getFxDealLegByID = `-- name: GetFxDealLegByID :one
SELECT id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id, requires_international_settlement, created_at, updated_at, updated_by FROM fx_deal_legs WHERE id = $1
`

func (q *Queries) GetFxDealLegByID(ctx context.Context, id uuid.UUID) (FxDealLeg, error) {
	row := q.db.QueryRow(ctx, getFxDealLegByID, id)
	var i FxDealLeg
	err := row.Scan(
		&i.ID,
		&i.DealID,
		&i.LegNumber,
		&i.ValueDate,
		&i.SettlementDate,
		&i.ExchangeRate,
		&i.ConvertedAmount,
		&i.ConvertedCurrency,
		&i.InternalSsiID,
		&i.CounterpartySsiID,
		&i.RequiresInternationalSettlement,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getFxDealLegsByDealID = `-- name: GetFxDealLegsByDealID :many
SELECT id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id, requires_international_settlement, created_at, updated_at, updated_by FROM fx_deal_legs
WHERE deal_id = $1
ORDER BY leg_number ASC
`

// Lấy tất cả legs của một deal (1 for Spot/Fwd, 2 for Swap)
func (q *Queries) GetFxDealLegsByDealID(ctx context.Context, dealID uuid.UUID) ([]FxDealLeg, error) {
	rows, err := q.db.Query(ctx, getFxDealLegsByDealID, dealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxDealLeg{}
	for rows.Next() {
		var i FxDealLeg
		if err := rows.Scan(
			&i.ID,
			&i.DealID,
			&i.LegNumber,
			&i.ValueDate,
			&i.SettlementDate,
			&i.ExchangeRate,
			&i.ConvertedAmount,
			&i.ConvertedCurrency,
			&i.InternalSsiID,
			&i.CounterpartySsiID,
			&i.RequiresInternationalSettlement,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegsRequiringSettlement = `-- name: ListLegsRequiringSettlement :many
SELECT
    l.id, l.deal_id, l.leg_number, l.value_date, l.settlement_date, l.exchange_rate, l.converted_amount, l.converted_currency, l.internal_ssi_id, l.counterparty_ssi_id, l.requires_international_settlement, l.created_at, l.updated_at, l.updated_by,
    d.deal_number,
    d.deal_type,
    d.direction,
    d.counterparty_id,
    d.notional_amount,
    d.currency_code
FROM fx_deal_legs l
JOIN fx_deals d ON d.id = l.deal_id
WHERE l.requires_international_settlement = true
  AND l.settlement_date = $1
  AND d.status = 'PENDING_SETTLEMENT'
  AND d.deleted_at IS NULL
ORDER BY d.created_at ASC
`

type ListLegsRequiringSettlementRow struct {
	ID                              uuid.UUID      `json:"id"`
	DealID                          uuid.UUID      `json:"deal_id"`
	LegNumber                       int16          `json:"leg_number"`
	ValueDate                       pgtype.Date    `json:"value_date"`
	SettlementDate                  pgtype.Date    `json:"settlement_date"`
	ExchangeRate                    pgtype.Numeric `json:"exchange_rate"`
	ConvertedAmount                 pgtype.Numeric `json:"converted_amount"`
	ConvertedCurrency               string         `json:"converted_currency"`
	InternalSsiID                   uuid.UUID      `json:"internal_ssi_id"`
	CounterpartySsiID               uuid.UUID      `json:"counterparty_ssi_id"`
	RequiresInternationalSettlement bool           `json:"requires_international_settlement"`
	CreatedAt                       time.Time      `json:"created_at"`
	UpdatedAt                       time.Time      `json:"updated_at"`
	UpdatedBy                       pgtype.UUID    `json:"updated_by"`
	DealNumber                      string         `json:"deal_number"`
	DealType                        string         `json:"deal_type"`
	Direction                       string         `json:"direction"`
	CounterpartyID                  uuid.UUID      `json:"counterparty_id"`
	NotionalAmount                  pgtype.Numeric `json:"notional_amount"`
	CurrencyCode                    string         `json:"currency_code"`
}

// Legs cần thanh toán quốc tế theo ngày settlement — BP.TTQT xử lý
func (q *Queries) ListLegsRequiringSettlement(ctx context.Context, settlementDate pgtype.Date) ([]ListLegsRequiringSettlementRow, error) {
	rows, err := q.db.Query(ctx, listLegsRequiringSettlement, settlementDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegsRequiringSettlementRow{}
	for rows.Next() {
		var i ListLegsRequiringSettlementRow
		if err := rows.Scan(
			&i.ID,
			&i.DealID,
			&i.LegNumber,
			&i.ValueDate,
			&i.SettlementDate,
			&i.ExchangeRate,
			&i.ConvertedAmount,
			&i.ConvertedCurrency,
			&i.InternalSsiID,
			&i.CounterpartySsiID,
			&i.RequiresInternationalSettlement,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DealNumber,
			&i.DealType,
			&i.Direction,
			&i.CounterpartyID,
			&i.NotionalAmount,
			&i.CurrencyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFxDealLeg = `-- name: UpdateFxDealLeg :one
UPDATE fx_deal_legs SET
    value_date = COALESCE($3, value_date),
    settlement_date = COALESCE($4, settlement_date),
    exchange_rate = COALESCE($5, exchange_rate),
    converted_amount = COALESCE($6, converted_amount),
    converted_currency = COALESCE($7, converted_currency),
    internal_ssi_id = COALESCE($8, internal_ssi_id),
    counterparty_ssi_id = COALESCE($9, counterparty_ssi_id),
    requires_international_settlement = COALESCE($10, requires_international_settlement),
    updated_by = $1
WHERE id = $2
RETURNING id, deal_id, leg_number, value_date, settlement_date, exchange_rate, converted_amount, converted_currency, internal_ssi_id, counterparty_ssi_id, requires_international_settlement, created_at, updated_at, updated_by
`

type UpdateFxDealLegParams struct {
	UpdatedBy                       pgtype.UUID    `json:"updated_by"`
	ID                              uuid.UUID      `json:"id"`
	ValueDate                       pgtype.Date    `json:"value_date"`
	SettlementDate                  pgtype.Date    `json:"settlement_date"`
	ExchangeRate                    pgtype.Numeric `json:"exchange_rate"`
	ConvertedAmount                 pgtype.Numeric `json:"converted_amount"`
	ConvertedCurrency               *string        `json:"converted_currency"`
	InternalSsiID                   pgtype.UUID    `json:"internal_ssi_id"`
	CounterpartySsiID               pgtype.UUID    `json:"counterparty_ssi_id"`
	RequiresInternationalSettlement *bool          `json:"requires_international_settlement"`
}

func (q *Queries) UpdateFxDealLeg(ctx context.Context, arg UpdateFxDealLegParams) (FxDealLeg, error) {
	row := q.db.QueryRow(ctx, updateFxDealLeg,
		arg.UpdatedBy,
		arg.ID,
		arg.ValueDate,
		arg.SettlementDate,
		arg.ExchangeRate,
		arg.ConvertedAmount,
		arg.ConvertedCurrency,
		arg.InternalSsiID,
		arg.CounterpartySsiID,
		arg.RequiresInternationalSettlement,
	)
	var i FxDealLeg
	err := row.Scan(
		&i.ID,
		&i.DealID,
		&i.LegNumber,
		&i.ValueDate,
		&i.SettlementDate,
		&i.ExchangeRate,
		&i.ConvertedAmount,
		&i.ConvertedCurrency,
		&i.InternalSsiID,
		&i.CounterpartySsiID,
		&i.RequiresInternationalSettlement,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
