// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: international_payments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approvePayment = `-- name: ApprovePayment :one
UPDATE international_payments SET
    settlement_status = 'APPROVED',
    settled_by = $1,
    settled_at = NOW()
WHERE id = $2 AND settlement_status = 'PENDING'
RETURNING id, source_module, source_deal_id, source_leg_number, ticket_display, counterparty_id, debit_account, bic_code, currency_code, amount, transfer_date, counterparty_ssi, original_trade_date, approved_by_division, settlement_status, settled_by, settled_at, rejection_reason, created_at
`

type ApprovePaymentParams struct {
	SettledBy pgtype.UUID `json:"settled_by"`
	ID        uuid.UUID   `json:"id"`
}

// BP.TTQT duyệt thanh toán
func (q *Queries) ApprovePayment(ctx context.Context, arg ApprovePaymentParams) (InternationalPayment, error) {
	row := q.db.QueryRow(ctx, approvePayment, arg.SettledBy, arg.ID)
	var i InternationalPayment
	err := row.Scan(
		&i.ID,
		&i.SourceModule,
		&i.SourceDealID,
		&i.SourceLegNumber,
		&i.TicketDisplay,
		&i.CounterpartyID,
		&i.DebitAccount,
		&i.BicCode,
		&i.CurrencyCode,
		&i.Amount,
		&i.TransferDate,
		&i.CounterpartySsi,
		&i.OriginalTradeDate,
		&i.ApprovedByDivision,
		&i.SettlementStatus,
		&i.SettledBy,
		&i.SettledAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const createInternationalPayment = `-- name: CreateInternationalPayment :one

INSERT INTO international_payments (
    id, source_module, source_deal_id, source_leg_number,
    ticket_display, counterparty_id, debit_account, bic_code,
    currency_code, amount, transfer_date, counterparty_ssi,
    original_trade_date, settlement_status, created_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    'PENDING', NOW()
)
RETURNING id, source_module, source_deal_id, source_leg_number, ticket_display, counterparty_id, debit_account, bic_code, currency_code, amount, transfer_date, counterparty_ssi, original_trade_date, approved_by_division, settlement_status, settled_by, settled_at, rejection_reason, created_at
`

type CreateInternationalPaymentParams struct {
	SourceModule      string         `json:"source_module"`
	SourceDealID      uuid.UUID      `json:"source_deal_id"`
	SourceLegNumber   *int16         `json:"source_leg_number"`
	TicketDisplay     string         `json:"ticket_display"`
	CounterpartyID    uuid.UUID      `json:"counterparty_id"`
	DebitAccount      string         `json:"debit_account"`
	BicCode           *string        `json:"bic_code"`
	CurrencyCode      string         `json:"currency_code"`
	Amount            pgtype.Numeric `json:"amount"`
	TransferDate      pgtype.Date    `json:"transfer_date"`
	CounterpartySsi   string         `json:"counterparty_ssi"`
	OriginalTradeDate pgtype.Date    `json:"original_trade_date"`
}

// ============================================================================
// international_payments.sql — Queries for international_payments table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateInternationalPayment(ctx context.Context, arg CreateInternationalPaymentParams) (InternationalPayment, error) {
	row := q.db.QueryRow(ctx, createInternationalPayment,
		arg.SourceModule,
		arg.SourceDealID,
		arg.SourceLegNumber,
		arg.TicketDisplay,
		arg.CounterpartyID,
		arg.DebitAccount,
		arg.BicCode,
		arg.CurrencyCode,
		arg.Amount,
		arg.TransferDate,
		arg.CounterpartySsi,
		arg.OriginalTradeDate,
	)
	var i InternationalPayment
	err := row.Scan(
		&i.ID,
		&i.SourceModule,
		&i.SourceDealID,
		&i.SourceLegNumber,
		&i.TicketDisplay,
		&i.CounterpartyID,
		&i.DebitAccount,
		&i.BicCode,
		&i.CurrencyCode,
		&i.Amount,
		&i.TransferDate,
		&i.CounterpartySsi,
		&i.OriginalTradeDate,
		&i.ApprovedByDivision,
		&i.SettlementStatus,
		&i.SettledBy,
		&i.SettledAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getInternationalPaymentByID = `-- name: GetInternationalPaymentByID :one
SELECT id, source_module, source_deal_id, source_leg_number, ticket_display, counterparty_id, debit_account, bic_code, currency_code, amount, transfer_date, counterparty_ssi, original_trade_date, approved_by_division, settlement_status, settled_by, settled_at, rejection_reason, created_at FROM international_payments WHERE id = $1
`

func (q *Queries) GetInternationalPaymentByID(ctx context.Context, id uuid.UUID) (InternationalPayment, error) {
	row := q.db.QueryRow(ctx, getInternationalPaymentByID, id)
	var i InternationalPayment
	err := row.Scan(
		&i.ID,
		&i.SourceModule,
		&i.SourceDealID,
		&i.SourceLegNumber,
		&i.TicketDisplay,
		&i.CounterpartyID,
		&i.DebitAccount,
		&i.BicCode,
		&i.CurrencyCode,
		&i.Amount,
		&i.TransferDate,
		&i.CounterpartySsi,
		&i.OriginalTradeDate,
		&i.ApprovedByDivision,
		&i.SettlementStatus,
		&i.SettledBy,
		&i.SettledAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getInternationalPaymentBySourceDeal = `-- name: GetInternationalPaymentBySourceDeal :one
SELECT id, source_module, source_deal_id, source_leg_number, ticket_display, counterparty_id, debit_account, bic_code, currency_code, amount, transfer_date, counterparty_ssi, original_trade_date, approved_by_division, settlement_status, settled_by, settled_at, rejection_reason, created_at FROM international_payments
WHERE source_module = $1
  AND source_deal_id = $2
  AND (source_leg_number = $3 OR $3 IS NULL)
`

type GetInternationalPaymentBySourceDealParams struct {
	SourceModule    string    `json:"source_module"`
	SourceDealID    uuid.UUID `json:"source_deal_id"`
	SourceLegNumber *int16    `json:"source_leg_number"`
}

// Tìm payment theo deal gốc (và leg nếu là swap)
func (q *Queries) GetInternationalPaymentBySourceDeal(ctx context.Context, arg GetInternationalPaymentBySourceDealParams) (InternationalPayment, error) {
	row := q.db.QueryRow(ctx, getInternationalPaymentBySourceDeal, arg.SourceModule, arg.SourceDealID, arg.SourceLegNumber)
	var i InternationalPayment
	err := row.Scan(
		&i.ID,
		&i.SourceModule,
		&i.SourceDealID,
		&i.SourceLegNumber,
		&i.TicketDisplay,
		&i.CounterpartyID,
		&i.DebitAccount,
		&i.BicCode,
		&i.CurrencyCode,
		&i.Amount,
		&i.TransferDate,
		&i.CounterpartySsi,
		&i.OriginalTradeDate,
		&i.ApprovedByDivision,
		&i.SettlementStatus,
		&i.SettledBy,
		&i.SettledAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsByDateRange = `-- name: ListPaymentsByDateRange :many
SELECT
    ip.id, ip.source_module, ip.source_deal_id, ip.source_leg_number, ip.ticket_display, ip.counterparty_id, ip.debit_account, ip.bic_code, ip.currency_code, ip.amount, ip.transfer_date, ip.counterparty_ssi, ip.original_trade_date, ip.approved_by_division, ip.settlement_status, ip.settled_by, ip.settled_at, ip.rejection_reason, ip.created_at,
    c.full_name AS counterparty_name
FROM international_payments ip
JOIN counterparties c ON c.id = ip.counterparty_id
WHERE ip.transfer_date BETWEEN $1 AND $2
ORDER BY ip.transfer_date DESC, ip.created_at DESC
LIMIT $3 OFFSET $4
`

type ListPaymentsByDateRangeParams struct {
	TransferDate   pgtype.Date `json:"transfer_date"`
	TransferDate_2 pgtype.Date `json:"transfer_date_2"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type ListPaymentsByDateRangeRow struct {
	ID                 uuid.UUID          `json:"id"`
	SourceModule       string             `json:"source_module"`
	SourceDealID       uuid.UUID          `json:"source_deal_id"`
	SourceLegNumber    *int16             `json:"source_leg_number"`
	TicketDisplay      string             `json:"ticket_display"`
	CounterpartyID     uuid.UUID          `json:"counterparty_id"`
	DebitAccount       string             `json:"debit_account"`
	BicCode            *string            `json:"bic_code"`
	CurrencyCode       string             `json:"currency_code"`
	Amount             pgtype.Numeric     `json:"amount"`
	TransferDate       pgtype.Date        `json:"transfer_date"`
	CounterpartySsi    string             `json:"counterparty_ssi"`
	OriginalTradeDate  pgtype.Date        `json:"original_trade_date"`
	ApprovedByDivision *string            `json:"approved_by_division"`
	SettlementStatus   string             `json:"settlement_status"`
	SettledBy          pgtype.UUID        `json:"settled_by"`
	SettledAt          pgtype.Timestamptz `json:"settled_at"`
	RejectionReason    *string            `json:"rejection_reason"`
	CreatedAt          time.Time          `json:"created_at"`
	CounterpartyName   string             `json:"counterparty_name"`
}

// Tìm kiếm payment theo khoảng ngày
func (q *Queries) ListPaymentsByDateRange(ctx context.Context, arg ListPaymentsByDateRangeParams) ([]ListPaymentsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByDateRange,
		arg.TransferDate,
		arg.TransferDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsByDateRangeRow{}
	for rows.Next() {
		var i ListPaymentsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceModule,
			&i.SourceDealID,
			&i.SourceLegNumber,
			&i.TicketDisplay,
			&i.CounterpartyID,
			&i.DebitAccount,
			&i.BicCode,
			&i.CurrencyCode,
			&i.Amount,
			&i.TransferDate,
			&i.CounterpartySsi,
			&i.OriginalTradeDate,
			&i.ApprovedByDivision,
			&i.SettlementStatus,
			&i.SettledBy,
			&i.SettledAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.CounterpartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByStatus = `-- name: ListPaymentsByStatus :many
SELECT
    ip.id, ip.source_module, ip.source_deal_id, ip.source_leg_number, ip.ticket_display, ip.counterparty_id, ip.debit_account, ip.bic_code, ip.currency_code, ip.amount, ip.transfer_date, ip.counterparty_ssi, ip.original_trade_date, ip.approved_by_division, ip.settlement_status, ip.settled_by, ip.settled_at, ip.rejection_reason, ip.created_at,
    c.full_name AS counterparty_name
FROM international_payments ip
JOIN counterparties c ON c.id = ip.counterparty_id
WHERE ip.settlement_status = $1
ORDER BY ip.transfer_date DESC, ip.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByStatusParams struct {
	SettlementStatus string `json:"settlement_status"`
	Limit            int32  `json:"limit"`
	Offset           int32  `json:"offset"`
}

type ListPaymentsByStatusRow struct {
	ID                 uuid.UUID          `json:"id"`
	SourceModule       string             `json:"source_module"`
	SourceDealID       uuid.UUID          `json:"source_deal_id"`
	SourceLegNumber    *int16             `json:"source_leg_number"`
	TicketDisplay      string             `json:"ticket_display"`
	CounterpartyID     uuid.UUID          `json:"counterparty_id"`
	DebitAccount       string             `json:"debit_account"`
	BicCode            *string            `json:"bic_code"`
	CurrencyCode       string             `json:"currency_code"`
	Amount             pgtype.Numeric     `json:"amount"`
	TransferDate       pgtype.Date        `json:"transfer_date"`
	CounterpartySsi    string             `json:"counterparty_ssi"`
	OriginalTradeDate  pgtype.Date        `json:"original_trade_date"`
	ApprovedByDivision *string            `json:"approved_by_division"`
	SettlementStatus   string             `json:"settlement_status"`
	SettledBy          pgtype.UUID        `json:"settled_by"`
	SettledAt          pgtype.Timestamptz `json:"settled_at"`
	RejectionReason    *string            `json:"rejection_reason"`
	CreatedAt          time.Time          `json:"created_at"`
	CounterpartyName   string             `json:"counterparty_name"`
}

func (q *Queries) ListPaymentsByStatus(ctx context.Context, arg ListPaymentsByStatusParams) ([]ListPaymentsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByStatus, arg.SettlementStatus, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsByStatusRow{}
	for rows.Next() {
		var i ListPaymentsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceModule,
			&i.SourceDealID,
			&i.SourceLegNumber,
			&i.TicketDisplay,
			&i.CounterpartyID,
			&i.DebitAccount,
			&i.BicCode,
			&i.CurrencyCode,
			&i.Amount,
			&i.TransferDate,
			&i.CounterpartySsi,
			&i.OriginalTradeDate,
			&i.ApprovedByDivision,
			&i.SettlementStatus,
			&i.SettledBy,
			&i.SettledAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.CounterpartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPaymentsToday = `-- name: ListPendingPaymentsToday :many
SELECT
    ip.id, ip.source_module, ip.source_deal_id, ip.source_leg_number, ip.ticket_display, ip.counterparty_id, ip.debit_account, ip.bic_code, ip.currency_code, ip.amount, ip.transfer_date, ip.counterparty_ssi, ip.original_trade_date, ip.approved_by_division, ip.settlement_status, ip.settled_by, ip.settled_at, ip.rejection_reason, ip.created_at,
    c.full_name AS counterparty_name
FROM international_payments ip
JOIN counterparties c ON c.id = ip.counterparty_id
WHERE ip.transfer_date = CURRENT_DATE
  AND ip.settlement_status = 'PENDING'
ORDER BY ip.created_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingPaymentsTodayParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPendingPaymentsTodayRow struct {
	ID                 uuid.UUID          `json:"id"`
	SourceModule       string             `json:"source_module"`
	SourceDealID       uuid.UUID          `json:"source_deal_id"`
	SourceLegNumber    *int16             `json:"source_leg_number"`
	TicketDisplay      string             `json:"ticket_display"`
	CounterpartyID     uuid.UUID          `json:"counterparty_id"`
	DebitAccount       string             `json:"debit_account"`
	BicCode            *string            `json:"bic_code"`
	CurrencyCode       string             `json:"currency_code"`
	Amount             pgtype.Numeric     `json:"amount"`
	TransferDate       pgtype.Date        `json:"transfer_date"`
	CounterpartySsi    string             `json:"counterparty_ssi"`
	OriginalTradeDate  pgtype.Date        `json:"original_trade_date"`
	ApprovedByDivision *string            `json:"approved_by_division"`
	SettlementStatus   string             `json:"settlement_status"`
	SettledBy          pgtype.UUID        `json:"settled_by"`
	SettledAt          pgtype.Timestamptz `json:"settled_at"`
	RejectionReason    *string            `json:"rejection_reason"`
	CreatedAt          time.Time          `json:"created_at"`
	CounterpartyName   string             `json:"counterparty_name"`
}

// Lấy danh sách payment cần xử lý hôm nay
func (q *Queries) ListPendingPaymentsToday(ctx context.Context, arg ListPendingPaymentsTodayParams) ([]ListPendingPaymentsTodayRow, error) {
	rows, err := q.db.Query(ctx, listPendingPaymentsToday, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingPaymentsTodayRow{}
	for rows.Next() {
		var i ListPendingPaymentsTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceModule,
			&i.SourceDealID,
			&i.SourceLegNumber,
			&i.TicketDisplay,
			&i.CounterpartyID,
			&i.DebitAccount,
			&i.BicCode,
			&i.CurrencyCode,
			&i.Amount,
			&i.TransferDate,
			&i.CounterpartySsi,
			&i.OriginalTradeDate,
			&i.ApprovedByDivision,
			&i.SettlementStatus,
			&i.SettledBy,
			&i.SettledAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.CounterpartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectPayment = `-- name: RejectPayment :one
UPDATE international_payments SET
    settlement_status = 'REJECTED',
    rejection_reason = $3,
    settled_by = $1,
    settled_at = NOW()
WHERE id = $2 AND settlement_status = 'PENDING'
RETURNING id, source_module, source_deal_id, source_leg_number, ticket_display, counterparty_id, debit_account, bic_code, currency_code, amount, transfer_date, counterparty_ssi, original_trade_date, approved_by_division, settlement_status, settled_by, settled_at, rejection_reason, created_at
`

type RejectPaymentParams struct {
	SettledBy       pgtype.UUID `json:"settled_by"`
	ID              uuid.UUID   `json:"id"`
	RejectionReason *string     `json:"rejection_reason"`
}

// BP.TTQT từ chối thanh toán
func (q *Queries) RejectPayment(ctx context.Context, arg RejectPaymentParams) (InternationalPayment, error) {
	row := q.db.QueryRow(ctx, rejectPayment, arg.SettledBy, arg.ID, arg.RejectionReason)
	var i InternationalPayment
	err := row.Scan(
		&i.ID,
		&i.SourceModule,
		&i.SourceDealID,
		&i.SourceLegNumber,
		&i.TicketDisplay,
		&i.CounterpartyID,
		&i.DebitAccount,
		&i.BicCode,
		&i.CurrencyCode,
		&i.Amount,
		&i.TransferDate,
		&i.CounterpartySsi,
		&i.OriginalTradeDate,
		&i.ApprovedByDivision,
		&i.SettlementStatus,
		&i.SettledBy,
		&i.SettledAt,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}
