// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: limit_snapshots.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLimitSnapshot = `-- name: CreateLimitSnapshot :one

INSERT INTO limit_utilization_snapshots (
    id, counterparty_id, snapshot_date, limit_type,
    limit_granted, utilized_opening, utilized_intraday, utilized_total,
    remaining, fx_rate_applied, breakdown_detail,
    created_at, created_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    NOW(), $11
)
RETURNING id, counterparty_id, snapshot_date, limit_type, limit_granted, utilized_opening, utilized_intraday, utilized_total, remaining, fx_rate_applied, breakdown_detail, created_at, created_by
`

type CreateLimitSnapshotParams struct {
	CounterpartyID   uuid.UUID      `json:"counterparty_id"`
	SnapshotDate     pgtype.Date    `json:"snapshot_date"`
	LimitType        string         `json:"limit_type"`
	LimitGranted     pgtype.Numeric `json:"limit_granted"`
	UtilizedOpening  pgtype.Numeric `json:"utilized_opening"`
	UtilizedIntraday pgtype.Numeric `json:"utilized_intraday"`
	UtilizedTotal    pgtype.Numeric `json:"utilized_total"`
	Remaining        pgtype.Numeric `json:"remaining"`
	FxRateApplied    pgtype.Numeric `json:"fx_rate_applied"`
	BreakdownDetail  []byte         `json:"breakdown_detail"`
	CreatedBy        pgtype.UUID    `json:"created_by"`
}

// ============================================================================
// limit_snapshots.sql — Queries for limit_utilization_snapshots table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateLimitSnapshot(ctx context.Context, arg CreateLimitSnapshotParams) (LimitUtilizationSnapshot, error) {
	row := q.db.QueryRow(ctx, createLimitSnapshot,
		arg.CounterpartyID,
		arg.SnapshotDate,
		arg.LimitType,
		arg.LimitGranted,
		arg.UtilizedOpening,
		arg.UtilizedIntraday,
		arg.UtilizedTotal,
		arg.Remaining,
		arg.FxRateApplied,
		arg.BreakdownDetail,
		arg.CreatedBy,
	)
	var i LimitUtilizationSnapshot
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.SnapshotDate,
		&i.LimitType,
		&i.LimitGranted,
		&i.UtilizedOpening,
		&i.UtilizedIntraday,
		&i.UtilizedTotal,
		&i.Remaining,
		&i.FxRateApplied,
		&i.BreakdownDetail,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLatestSnapshotByCounterparty = `-- name: GetLatestSnapshotByCounterparty :one
SELECT id, counterparty_id, snapshot_date, limit_type, limit_granted, utilized_opening, utilized_intraday, utilized_total, remaining, fx_rate_applied, breakdown_detail, created_at, created_by FROM limit_utilization_snapshots
WHERE counterparty_id = $1 AND limit_type = $2
ORDER BY snapshot_date DESC
LIMIT 1
`

type GetLatestSnapshotByCounterpartyParams struct {
	CounterpartyID uuid.UUID `json:"counterparty_id"`
	LimitType      string    `json:"limit_type"`
}

// Lấy snapshot mới nhất của đối tác
func (q *Queries) GetLatestSnapshotByCounterparty(ctx context.Context, arg GetLatestSnapshotByCounterpartyParams) (LimitUtilizationSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshotByCounterparty, arg.CounterpartyID, arg.LimitType)
	var i LimitUtilizationSnapshot
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.SnapshotDate,
		&i.LimitType,
		&i.LimitGranted,
		&i.UtilizedOpening,
		&i.UtilizedIntraday,
		&i.UtilizedTotal,
		&i.Remaining,
		&i.FxRateApplied,
		&i.BreakdownDetail,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getSnapshotByCounterpartyAndDate = `-- name: GetSnapshotByCounterpartyAndDate :one
SELECT id, counterparty_id, snapshot_date, limit_type, limit_granted, utilized_opening, utilized_intraday, utilized_total, remaining, fx_rate_applied, breakdown_detail, created_at, created_by FROM limit_utilization_snapshots
WHERE counterparty_id = $1
  AND limit_type = $2
  AND snapshot_date = $3
`

type GetSnapshotByCounterpartyAndDateParams struct {
	CounterpartyID uuid.UUID   `json:"counterparty_id"`
	LimitType      string      `json:"limit_type"`
	SnapshotDate   pgtype.Date `json:"snapshot_date"`
}

func (q *Queries) GetSnapshotByCounterpartyAndDate(ctx context.Context, arg GetSnapshotByCounterpartyAndDateParams) (LimitUtilizationSnapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshotByCounterpartyAndDate, arg.CounterpartyID, arg.LimitType, arg.SnapshotDate)
	var i LimitUtilizationSnapshot
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.SnapshotDate,
		&i.LimitType,
		&i.LimitGranted,
		&i.UtilizedOpening,
		&i.UtilizedIntraday,
		&i.UtilizedTotal,
		&i.Remaining,
		&i.FxRateApplied,
		&i.BreakdownDetail,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listSnapshotsByCounterparty = `-- name: ListSnapshotsByCounterparty :many
SELECT id, counterparty_id, snapshot_date, limit_type, limit_granted, utilized_opening, utilized_intraday, utilized_total, remaining, fx_rate_applied, breakdown_detail, created_at, created_by FROM limit_utilization_snapshots
WHERE counterparty_id = $1
ORDER BY snapshot_date DESC
LIMIT $2 OFFSET $3
`

type ListSnapshotsByCounterpartyParams struct {
	CounterpartyID uuid.UUID `json:"counterparty_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

// Lấy lịch sử snapshot của đối tác
func (q *Queries) ListSnapshotsByCounterparty(ctx context.Context, arg ListSnapshotsByCounterpartyParams) ([]LimitUtilizationSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsByCounterparty, arg.CounterpartyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LimitUtilizationSnapshot{}
	for rows.Next() {
		var i LimitUtilizationSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CounterpartyID,
			&i.SnapshotDate,
			&i.LimitType,
			&i.LimitGranted,
			&i.UtilizedOpening,
			&i.UtilizedIntraday,
			&i.UtilizedTotal,
			&i.Remaining,
			&i.FxRateApplied,
			&i.BreakdownDetail,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLimitSnapshot = `-- name: UpsertLimitSnapshot :one
INSERT INTO limit_utilization_snapshots (
    id, counterparty_id, snapshot_date, limit_type,
    limit_granted, utilized_opening, utilized_intraday, utilized_total,
    remaining, fx_rate_applied, breakdown_detail,
    created_at, created_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    NOW(), $11
)
ON CONFLICT (counterparty_id, snapshot_date, limit_type) DO UPDATE SET
    limit_granted = EXCLUDED.limit_granted,
    utilized_opening = EXCLUDED.utilized_opening,
    utilized_intraday = EXCLUDED.utilized_intraday,
    utilized_total = EXCLUDED.utilized_total,
    remaining = EXCLUDED.remaining,
    fx_rate_applied = EXCLUDED.fx_rate_applied,
    breakdown_detail = EXCLUDED.breakdown_detail,
    created_by = EXCLUDED.created_by
RETURNING id, counterparty_id, snapshot_date, limit_type, limit_granted, utilized_opening, utilized_intraday, utilized_total, remaining, fx_rate_applied, breakdown_detail, created_at, created_by
`

type UpsertLimitSnapshotParams struct {
	CounterpartyID   uuid.UUID      `json:"counterparty_id"`
	SnapshotDate     pgtype.Date    `json:"snapshot_date"`
	LimitType        string         `json:"limit_type"`
	LimitGranted     pgtype.Numeric `json:"limit_granted"`
	UtilizedOpening  pgtype.Numeric `json:"utilized_opening"`
	UtilizedIntraday pgtype.Numeric `json:"utilized_intraday"`
	UtilizedTotal    pgtype.Numeric `json:"utilized_total"`
	Remaining        pgtype.Numeric `json:"remaining"`
	FxRateApplied    pgtype.Numeric `json:"fx_rate_applied"`
	BreakdownDetail  []byte         `json:"breakdown_detail"`
	CreatedBy        pgtype.UUID    `json:"created_by"`
}

// Tạo hoặc cập nhật snapshot cho ngày
func (q *Queries) UpsertLimitSnapshot(ctx context.Context, arg UpsertLimitSnapshotParams) (LimitUtilizationSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertLimitSnapshot,
		arg.CounterpartyID,
		arg.SnapshotDate,
		arg.LimitType,
		arg.LimitGranted,
		arg.UtilizedOpening,
		arg.UtilizedIntraday,
		arg.UtilizedTotal,
		arg.Remaining,
		arg.FxRateApplied,
		arg.BreakdownDetail,
		arg.CreatedBy,
	)
	var i LimitUtilizationSnapshot
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.SnapshotDate,
		&i.LimitType,
		&i.LimitGranted,
		&i.UtilizedOpening,
		&i.UtilizedIntraday,
		&i.UtilizedTotal,
		&i.Remaining,
		&i.FxRateApplied,
		&i.BreakdownDetail,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
