// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: limit_approvals.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLimitApproval = `-- name: CreateLimitApproval :one

INSERT INTO limit_approval_records (
    id, deal_module, deal_id, counterparty_id, limit_type,
    deal_amount_vnd, limit_snapshot, approval_status,
    created_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, 'PENDING', NOW()
)
RETURNING id, deal_module, deal_id, counterparty_id, limit_type, deal_amount_vnd, limit_snapshot, risk_officer_approved_by, risk_officer_approved_at, risk_head_approved_by, risk_head_approved_at, approval_status, rejection_reason, created_at
`

type CreateLimitApprovalParams struct {
	DealModule     string          `json:"deal_module"`
	DealID         uuid.UUID       `json:"deal_id"`
	CounterpartyID uuid.UUID       `json:"counterparty_id"`
	LimitType      string          `json:"limit_type"`
	DealAmountVnd  pgtype.Numeric  `json:"deal_amount_vnd"`
	LimitSnapshot  json.RawMessage `json:"limit_snapshot"`
}

// ============================================================================
// limit_approvals.sql — Queries for limit_approval_records table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateLimitApproval(ctx context.Context, arg CreateLimitApprovalParams) (LimitApprovalRecord, error) {
	row := q.db.QueryRow(ctx, createLimitApproval,
		arg.DealModule,
		arg.DealID,
		arg.CounterpartyID,
		arg.LimitType,
		arg.DealAmountVnd,
		arg.LimitSnapshot,
	)
	var i LimitApprovalRecord
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.DealID,
		&i.CounterpartyID,
		&i.LimitType,
		&i.DealAmountVnd,
		&i.LimitSnapshot,
		&i.RiskOfficerApprovedBy,
		&i.RiskOfficerApprovedAt,
		&i.RiskHeadApprovedBy,
		&i.RiskHeadApprovedAt,
		&i.ApprovalStatus,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getLimitApprovalByDealID = `-- name: GetLimitApprovalByDealID :one
SELECT id, deal_module, deal_id, counterparty_id, limit_type, deal_amount_vnd, limit_snapshot, risk_officer_approved_by, risk_officer_approved_at, risk_head_approved_by, risk_head_approved_at, approval_status, rejection_reason, created_at FROM limit_approval_records
WHERE deal_module = $1 AND deal_id = $2
`

type GetLimitApprovalByDealIDParams struct {
	DealModule string    `json:"deal_module"`
	DealID     uuid.UUID `json:"deal_id"`
}

// Lấy record phê duyệt hạn mức theo deal
func (q *Queries) GetLimitApprovalByDealID(ctx context.Context, arg GetLimitApprovalByDealIDParams) (LimitApprovalRecord, error) {
	row := q.db.QueryRow(ctx, getLimitApprovalByDealID, arg.DealModule, arg.DealID)
	var i LimitApprovalRecord
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.DealID,
		&i.CounterpartyID,
		&i.LimitType,
		&i.DealAmountVnd,
		&i.LimitSnapshot,
		&i.RiskOfficerApprovedBy,
		&i.RiskOfficerApprovedAt,
		&i.RiskHeadApprovedBy,
		&i.RiskHeadApprovedAt,
		&i.ApprovalStatus,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getLimitApprovalByID = `-- name: GetLimitApprovalByID :one
SELECT id, deal_module, deal_id, counterparty_id, limit_type, deal_amount_vnd, limit_snapshot, risk_officer_approved_by, risk_officer_approved_at, risk_head_approved_by, risk_head_approved_at, approval_status, rejection_reason, created_at FROM limit_approval_records WHERE id = $1
`

func (q *Queries) GetLimitApprovalByID(ctx context.Context, id uuid.UUID) (LimitApprovalRecord, error) {
	row := q.db.QueryRow(ctx, getLimitApprovalByID, id)
	var i LimitApprovalRecord
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.DealID,
		&i.CounterpartyID,
		&i.LimitType,
		&i.DealAmountVnd,
		&i.LimitSnapshot,
		&i.RiskOfficerApprovedBy,
		&i.RiskOfficerApprovedAt,
		&i.RiskHeadApprovedBy,
		&i.RiskHeadApprovedAt,
		&i.ApprovalStatus,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingLimitApprovals = `-- name: ListPendingLimitApprovals :many
SELECT
    lar.id, lar.deal_module, lar.deal_id, lar.counterparty_id, lar.limit_type, lar.deal_amount_vnd, lar.limit_snapshot, lar.risk_officer_approved_by, lar.risk_officer_approved_at, lar.risk_head_approved_by, lar.risk_head_approved_at, lar.approval_status, lar.rejection_reason, lar.created_at,
    u.full_name AS deal_creator,
    CASE lar.deal_module
        WHEN 'MM' THEN mmd.deal_number
        WHEN 'FX' THEN fxd.deal_number
    END AS deal_number
FROM limit_approval_records lar
JOIN users u ON
    CASE lar.deal_module
        WHEN 'MM' THEN (SELECT created_by FROM mm_interbank_deals WHERE id = lar.deal_id) = u.id
        WHEN 'FX' THEN (SELECT created_by FROM fx_deals WHERE id = lar.deal_id) = u.id
    END
LEFT JOIN mm_interbank_deals mmd ON lar.deal_module = 'MM' AND lar.deal_id = mmd.id
LEFT JOIN fx_deals fxd ON lar.deal_module = 'FX' AND lar.deal_id = fxd.id
WHERE lar.approval_status = 'PENDING'
ORDER BY lar.created_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingLimitApprovalsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPendingLimitApprovalsRow struct {
	ID                    uuid.UUID          `json:"id"`
	DealModule            string             `json:"deal_module"`
	DealID                uuid.UUID          `json:"deal_id"`
	CounterpartyID        uuid.UUID          `json:"counterparty_id"`
	LimitType             string             `json:"limit_type"`
	DealAmountVnd         pgtype.Numeric     `json:"deal_amount_vnd"`
	LimitSnapshot         json.RawMessage    `json:"limit_snapshot"`
	RiskOfficerApprovedBy pgtype.UUID        `json:"risk_officer_approved_by"`
	RiskOfficerApprovedAt pgtype.Timestamptz `json:"risk_officer_approved_at"`
	RiskHeadApprovedBy    pgtype.UUID        `json:"risk_head_approved_by"`
	RiskHeadApprovedAt    pgtype.Timestamptz `json:"risk_head_approved_at"`
	ApprovalStatus        string             `json:"approval_status"`
	RejectionReason       *string            `json:"rejection_reason"`
	CreatedAt             time.Time          `json:"created_at"`
	DealCreator           string             `json:"deal_creator"`
	DealNumber            interface{}        `json:"deal_number"`
}

// Lấy danh sách các deal chờ QLRR duyệt hạn mức
func (q *Queries) ListPendingLimitApprovals(ctx context.Context, arg ListPendingLimitApprovalsParams) ([]ListPendingLimitApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listPendingLimitApprovals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingLimitApprovalsRow{}
	for rows.Next() {
		var i ListPendingLimitApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.DealModule,
			&i.DealID,
			&i.CounterpartyID,
			&i.LimitType,
			&i.DealAmountVnd,
			&i.LimitSnapshot,
			&i.RiskOfficerApprovedBy,
			&i.RiskOfficerApprovedAt,
			&i.RiskHeadApprovedBy,
			&i.RiskHeadApprovedAt,
			&i.ApprovalStatus,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.DealCreator,
			&i.DealNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLimitApprovalStatus = `-- name: UpdateLimitApprovalStatus :one
UPDATE limit_approval_records SET
    risk_officer_approved_by = CASE
        WHEN $3::TEXT = 'RISK_OFFICER' THEN $4::UUID
        ELSE risk_officer_approved_by
    END,
    risk_officer_approved_at = CASE
        WHEN $3::TEXT = 'RISK_OFFICER' THEN NOW()
        ELSE risk_officer_approved_at
    END,
    risk_head_approved_by = CASE
        WHEN $3::TEXT = 'RISK_HEAD' THEN $4::UUID
        ELSE risk_head_approved_by
    END,
    risk_head_approved_at = CASE
        WHEN $3::TEXT = 'RISK_HEAD' THEN NOW()
        ELSE risk_head_approved_at
    END,
    approval_status = $1,
    rejection_reason = COALESCE($5, rejection_reason)
WHERE id = $2
RETURNING id, deal_module, deal_id, counterparty_id, limit_type, deal_amount_vnd, limit_snapshot, risk_officer_approved_by, risk_officer_approved_at, risk_head_approved_by, risk_head_approved_at, approval_status, rejection_reason, created_at
`

type UpdateLimitApprovalStatusParams struct {
	ApprovalStatus  string    `json:"approval_status"`
	ID              uuid.UUID `json:"id"`
	ApprovalLevel   string    `json:"approval_level"`
	UserID          uuid.UUID `json:"user_id"`
	RejectionReason *string   `json:"rejection_reason"`
}

// Cập nhật trạng thái phê duyệt từ QLRR
func (q *Queries) UpdateLimitApprovalStatus(ctx context.Context, arg UpdateLimitApprovalStatusParams) (LimitApprovalRecord, error) {
	row := q.db.QueryRow(ctx, updateLimitApprovalStatus,
		arg.ApprovalStatus,
		arg.ID,
		arg.ApprovalLevel,
		arg.UserID,
		arg.RejectionReason,
	)
	var i LimitApprovalRecord
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.DealID,
		&i.CounterpartyID,
		&i.LimitType,
		&i.DealAmountVnd,
		&i.LimitSnapshot,
		&i.RiskOfficerApprovedBy,
		&i.RiskOfficerApprovedAt,
		&i.RiskHeadApprovedBy,
		&i.RiskHeadApprovedAt,
		&i.ApprovalStatus,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}
