// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mm_interbank_deals.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMMInterbankDeals = `-- name: CountMMInterbankDeals :one
SELECT COUNT(*) FROM mm_interbank_deals WHERE deleted_at IS NULL
`

func (q *Queries) CountMMInterbankDeals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMMInterbankDeals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMMInterbankDeal = `-- name: CreateMMInterbankDeal :one

INSERT INTO mm_interbank_deals (
    id, deal_number, ticket_number, counterparty_id, branch_id,
    currency_code, internal_ssi_id, counterparty_ssi_id,
    direction, principal_amount, interest_rate, day_count_convention,
    trade_date, effective_date, tenor_days, maturity_date,
    interest_amount, maturity_amount,
    has_collateral, collateral_currency, collateral_description,
    requires_international_settlement,
    status, note, cloned_from_id,
    created_at, created_by, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17, $18, $19, $20, $21,
    'OPEN', $22, $23,
    NOW(), $24, NOW(), $24
)
RETURNING id, deal_number, ticket_number, counterparty_id, branch_id, currency_code, internal_ssi_id, counterparty_ssi_id, direction, principal_amount, interest_rate, day_count_convention, trade_date, effective_date, tenor_days, maturity_date, interest_amount, maturity_amount, has_collateral, collateral_currency, collateral_description, requires_international_settlement, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type CreateMMInterbankDealParams struct {
	DealNumber                      string         `json:"deal_number"`
	TicketNumber                    *string        `json:"ticket_number"`
	CounterpartyID                  uuid.UUID      `json:"counterparty_id"`
	BranchID                        uuid.UUID      `json:"branch_id"`
	CurrencyCode                    string         `json:"currency_code"`
	InternalSsiID                   uuid.UUID      `json:"internal_ssi_id"`
	CounterpartySsiID               uuid.UUID      `json:"counterparty_ssi_id"`
	Direction                       string         `json:"direction"`
	PrincipalAmount                 pgtype.Numeric `json:"principal_amount"`
	InterestRate                    pgtype.Numeric `json:"interest_rate"`
	DayCountConvention              string         `json:"day_count_convention"`
	TradeDate                       pgtype.Date    `json:"trade_date"`
	EffectiveDate                   pgtype.Date    `json:"effective_date"`
	TenorDays                       int32          `json:"tenor_days"`
	MaturityDate                    pgtype.Date    `json:"maturity_date"`
	InterestAmount                  pgtype.Numeric `json:"interest_amount"`
	MaturityAmount                  pgtype.Numeric `json:"maturity_amount"`
	HasCollateral                   bool           `json:"has_collateral"`
	CollateralCurrency              *string        `json:"collateral_currency"`
	CollateralDescription           *string        `json:"collateral_description"`
	RequiresInternationalSettlement bool           `json:"requires_international_settlement"`
	Note                            *string        `json:"note"`
	ClonedFromID                    pgtype.UUID    `json:"cloned_from_id"`
	CreatedBy                       uuid.UUID      `json:"created_by"`
}

// ============================================================================
// mm_interbank_deals.sql — Queries for mm_interbank_deals table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateMMInterbankDeal(ctx context.Context, arg CreateMMInterbankDealParams) (MmInterbankDeal, error) {
	row := q.db.QueryRow(ctx, createMMInterbankDeal,
		arg.DealNumber,
		arg.TicketNumber,
		arg.CounterpartyID,
		arg.BranchID,
		arg.CurrencyCode,
		arg.InternalSsiID,
		arg.CounterpartySsiID,
		arg.Direction,
		arg.PrincipalAmount,
		arg.InterestRate,
		arg.DayCountConvention,
		arg.TradeDate,
		arg.EffectiveDate,
		arg.TenorDays,
		arg.MaturityDate,
		arg.InterestAmount,
		arg.MaturityAmount,
		arg.HasCollateral,
		arg.CollateralCurrency,
		arg.CollateralDescription,
		arg.RequiresInternationalSettlement,
		arg.Note,
		arg.ClonedFromID,
		arg.CreatedBy,
	)
	var i MmInterbankDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.TicketNumber,
		&i.CounterpartyID,
		&i.BranchID,
		&i.CurrencyCode,
		&i.InternalSsiID,
		&i.CounterpartySsiID,
		&i.Direction,
		&i.PrincipalAmount,
		&i.InterestRate,
		&i.DayCountConvention,
		&i.TradeDate,
		&i.EffectiveDate,
		&i.TenorDays,
		&i.MaturityDate,
		&i.InterestAmount,
		&i.MaturityAmount,
		&i.HasCollateral,
		&i.CollateralCurrency,
		&i.CollateralDescription,
		&i.RequiresInternationalSettlement,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getMMInterbankDealByID = `-- name: GetMMInterbankDealByID :one
SELECT id, deal_number, ticket_number, counterparty_id, branch_id, currency_code, internal_ssi_id, counterparty_ssi_id, direction, principal_amount, interest_rate, day_count_convention, trade_date, effective_date, tenor_days, maturity_date, interest_amount, maturity_amount, has_collateral, collateral_currency, collateral_description, requires_international_settlement, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM mm_interbank_deals
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMMInterbankDealByID(ctx context.Context, id uuid.UUID) (MmInterbankDeal, error) {
	row := q.db.QueryRow(ctx, getMMInterbankDealByID, id)
	var i MmInterbankDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.TicketNumber,
		&i.CounterpartyID,
		&i.BranchID,
		&i.CurrencyCode,
		&i.InternalSsiID,
		&i.CounterpartySsiID,
		&i.Direction,
		&i.PrincipalAmount,
		&i.InterestRate,
		&i.DayCountConvention,
		&i.TradeDate,
		&i.EffectiveDate,
		&i.TenorDays,
		&i.MaturityDate,
		&i.InterestAmount,
		&i.MaturityAmount,
		&i.HasCollateral,
		&i.CollateralCurrency,
		&i.CollateralDescription,
		&i.RequiresInternationalSettlement,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const listMMInterbankDeals = `-- name: ListMMInterbankDeals :many
SELECT id, deal_number, ticket_number, counterparty_id, branch_id, currency_code, internal_ssi_id, counterparty_ssi_id, direction, principal_amount, interest_rate, day_count_convention, trade_date, effective_date, tenor_days, maturity_date, interest_amount, maturity_amount, has_collateral, collateral_currency, collateral_description, requires_international_settlement, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM mm_interbank_deals
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMMInterbankDealsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMMInterbankDeals(ctx context.Context, arg ListMMInterbankDealsParams) ([]MmInterbankDeal, error) {
	rows, err := q.db.Query(ctx, listMMInterbankDeals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MmInterbankDeal{}
	for rows.Next() {
		var i MmInterbankDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.BranchID,
			&i.CurrencyCode,
			&i.InternalSsiID,
			&i.CounterpartySsiID,
			&i.Direction,
			&i.PrincipalAmount,
			&i.InterestRate,
			&i.DayCountConvention,
			&i.TradeDate,
			&i.EffectiveDate,
			&i.TenorDays,
			&i.MaturityDate,
			&i.InterestAmount,
			&i.MaturityAmount,
			&i.HasCollateral,
			&i.CollateralCurrency,
			&i.CollateralDescription,
			&i.RequiresInternationalSettlement,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMMInterbankDealsByMaturityDate = `-- name: ListMMInterbankDealsByMaturityDate :many
SELECT id, deal_number, ticket_number, counterparty_id, branch_id, currency_code, internal_ssi_id, counterparty_ssi_id, direction, principal_amount, interest_rate, day_count_convention, trade_date, effective_date, tenor_days, maturity_date, interest_amount, maturity_amount, has_collateral, collateral_currency, collateral_description, requires_international_settlement, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM mm_interbank_deals
WHERE maturity_date BETWEEN $1 AND $2
  AND deleted_at IS NULL
  AND status NOT IN ('CANCELLED', 'VOIDED_BY_RISK', 'VOIDED_BY_ACCOUNTING', 'VOIDED_BY_SETTLEMENT')
ORDER BY maturity_date ASC
LIMIT $3 OFFSET $4
`

type ListMMInterbankDealsByMaturityDateParams struct {
	MaturityDate   pgtype.Date `json:"maturity_date"`
	MaturityDate_2 pgtype.Date `json:"maturity_date_2"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

// Giám sát đáo hạn — deal sắp đáo hạn trong khoảng ngày
func (q *Queries) ListMMInterbankDealsByMaturityDate(ctx context.Context, arg ListMMInterbankDealsByMaturityDateParams) ([]MmInterbankDeal, error) {
	rows, err := q.db.Query(ctx, listMMInterbankDealsByMaturityDate,
		arg.MaturityDate,
		arg.MaturityDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MmInterbankDeal{}
	for rows.Next() {
		var i MmInterbankDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.BranchID,
			&i.CurrencyCode,
			&i.InternalSsiID,
			&i.CounterpartySsiID,
			&i.Direction,
			&i.PrincipalAmount,
			&i.InterestRate,
			&i.DayCountConvention,
			&i.TradeDate,
			&i.EffectiveDate,
			&i.TenorDays,
			&i.MaturityDate,
			&i.InterestAmount,
			&i.MaturityAmount,
			&i.HasCollateral,
			&i.CollateralCurrency,
			&i.CollateralDescription,
			&i.RequiresInternationalSettlement,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMMInterbankDealsByStatus = `-- name: ListMMInterbankDealsByStatus :many
SELECT id, deal_number, ticket_number, counterparty_id, branch_id, currency_code, internal_ssi_id, counterparty_ssi_id, direction, principal_amount, interest_rate, day_count_convention, trade_date, effective_date, tenor_days, maturity_date, interest_amount, maturity_amount, has_collateral, collateral_currency, collateral_description, requires_international_settlement, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM mm_interbank_deals
WHERE status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMMInterbankDealsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListMMInterbankDealsByStatus(ctx context.Context, arg ListMMInterbankDealsByStatusParams) ([]MmInterbankDeal, error) {
	rows, err := q.db.Query(ctx, listMMInterbankDealsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MmInterbankDeal{}
	for rows.Next() {
		var i MmInterbankDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.BranchID,
			&i.CurrencyCode,
			&i.InternalSsiID,
			&i.CounterpartySsiID,
			&i.Direction,
			&i.PrincipalAmount,
			&i.InterestRate,
			&i.DayCountConvention,
			&i.TradeDate,
			&i.EffectiveDate,
			&i.TenorDays,
			&i.MaturityDate,
			&i.InterestAmount,
			&i.MaturityAmount,
			&i.HasCollateral,
			&i.CollateralCurrency,
			&i.CollateralDescription,
			&i.RequiresInternationalSettlement,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMMInterbankPendingRiskApproval = `-- name: ListMMInterbankPendingRiskApproval :many
SELECT d.id, d.deal_number, d.ticket_number, d.counterparty_id, d.branch_id, d.currency_code, d.internal_ssi_id, d.counterparty_ssi_id, d.direction, d.principal_amount, d.interest_rate, d.day_count_convention, d.trade_date, d.effective_date, d.tenor_days, d.maturity_date, d.interest_amount, d.maturity_amount, d.has_collateral, d.collateral_currency, d.collateral_description, d.requires_international_settlement, d.status, d.note, d.cloned_from_id, d.cancel_reason, d.cancel_requested_by, d.cancel_requested_at, d.created_at, d.created_by, d.updated_at, d.updated_by, d.deleted_at, c.code AS counterparty_code, c.full_name AS counterparty_name
FROM mm_interbank_deals d
JOIN counterparties c ON c.id = d.counterparty_id
WHERE d.status = 'PENDING_RISK_APPROVAL'
  AND d.deleted_at IS NULL
ORDER BY d.trade_date ASC, d.created_at ASC
LIMIT $1 OFFSET $2
`

type ListMMInterbankPendingRiskApprovalParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMMInterbankPendingRiskApprovalRow struct {
	ID                              uuid.UUID          `json:"id"`
	DealNumber                      string             `json:"deal_number"`
	TicketNumber                    *string            `json:"ticket_number"`
	CounterpartyID                  uuid.UUID          `json:"counterparty_id"`
	BranchID                        uuid.UUID          `json:"branch_id"`
	CurrencyCode                    string             `json:"currency_code"`
	InternalSsiID                   uuid.UUID          `json:"internal_ssi_id"`
	CounterpartySsiID               uuid.UUID          `json:"counterparty_ssi_id"`
	Direction                       string             `json:"direction"`
	PrincipalAmount                 pgtype.Numeric     `json:"principal_amount"`
	InterestRate                    pgtype.Numeric     `json:"interest_rate"`
	DayCountConvention              string             `json:"day_count_convention"`
	TradeDate                       pgtype.Date        `json:"trade_date"`
	EffectiveDate                   pgtype.Date        `json:"effective_date"`
	TenorDays                       int32              `json:"tenor_days"`
	MaturityDate                    pgtype.Date        `json:"maturity_date"`
	InterestAmount                  pgtype.Numeric     `json:"interest_amount"`
	MaturityAmount                  pgtype.Numeric     `json:"maturity_amount"`
	HasCollateral                   bool               `json:"has_collateral"`
	CollateralCurrency              *string            `json:"collateral_currency"`
	CollateralDescription           *string            `json:"collateral_description"`
	RequiresInternationalSettlement bool               `json:"requires_international_settlement"`
	Status                          string             `json:"status"`
	Note                            *string            `json:"note"`
	ClonedFromID                    pgtype.UUID        `json:"cloned_from_id"`
	CancelReason                    *string            `json:"cancel_reason"`
	CancelRequestedBy               pgtype.UUID        `json:"cancel_requested_by"`
	CancelRequestedAt               pgtype.Timestamptz `json:"cancel_requested_at"`
	CreatedAt                       time.Time          `json:"created_at"`
	CreatedBy                       uuid.UUID          `json:"created_by"`
	UpdatedAt                       time.Time          `json:"updated_at"`
	UpdatedBy                       uuid.UUID          `json:"updated_by"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
	CounterpartyCode                string             `json:"counterparty_code"`
	CounterpartyName                string             `json:"counterparty_name"`
}

// View cho QLRR: deals chờ phê duyệt rủi ro
func (q *Queries) ListMMInterbankPendingRiskApproval(ctx context.Context, arg ListMMInterbankPendingRiskApprovalParams) ([]ListMMInterbankPendingRiskApprovalRow, error) {
	rows, err := q.db.Query(ctx, listMMInterbankPendingRiskApproval, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMMInterbankPendingRiskApprovalRow{}
	for rows.Next() {
		var i ListMMInterbankPendingRiskApprovalRow
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.BranchID,
			&i.CurrencyCode,
			&i.InternalSsiID,
			&i.CounterpartySsiID,
			&i.Direction,
			&i.PrincipalAmount,
			&i.InterestRate,
			&i.DayCountConvention,
			&i.TradeDate,
			&i.EffectiveDate,
			&i.TenorDays,
			&i.MaturityDate,
			&i.InterestAmount,
			&i.MaturityAmount,
			&i.HasCollateral,
			&i.CollateralCurrency,
			&i.CollateralDescription,
			&i.RequiresInternationalSettlement,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.CounterpartyCode,
			&i.CounterpartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMMInterbankPendingSettlement = `-- name: ListMMInterbankPendingSettlement :many
SELECT d.id, d.deal_number, d.ticket_number, d.counterparty_id, d.branch_id, d.currency_code, d.internal_ssi_id, d.counterparty_ssi_id, d.direction, d.principal_amount, d.interest_rate, d.day_count_convention, d.trade_date, d.effective_date, d.tenor_days, d.maturity_date, d.interest_amount, d.maturity_amount, d.has_collateral, d.collateral_currency, d.collateral_description, d.requires_international_settlement, d.status, d.note, d.cloned_from_id, d.cancel_reason, d.cancel_requested_by, d.cancel_requested_at, d.created_at, d.created_by, d.updated_at, d.updated_by, d.deleted_at, c.code AS counterparty_code, c.full_name AS counterparty_name
FROM mm_interbank_deals d
JOIN counterparties c ON c.id = d.counterparty_id
WHERE d.status = 'PENDING_SETTLEMENT'
  AND d.requires_international_settlement = true
  AND d.deleted_at IS NULL
ORDER BY d.effective_date ASC
LIMIT $1 OFFSET $2
`

type ListMMInterbankPendingSettlementParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMMInterbankPendingSettlementRow struct {
	ID                              uuid.UUID          `json:"id"`
	DealNumber                      string             `json:"deal_number"`
	TicketNumber                    *string            `json:"ticket_number"`
	CounterpartyID                  uuid.UUID          `json:"counterparty_id"`
	BranchID                        uuid.UUID          `json:"branch_id"`
	CurrencyCode                    string             `json:"currency_code"`
	InternalSsiID                   uuid.UUID          `json:"internal_ssi_id"`
	CounterpartySsiID               uuid.UUID          `json:"counterparty_ssi_id"`
	Direction                       string             `json:"direction"`
	PrincipalAmount                 pgtype.Numeric     `json:"principal_amount"`
	InterestRate                    pgtype.Numeric     `json:"interest_rate"`
	DayCountConvention              string             `json:"day_count_convention"`
	TradeDate                       pgtype.Date        `json:"trade_date"`
	EffectiveDate                   pgtype.Date        `json:"effective_date"`
	TenorDays                       int32              `json:"tenor_days"`
	MaturityDate                    pgtype.Date        `json:"maturity_date"`
	InterestAmount                  pgtype.Numeric     `json:"interest_amount"`
	MaturityAmount                  pgtype.Numeric     `json:"maturity_amount"`
	HasCollateral                   bool               `json:"has_collateral"`
	CollateralCurrency              *string            `json:"collateral_currency"`
	CollateralDescription           *string            `json:"collateral_description"`
	RequiresInternationalSettlement bool               `json:"requires_international_settlement"`
	Status                          string             `json:"status"`
	Note                            *string            `json:"note"`
	ClonedFromID                    pgtype.UUID        `json:"cloned_from_id"`
	CancelReason                    *string            `json:"cancel_reason"`
	CancelRequestedBy               pgtype.UUID        `json:"cancel_requested_by"`
	CancelRequestedAt               pgtype.Timestamptz `json:"cancel_requested_at"`
	CreatedAt                       time.Time          `json:"created_at"`
	CreatedBy                       uuid.UUID          `json:"created_by"`
	UpdatedAt                       time.Time          `json:"updated_at"`
	UpdatedBy                       uuid.UUID          `json:"updated_by"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
	CounterpartyCode                string             `json:"counterparty_code"`
	CounterpartyName                string             `json:"counterparty_name"`
}

// View cho TTQT: deals cần thanh toán quốc tế
// Logic: direction (PLACE/LEND → KLB chuyển tiền ra; TAKE/BORROW → nhận tiền vào)
// Chỉ hiển thị deals có requires_international_settlement = true
func (q *Queries) ListMMInterbankPendingSettlement(ctx context.Context, arg ListMMInterbankPendingSettlementParams) ([]ListMMInterbankPendingSettlementRow, error) {
	rows, err := q.db.Query(ctx, listMMInterbankPendingSettlement, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMMInterbankPendingSettlementRow{}
	for rows.Next() {
		var i ListMMInterbankPendingSettlementRow
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.TicketNumber,
			&i.CounterpartyID,
			&i.BranchID,
			&i.CurrencyCode,
			&i.InternalSsiID,
			&i.CounterpartySsiID,
			&i.Direction,
			&i.PrincipalAmount,
			&i.InterestRate,
			&i.DayCountConvention,
			&i.TradeDate,
			&i.EffectiveDate,
			&i.TenorDays,
			&i.MaturityDate,
			&i.InterestAmount,
			&i.MaturityAmount,
			&i.HasCollateral,
			&i.CollateralCurrency,
			&i.CollateralDescription,
			&i.RequiresInternationalSettlement,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.CounterpartyCode,
			&i.CounterpartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMMInterbankCancelRequest = `-- name: SetMMInterbankCancelRequest :one

UPDATE mm_interbank_deals SET
    cancel_reason = $3,
    cancel_requested_by = $1,
    cancel_requested_at = NOW(),
    status = 'CANCELLED',
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = $4
RETURNING id, deal_number, ticket_number, counterparty_id, branch_id, currency_code, internal_ssi_id, counterparty_ssi_id, direction, principal_amount, interest_rate, day_count_convention, trade_date, effective_date, tenor_days, maturity_date, interest_amount, maturity_amount, has_collateral, collateral_currency, collateral_description, requires_international_settlement, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type SetMMInterbankCancelRequestParams struct {
	CancelRequestedBy pgtype.UUID `json:"cancel_requested_by"`
	ID                uuid.UUID   `json:"id"`
	CancelReason      *string     `json:"cancel_reason"`
	Status            string      `json:"status"`
}

// Interest calculation formula (for reference — computed in application):
// ACT_365: interest = principal × rate/100 × tenor_days / 365
// ACT_360: interest = principal × rate/100 × tenor_days / 360
// ACT_ACT: interest = principal × rate/100 × tenor_days / year_basis
//
//	(year_basis = 365 or 366, depending on whether period spans Feb 29)
func (q *Queries) SetMMInterbankCancelRequest(ctx context.Context, arg SetMMInterbankCancelRequestParams) (MmInterbankDeal, error) {
	row := q.db.QueryRow(ctx, setMMInterbankCancelRequest,
		arg.CancelRequestedBy,
		arg.ID,
		arg.CancelReason,
		arg.Status,
	)
	var i MmInterbankDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.TicketNumber,
		&i.CounterpartyID,
		&i.BranchID,
		&i.CurrencyCode,
		&i.InternalSsiID,
		&i.CounterpartySsiID,
		&i.Direction,
		&i.PrincipalAmount,
		&i.InterestRate,
		&i.DayCountConvention,
		&i.TradeDate,
		&i.EffectiveDate,
		&i.TenorDays,
		&i.MaturityDate,
		&i.InterestAmount,
		&i.MaturityAmount,
		&i.HasCollateral,
		&i.CollateralCurrency,
		&i.CollateralDescription,
		&i.RequiresInternationalSettlement,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteMMInterbankDeal = `-- name: SoftDeleteMMInterbankDeal :exec
UPDATE mm_interbank_deals SET deleted_at = NOW(), updated_by = $2
WHERE id = $1 AND deleted_at IS NULL AND status = 'OPEN'
`

type SoftDeleteMMInterbankDealParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedBy uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteMMInterbankDeal(ctx context.Context, arg SoftDeleteMMInterbankDealParams) error {
	_, err := q.db.Exec(ctx, softDeleteMMInterbankDeal, arg.ID, arg.UpdatedBy)
	return err
}

const updateMMInterbankDeal = `-- name: UpdateMMInterbankDeal :one
UPDATE mm_interbank_deals SET
    ticket_number = COALESCE($3, ticket_number),
    counterparty_id = COALESCE($4, counterparty_id),
    currency_code = COALESCE($5, currency_code),
    internal_ssi_id = COALESCE($6, internal_ssi_id),
    counterparty_ssi_id = COALESCE($7, counterparty_ssi_id),
    direction = COALESCE($8, direction),
    principal_amount = COALESCE($9, principal_amount),
    interest_rate = COALESCE($10, interest_rate),
    day_count_convention = COALESCE($11, day_count_convention),
    effective_date = COALESCE($12, effective_date),
    tenor_days = COALESCE($13, tenor_days),
    maturity_date = COALESCE($14, maturity_date),
    interest_amount = COALESCE($15, interest_amount),
    maturity_amount = COALESCE($16, maturity_amount),
    has_collateral = COALESCE($17, has_collateral),
    collateral_currency = COALESCE($18, collateral_currency),
    collateral_description = COALESCE($19, collateral_description),
    requires_international_settlement = COALESCE($20, requires_international_settlement),
    note = COALESCE($21, note),
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = 'OPEN'
RETURNING id, deal_number, ticket_number, counterparty_id, branch_id, currency_code, internal_ssi_id, counterparty_ssi_id, direction, principal_amount, interest_rate, day_count_convention, trade_date, effective_date, tenor_days, maturity_date, interest_amount, maturity_amount, has_collateral, collateral_currency, collateral_description, requires_international_settlement, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type UpdateMMInterbankDealParams struct {
	UpdatedBy                       uuid.UUID      `json:"updated_by"`
	ID                              uuid.UUID      `json:"id"`
	TicketNumber                    *string        `json:"ticket_number"`
	CounterpartyID                  pgtype.UUID    `json:"counterparty_id"`
	CurrencyCode                    *string        `json:"currency_code"`
	InternalSsiID                   pgtype.UUID    `json:"internal_ssi_id"`
	CounterpartySsiID               pgtype.UUID    `json:"counterparty_ssi_id"`
	Direction                       *string        `json:"direction"`
	PrincipalAmount                 pgtype.Numeric `json:"principal_amount"`
	InterestRate                    pgtype.Numeric `json:"interest_rate"`
	DayCountConvention              *string        `json:"day_count_convention"`
	EffectiveDate                   pgtype.Date    `json:"effective_date"`
	TenorDays                       *int32         `json:"tenor_days"`
	MaturityDate                    pgtype.Date    `json:"maturity_date"`
	InterestAmount                  pgtype.Numeric `json:"interest_amount"`
	MaturityAmount                  pgtype.Numeric `json:"maturity_amount"`
	HasCollateral                   *bool          `json:"has_collateral"`
	CollateralCurrency              *string        `json:"collateral_currency"`
	CollateralDescription           *string        `json:"collateral_description"`
	RequiresInternationalSettlement *bool          `json:"requires_international_settlement"`
	Note                            *string        `json:"note"`
}

// Chỉ cập nhật khi OPEN
func (q *Queries) UpdateMMInterbankDeal(ctx context.Context, arg UpdateMMInterbankDealParams) (MmInterbankDeal, error) {
	row := q.db.QueryRow(ctx, updateMMInterbankDeal,
		arg.UpdatedBy,
		arg.ID,
		arg.TicketNumber,
		arg.CounterpartyID,
		arg.CurrencyCode,
		arg.InternalSsiID,
		arg.CounterpartySsiID,
		arg.Direction,
		arg.PrincipalAmount,
		arg.InterestRate,
		arg.DayCountConvention,
		arg.EffectiveDate,
		arg.TenorDays,
		arg.MaturityDate,
		arg.InterestAmount,
		arg.MaturityAmount,
		arg.HasCollateral,
		arg.CollateralCurrency,
		arg.CollateralDescription,
		arg.RequiresInternationalSettlement,
		arg.Note,
	)
	var i MmInterbankDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.TicketNumber,
		&i.CounterpartyID,
		&i.BranchID,
		&i.CurrencyCode,
		&i.InternalSsiID,
		&i.CounterpartySsiID,
		&i.Direction,
		&i.PrincipalAmount,
		&i.InterestRate,
		&i.DayCountConvention,
		&i.TradeDate,
		&i.EffectiveDate,
		&i.TenorDays,
		&i.MaturityDate,
		&i.InterestAmount,
		&i.MaturityAmount,
		&i.HasCollateral,
		&i.CollateralCurrency,
		&i.CollateralDescription,
		&i.RequiresInternationalSettlement,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const updateMMInterbankDealStatus = `-- name: UpdateMMInterbankDealStatus :one
UPDATE mm_interbank_deals SET
    status = $3,
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = $4
RETURNING id, deal_number, ticket_number, counterparty_id, branch_id, currency_code, internal_ssi_id, counterparty_ssi_id, direction, principal_amount, interest_rate, day_count_convention, trade_date, effective_date, tenor_days, maturity_date, interest_amount, maturity_amount, has_collateral, collateral_currency, collateral_description, requires_international_settlement, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type UpdateMMInterbankDealStatusParams struct {
	UpdatedBy uuid.UUID `json:"updated_by"`
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	Status_2  string    `json:"status_2"`
}

// Optimistic status transition
func (q *Queries) UpdateMMInterbankDealStatus(ctx context.Context, arg UpdateMMInterbankDealStatusParams) (MmInterbankDeal, error) {
	row := q.db.QueryRow(ctx, updateMMInterbankDealStatus,
		arg.UpdatedBy,
		arg.ID,
		arg.Status,
		arg.Status_2,
	)
	var i MmInterbankDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.TicketNumber,
		&i.CounterpartyID,
		&i.BranchID,
		&i.CurrencyCode,
		&i.InternalSsiID,
		&i.CounterpartySsiID,
		&i.Direction,
		&i.PrincipalAmount,
		&i.InterestRate,
		&i.DayCountConvention,
		&i.TradeDate,
		&i.EffectiveDate,
		&i.TenorDays,
		&i.MaturityDate,
		&i.InterestAmount,
		&i.MaturityAmount,
		&i.HasCollateral,
		&i.CollateralCurrency,
		&i.CollateralDescription,
		&i.RequiresInternationalSettlement,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}
