// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mm_omo_repo_deals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMMOmoRepoDeals = `-- name: CountMMOmoRepoDeals :one
SELECT COUNT(*) FROM mm_omo_repo_deals WHERE deleted_at IS NULL
`

func (q *Queries) CountMMOmoRepoDeals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMMOmoRepoDeals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMMOmoRepoDeal = `-- name: CreateMMOmoRepoDeal :one

INSERT INTO mm_omo_repo_deals (
    id, deal_number, deal_subtype, session_name, trade_date, branch_id,
    counterparty_id, notional_amount, bond_catalog_id,
    winning_rate, tenor_days, settlement_date_1, settlement_date_2,
    haircut_pct, status, note, cloned_from_id,
    created_at, created_by, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, 'OPEN', $14, $15,
    NOW(), $16, NOW(), $16
)
RETURNING id, deal_number, deal_subtype, session_name, trade_date, branch_id, counterparty_id, notional_amount, bond_catalog_id, winning_rate, tenor_days, settlement_date_1, settlement_date_2, haircut_pct, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type CreateMMOmoRepoDealParams struct {
	DealNumber      string         `json:"deal_number"`
	DealSubtype     string         `json:"deal_subtype"`
	SessionName     string         `json:"session_name"`
	TradeDate       pgtype.Date    `json:"trade_date"`
	BranchID        uuid.UUID      `json:"branch_id"`
	CounterpartyID  uuid.UUID      `json:"counterparty_id"`
	NotionalAmount  pgtype.Numeric `json:"notional_amount"`
	BondCatalogID   uuid.UUID      `json:"bond_catalog_id"`
	WinningRate     pgtype.Numeric `json:"winning_rate"`
	TenorDays       int32          `json:"tenor_days"`
	SettlementDate1 pgtype.Date    `json:"settlement_date_1"`
	SettlementDate2 pgtype.Date    `json:"settlement_date_2"`
	HaircutPct      pgtype.Numeric `json:"haircut_pct"`
	Note            *string        `json:"note"`
	ClonedFromID    pgtype.UUID    `json:"cloned_from_id"`
	CreatedBy       uuid.UUID      `json:"created_by"`
}

// ============================================================================
// mm_omo_repo_deals.sql — Queries for mm_omo_repo_deals table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateMMOmoRepoDeal(ctx context.Context, arg CreateMMOmoRepoDealParams) (MmOmoRepoDeal, error) {
	row := q.db.QueryRow(ctx, createMMOmoRepoDeal,
		arg.DealNumber,
		arg.DealSubtype,
		arg.SessionName,
		arg.TradeDate,
		arg.BranchID,
		arg.CounterpartyID,
		arg.NotionalAmount,
		arg.BondCatalogID,
		arg.WinningRate,
		arg.TenorDays,
		arg.SettlementDate1,
		arg.SettlementDate2,
		arg.HaircutPct,
		arg.Note,
		arg.ClonedFromID,
		arg.CreatedBy,
	)
	var i MmOmoRepoDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.DealSubtype,
		&i.SessionName,
		&i.TradeDate,
		&i.BranchID,
		&i.CounterpartyID,
		&i.NotionalAmount,
		&i.BondCatalogID,
		&i.WinningRate,
		&i.TenorDays,
		&i.SettlementDate1,
		&i.SettlementDate2,
		&i.HaircutPct,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getMMOmoRepoDealByID = `-- name: GetMMOmoRepoDealByID :one
SELECT id, deal_number, deal_subtype, session_name, trade_date, branch_id, counterparty_id, notional_amount, bond_catalog_id, winning_rate, tenor_days, settlement_date_1, settlement_date_2, haircut_pct, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM mm_omo_repo_deals
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMMOmoRepoDealByID(ctx context.Context, id uuid.UUID) (MmOmoRepoDeal, error) {
	row := q.db.QueryRow(ctx, getMMOmoRepoDealByID, id)
	var i MmOmoRepoDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.DealSubtype,
		&i.SessionName,
		&i.TradeDate,
		&i.BranchID,
		&i.CounterpartyID,
		&i.NotionalAmount,
		&i.BondCatalogID,
		&i.WinningRate,
		&i.TenorDays,
		&i.SettlementDate1,
		&i.SettlementDate2,
		&i.HaircutPct,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const listMMOmoRepoDeals = `-- name: ListMMOmoRepoDeals :many
SELECT id, deal_number, deal_subtype, session_name, trade_date, branch_id, counterparty_id, notional_amount, bond_catalog_id, winning_rate, tenor_days, settlement_date_1, settlement_date_2, haircut_pct, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM mm_omo_repo_deals
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMMOmoRepoDealsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMMOmoRepoDeals(ctx context.Context, arg ListMMOmoRepoDealsParams) ([]MmOmoRepoDeal, error) {
	rows, err := q.db.Query(ctx, listMMOmoRepoDeals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MmOmoRepoDeal{}
	for rows.Next() {
		var i MmOmoRepoDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.DealSubtype,
			&i.SessionName,
			&i.TradeDate,
			&i.BranchID,
			&i.CounterpartyID,
			&i.NotionalAmount,
			&i.BondCatalogID,
			&i.WinningRate,
			&i.TenorDays,
			&i.SettlementDate1,
			&i.SettlementDate2,
			&i.HaircutPct,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMMOmoRepoDealsByStatus = `-- name: ListMMOmoRepoDealsByStatus :many
SELECT id, deal_number, deal_subtype, session_name, trade_date, branch_id, counterparty_id, notional_amount, bond_catalog_id, winning_rate, tenor_days, settlement_date_1, settlement_date_2, haircut_pct, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM mm_omo_repo_deals
WHERE status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMMOmoRepoDealsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListMMOmoRepoDealsByStatus(ctx context.Context, arg ListMMOmoRepoDealsByStatusParams) ([]MmOmoRepoDeal, error) {
	rows, err := q.db.Query(ctx, listMMOmoRepoDealsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MmOmoRepoDeal{}
	for rows.Next() {
		var i MmOmoRepoDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.DealSubtype,
			&i.SessionName,
			&i.TradeDate,
			&i.BranchID,
			&i.CounterpartyID,
			&i.NotionalAmount,
			&i.BondCatalogID,
			&i.WinningRate,
			&i.TenorDays,
			&i.SettlementDate1,
			&i.SettlementDate2,
			&i.HaircutPct,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMMOmoRepoDealsBySubtype = `-- name: ListMMOmoRepoDealsBySubtype :many
SELECT id, deal_number, deal_subtype, session_name, trade_date, branch_id, counterparty_id, notional_amount, bond_catalog_id, winning_rate, tenor_days, settlement_date_1, settlement_date_2, haircut_pct, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM mm_omo_repo_deals
WHERE deal_subtype = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMMOmoRepoDealsBySubtypeParams struct {
	DealSubtype string `json:"deal_subtype"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

// Lọc theo loại: OMO (với NHNN) hoặc STATE_REPO (với KBNN)
func (q *Queries) ListMMOmoRepoDealsBySubtype(ctx context.Context, arg ListMMOmoRepoDealsBySubtypeParams) ([]MmOmoRepoDeal, error) {
	rows, err := q.db.Query(ctx, listMMOmoRepoDealsBySubtype, arg.DealSubtype, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MmOmoRepoDeal{}
	for rows.Next() {
		var i MmOmoRepoDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.DealSubtype,
			&i.SessionName,
			&i.TradeDate,
			&i.BranchID,
			&i.CounterpartyID,
			&i.NotionalAmount,
			&i.BondCatalogID,
			&i.WinningRate,
			&i.TenorDays,
			&i.SettlementDate1,
			&i.SettlementDate2,
			&i.HaircutPct,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMMOmoRepoPendingBooking = `-- name: ListMMOmoRepoPendingBooking :many
SELECT id, deal_number, deal_subtype, session_name, trade_date, branch_id, counterparty_id, notional_amount, bond_catalog_id, winning_rate, tenor_days, settlement_date_1, settlement_date_2, haircut_pct, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at FROM mm_omo_repo_deals
WHERE status IN ('PENDING_BOOKING', 'PENDING_CHIEF_ACCOUNTANT')
  AND deleted_at IS NULL
ORDER BY trade_date ASC, created_at ASC
LIMIT $1 OFFSET $2
`

type ListMMOmoRepoPendingBookingParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// View cho KTTC
func (q *Queries) ListMMOmoRepoPendingBooking(ctx context.Context, arg ListMMOmoRepoPendingBookingParams) ([]MmOmoRepoDeal, error) {
	rows, err := q.db.Query(ctx, listMMOmoRepoPendingBooking, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MmOmoRepoDeal{}
	for rows.Next() {
		var i MmOmoRepoDeal
		if err := rows.Scan(
			&i.ID,
			&i.DealNumber,
			&i.DealSubtype,
			&i.SessionName,
			&i.TradeDate,
			&i.BranchID,
			&i.CounterpartyID,
			&i.NotionalAmount,
			&i.BondCatalogID,
			&i.WinningRate,
			&i.TenorDays,
			&i.SettlementDate1,
			&i.SettlementDate2,
			&i.HaircutPct,
			&i.Status,
			&i.Note,
			&i.ClonedFromID,
			&i.CancelReason,
			&i.CancelRequestedBy,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMMOmoRepoCancelRequest = `-- name: SetMMOmoRepoCancelRequest :one
UPDATE mm_omo_repo_deals SET
    cancel_reason = $3,
    cancel_requested_by = $1,
    cancel_requested_at = NOW(),
    status = 'CANCELLED',
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = $4
RETURNING id, deal_number, deal_subtype, session_name, trade_date, branch_id, counterparty_id, notional_amount, bond_catalog_id, winning_rate, tenor_days, settlement_date_1, settlement_date_2, haircut_pct, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type SetMMOmoRepoCancelRequestParams struct {
	CancelRequestedBy pgtype.UUID `json:"cancel_requested_by"`
	ID                uuid.UUID   `json:"id"`
	CancelReason      *string     `json:"cancel_reason"`
	Status            string      `json:"status"`
}

func (q *Queries) SetMMOmoRepoCancelRequest(ctx context.Context, arg SetMMOmoRepoCancelRequestParams) (MmOmoRepoDeal, error) {
	row := q.db.QueryRow(ctx, setMMOmoRepoCancelRequest,
		arg.CancelRequestedBy,
		arg.ID,
		arg.CancelReason,
		arg.Status,
	)
	var i MmOmoRepoDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.DealSubtype,
		&i.SessionName,
		&i.TradeDate,
		&i.BranchID,
		&i.CounterpartyID,
		&i.NotionalAmount,
		&i.BondCatalogID,
		&i.WinningRate,
		&i.TenorDays,
		&i.SettlementDate1,
		&i.SettlementDate2,
		&i.HaircutPct,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteMMOmoRepoDeal = `-- name: SoftDeleteMMOmoRepoDeal :exec
UPDATE mm_omo_repo_deals SET deleted_at = NOW(), updated_by = $2
WHERE id = $1 AND deleted_at IS NULL AND status = 'OPEN'
`

type SoftDeleteMMOmoRepoDealParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedBy uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteMMOmoRepoDeal(ctx context.Context, arg SoftDeleteMMOmoRepoDealParams) error {
	_, err := q.db.Exec(ctx, softDeleteMMOmoRepoDeal, arg.ID, arg.UpdatedBy)
	return err
}

const updateMMOmoRepoDeal = `-- name: UpdateMMOmoRepoDeal :one
UPDATE mm_omo_repo_deals SET
    session_name = COALESCE($3, session_name),
    counterparty_id = COALESCE($4, counterparty_id),
    notional_amount = COALESCE($5, notional_amount),
    bond_catalog_id = COALESCE($6, bond_catalog_id),
    winning_rate = COALESCE($7, winning_rate),
    tenor_days = COALESCE($8, tenor_days),
    settlement_date_1 = COALESCE($9, settlement_date_1),
    settlement_date_2 = COALESCE($10, settlement_date_2),
    haircut_pct = COALESCE($11, haircut_pct),
    note = COALESCE($12, note),
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = 'OPEN'
RETURNING id, deal_number, deal_subtype, session_name, trade_date, branch_id, counterparty_id, notional_amount, bond_catalog_id, winning_rate, tenor_days, settlement_date_1, settlement_date_2, haircut_pct, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type UpdateMMOmoRepoDealParams struct {
	UpdatedBy       uuid.UUID      `json:"updated_by"`
	ID              uuid.UUID      `json:"id"`
	SessionName     *string        `json:"session_name"`
	CounterpartyID  pgtype.UUID    `json:"counterparty_id"`
	NotionalAmount  pgtype.Numeric `json:"notional_amount"`
	BondCatalogID   pgtype.UUID    `json:"bond_catalog_id"`
	WinningRate     pgtype.Numeric `json:"winning_rate"`
	TenorDays       *int32         `json:"tenor_days"`
	SettlementDate1 pgtype.Date    `json:"settlement_date_1"`
	SettlementDate2 pgtype.Date    `json:"settlement_date_2"`
	HaircutPct      pgtype.Numeric `json:"haircut_pct"`
	Note            *string        `json:"note"`
}

func (q *Queries) UpdateMMOmoRepoDeal(ctx context.Context, arg UpdateMMOmoRepoDealParams) (MmOmoRepoDeal, error) {
	row := q.db.QueryRow(ctx, updateMMOmoRepoDeal,
		arg.UpdatedBy,
		arg.ID,
		arg.SessionName,
		arg.CounterpartyID,
		arg.NotionalAmount,
		arg.BondCatalogID,
		arg.WinningRate,
		arg.TenorDays,
		arg.SettlementDate1,
		arg.SettlementDate2,
		arg.HaircutPct,
		arg.Note,
	)
	var i MmOmoRepoDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.DealSubtype,
		&i.SessionName,
		&i.TradeDate,
		&i.BranchID,
		&i.CounterpartyID,
		&i.NotionalAmount,
		&i.BondCatalogID,
		&i.WinningRate,
		&i.TenorDays,
		&i.SettlementDate1,
		&i.SettlementDate2,
		&i.HaircutPct,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const updateMMOmoRepoDealStatus = `-- name: UpdateMMOmoRepoDealStatus :one
UPDATE mm_omo_repo_deals SET
    status = $3,
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL AND status = $4
RETURNING id, deal_number, deal_subtype, session_name, trade_date, branch_id, counterparty_id, notional_amount, bond_catalog_id, winning_rate, tenor_days, settlement_date_1, settlement_date_2, haircut_pct, status, note, cloned_from_id, cancel_reason, cancel_requested_by, cancel_requested_at, created_at, created_by, updated_at, updated_by, deleted_at
`

type UpdateMMOmoRepoDealStatusParams struct {
	UpdatedBy uuid.UUID `json:"updated_by"`
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	Status_2  string    `json:"status_2"`
}

func (q *Queries) UpdateMMOmoRepoDealStatus(ctx context.Context, arg UpdateMMOmoRepoDealStatusParams) (MmOmoRepoDeal, error) {
	row := q.db.QueryRow(ctx, updateMMOmoRepoDealStatus,
		arg.UpdatedBy,
		arg.ID,
		arg.Status,
		arg.Status_2,
	)
	var i MmOmoRepoDeal
	err := row.Scan(
		&i.ID,
		&i.DealNumber,
		&i.DealSubtype,
		&i.SessionName,
		&i.TradeDate,
		&i.BranchID,
		&i.CounterpartyID,
		&i.NotionalAmount,
		&i.BondCatalogID,
		&i.WinningRate,
		&i.TenorDays,
		&i.SettlementDate1,
		&i.SettlementDate2,
		&i.HaircutPct,
		&i.Status,
		&i.Note,
		&i.ClonedFromID,
		&i.CancelReason,
		&i.CancelRequestedBy,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}
