// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadByUser = `-- name: CountUnreadByUser :one
SELECT COUNT(*) FROM notifications
WHERE recipient_id = $1 AND is_read = false
`

// Đếm thông báo chưa đọc — badge count
func (q *Queries) CountUnreadByUser(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadByUser, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (
    id, recipient_id, channel, event_type,
    title, body, deal_module, deal_id,
    is_read, delivery_status, created_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7,
    false, 'PENDING', NOW()
)
RETURNING id, recipient_id, channel, event_type, title, body, deal_module, deal_id, is_read, read_at, delivery_status, retry_count, last_error, next_retry_at, sent_at, created_at
`

type CreateNotificationParams struct {
	RecipientID uuid.UUID   `json:"recipient_id"`
	Channel     string      `json:"channel"`
	EventType   string      `json:"event_type"`
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	DealModule  *string     `json:"deal_module"`
	DealID      pgtype.UUID `json:"deal_id"`
}

// ============================================================================
// notifications.sql — Queries for notifications table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.RecipientID,
		arg.Channel,
		arg.EventType,
		arg.Title,
		arg.Body,
		arg.DealModule,
		arg.DealID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Channel,
		&i.EventType,
		&i.Title,
		&i.Body,
		&i.DealModule,
		&i.DealID,
		&i.IsRead,
		&i.ReadAt,
		&i.DeliveryStatus,
		&i.RetryCount,
		&i.LastError,
		&i.NextRetryAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < NOW() - INTERVAL '1 day' * $1::INT
  AND is_read = true
`

// Xóa thông báo cũ hơn N ngày — cleanup job
func (q *Queries) DeleteOldNotifications(ctx context.Context, retentionDays int32) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications, retentionDays)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, recipient_id, channel, event_type, title, body, deal_module, deal_id, is_read, read_at, delivery_status, retry_count, last_error, next_retry_at, sent_at, created_at FROM notifications WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Channel,
		&i.EventType,
		&i.Title,
		&i.Body,
		&i.DealModule,
		&i.DealID,
		&i.IsRead,
		&i.ReadAt,
		&i.DeliveryStatus,
		&i.RetryCount,
		&i.LastError,
		&i.NextRetryAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByDeal = `-- name: ListNotificationsByDeal :many
SELECT
    n.id, n.recipient_id, n.channel, n.event_type, n.title, n.body, n.deal_module, n.deal_id, n.is_read, n.read_at, n.delivery_status, n.retry_count, n.last_error, n.next_retry_at, n.sent_at, n.created_at,
    u.full_name AS recipient_name
FROM notifications n
JOIN users u ON u.id = n.recipient_id
WHERE n.deal_module = $1 AND n.deal_id = $2
ORDER BY n.created_at DESC
`

type ListNotificationsByDealParams struct {
	DealModule *string     `json:"deal_module"`
	DealID     pgtype.UUID `json:"deal_id"`
}

type ListNotificationsByDealRow struct {
	ID             uuid.UUID          `json:"id"`
	RecipientID    uuid.UUID          `json:"recipient_id"`
	Channel        string             `json:"channel"`
	EventType      string             `json:"event_type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	DealModule     *string            `json:"deal_module"`
	DealID         pgtype.UUID        `json:"deal_id"`
	IsRead         bool               `json:"is_read"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	DeliveryStatus string             `json:"delivery_status"`
	RetryCount     int16              `json:"retry_count"`
	LastError      *string            `json:"last_error"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	CreatedAt      time.Time          `json:"created_at"`
	RecipientName  string             `json:"recipient_name"`
}

// Lấy thông báo liên quan đến deal — deal detail page
func (q *Queries) ListNotificationsByDeal(ctx context.Context, arg ListNotificationsByDealParams) ([]ListNotificationsByDealRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsByDeal, arg.DealModule, arg.DealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsByDealRow{}
	for rows.Next() {
		var i ListNotificationsByDealRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Channel,
			&i.EventType,
			&i.Title,
			&i.Body,
			&i.DealModule,
			&i.DealID,
			&i.IsRead,
			&i.ReadAt,
			&i.DeliveryStatus,
			&i.RetryCount,
			&i.LastError,
			&i.NextRetryAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.RecipientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, recipient_id, channel, event_type, title, body, deal_module, deal_id, is_read, read_at, delivery_status, retry_count, last_error, next_retry_at, sent_at, created_at FROM notifications
WHERE recipient_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

// Lấy tất cả thông báo (đã đọc + chưa đọc) — notification center
func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.RecipientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Channel,
			&i.EventType,
			&i.Title,
			&i.Body,
			&i.DealModule,
			&i.DealID,
			&i.IsRead,
			&i.ReadAt,
			&i.DeliveryStatus,
			&i.RetryCount,
			&i.LastError,
			&i.NextRetryAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDelivery = `-- name: ListPendingDelivery :many
SELECT id, recipient_id, channel, event_type, title, body, deal_module, deal_id, is_read, read_at, delivery_status, retry_count, last_error, next_retry_at, sent_at, created_at FROM notifications
WHERE delivery_status IN ('PENDING', 'RETRYING')
  AND (next_retry_at IS NULL OR next_retry_at <= NOW())
ORDER BY created_at ASC
LIMIT $1
`

// Lấy notifications chờ gửi — email worker
func (q *Queries) ListPendingDelivery(ctx context.Context, limit int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listPendingDelivery, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Channel,
			&i.EventType,
			&i.Title,
			&i.Body,
			&i.DealModule,
			&i.DealID,
			&i.IsRead,
			&i.ReadAt,
			&i.DeliveryStatus,
			&i.RetryCount,
			&i.LastError,
			&i.NextRetryAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadByUser = `-- name: ListUnreadByUser :many
SELECT id, recipient_id, channel, event_type, title, body, deal_module, deal_id, is_read, read_at, delivery_status, retry_count, last_error, next_retry_at, sent_at, created_at FROM notifications
WHERE recipient_id = $1
  AND is_read = false
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUnreadByUserParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

// Lấy thông báo chưa đọc — bell icon + dropdown
func (q *Queries) ListUnreadByUser(ctx context.Context, arg ListUnreadByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadByUser, arg.RecipientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Channel,
			&i.EventType,
			&i.Title,
			&i.Body,
			&i.DealModule,
			&i.DealID,
			&i.IsRead,
			&i.ReadAt,
			&i.DeliveryStatus,
			&i.RetryCount,
			&i.LastError,
			&i.NextRetryAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllAsRead = `-- name: MarkAllAsRead :exec
UPDATE notifications SET
    is_read = true,
    read_at = NOW()
WHERE recipient_id = $1 AND is_read = false
`

// Đánh dấu tất cả đã đọc — "Mark all as read" button
func (q *Queries) MarkAllAsRead(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllAsRead, recipientID)
	return err
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE notifications SET
    is_read = true,
    read_at = NOW()
WHERE id = $1 AND recipient_id = $2 AND is_read = false
`

type MarkAsReadParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

// Đánh dấu đã đọc khi user click
func (q *Queries) MarkAsRead(ctx context.Context, arg MarkAsReadParams) error {
	_, err := q.db.Exec(ctx, markAsRead, arg.ID, arg.RecipientID)
	return err
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :exec
UPDATE notifications SET
    delivery_status = $2,
    sent_at = CASE WHEN $2 = 'SENT' THEN NOW() ELSE sent_at END,
    retry_count = CASE WHEN $2 = 'RETRYING' THEN retry_count + 1 ELSE retry_count END,
    last_error = $3,
    next_retry_at = $4
WHERE id = $1
`

type UpdateDeliveryStatusParams struct {
	ID             uuid.UUID          `json:"id"`
	DeliveryStatus string             `json:"delivery_status"`
	LastError      *string            `json:"last_error"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
}

// Cập nhật trạng thái gửi — email worker callback
func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryStatus,
		arg.ID,
		arg.DeliveryStatus,
		arg.LastError,
		arg.NextRetryAt,
	)
	return err
}
