// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :one
INSERT INTO role_permissions (id, role_id, permission_id, created_at, created_by)
VALUES (gen_random_uuid(), $1, $2, NOW(), $3)
ON CONFLICT (role_id, permission_id) DO NOTHING
RETURNING id, role_id, permission_id, created_at, created_by
`

type AssignPermissionToRoleParams struct {
	RoleID       uuid.UUID   `json:"role_id"`
	PermissionID uuid.UUID   `json:"permission_id"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID, arg.CreatedBy)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PermissionID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const checkUserPermission = `-- name: CheckUserPermission :one
SELECT EXISTS(
    SELECT 1 FROM permissions p
    JOIN role_permissions rp ON rp.permission_id = p.id
    JOIN user_roles ur ON ur.role_id = rp.role_id
    WHERE ur.user_id = $1 AND p.code = $2
) AS has_permission
`

type CheckUserPermissionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Code   string    `json:"code"`
}

// Kiểm tra user có permission cụ thể không — dùng cho authorization middleware
func (q *Queries) CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserPermission, arg.UserID, arg.Code)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const createPermission = `-- name: CreatePermission :one

INSERT INTO permissions (id, code, resource, action, description, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, NOW())
RETURNING id, code, resource, action, description, created_at
`

type CreatePermissionParams struct {
	Code        string  `json:"code"`
	Resource    string  `json:"resource"`
	Action      string  `json:"action"`
	Description *string `json:"description"`
}

// ============================================================================
// permissions.sql — Queries for permissions + role_permissions tables
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.Code,
		arg.Resource,
		arg.Action,
		arg.Description,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Resource,
		&i.Action,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, code, resource, action, description, created_at FROM permissions WHERE code = $1
`

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByCode, code)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Resource,
		&i.Action,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, code, resource, action, description, created_at FROM permissions WHERE id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id uuid.UUID) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Resource,
		&i.Action,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, code, resource, action, description, created_at FROM permissions
ORDER BY resource ASC, action ASC
LIMIT $1 OFFSET $2
`

type ListPermissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Resource,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByResource = `-- name: ListPermissionsByResource :many
SELECT id, code, resource, action, description, created_at FROM permissions
WHERE resource = $1
ORDER BY action ASC
`

func (q *Queries) ListPermissionsByResource(ctx context.Context, resource string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByResource, resource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Resource,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByRole = `-- name: ListPermissionsByRole :many
SELECT p.id, p.code, p.resource, p.action, p.description, p.created_at FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
ORDER BY p.resource ASC, p.action ASC
`

// Lấy tất cả permissions của một role
func (q *Queries) ListPermissionsByRole(ctx context.Context, roleID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Resource,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByUser = `-- name: ListPermissionsByUser :many
SELECT DISTINCT p.id, p.code, p.resource, p.action, p.description, p.created_at FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = $1
ORDER BY p.resource ASC, p.action ASC
`

// Lấy tất cả permissions của user (qua user_roles + role_permissions)
func (q *Queries) ListPermissionsByUser(ctx context.Context, userID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Resource,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :exec
DELETE FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
`

type RevokePermissionFromRoleParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}
