// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// BP.TTQT duyệt thanh toán
	ApprovePayment(ctx context.Context, arg ApprovePaymentParams) (InternationalPayment, error)
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) (RolePermission, error)
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (UserRole, error)
	// Batch insert cho preload lịch cả năm
	BulkInsertBusinessCalendar(ctx context.Context, arg BulkInsertBusinessCalendarParams) error
	// Tính toán utilization tổng hợp (MM + FX + Bond) cho uncollateralized limit
	// Query phức tạp này join các deals đã được duyệt nhưng chưa đáo hạn/settle
	CalculateUtilization(ctx context.Context, arg CalculateUtilizationParams) (pgtype.Numeric, error)
	// Kiểm tra tồn kho trước khi bán — hard block nếu không đủ
	// Trả về available_quantity: 0 nếu không tìm thấy record
	CheckInventoryBeforeSell(ctx context.Context, arg CheckInventoryBeforeSellParams) (int64, error)
	// Kiểm tra user có permission cụ thể không — dùng cho authorization middleware
	CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (bool, error)
	// Dọn dẹp sessions đã hết hạn quá 30 ngày
	CleanupExpiredSessions(ctx context.Context) error
	// Đếm số hành động phê duyệt theo deal
	CountApprovalActionsByDeal(ctx context.Context, arg CountApprovalActionsByDealParams) (int64, error)
	// Thống kê số lượng theo action — dashboard chart
	CountAuditLogsByAction(ctx context.Context, arg CountAuditLogsByActionParams) ([]CountAuditLogsByActionRow, error)
	CountBondDeals(ctx context.Context) (int64, error)
	CountCounterparties(ctx context.Context) (int64, error)
	CountFxDeals(ctx context.Context) (int64, error)
	// Dashboard: đếm deal theo status cho một ngày — hiển thị summary cards
	CountFxDealsByStatusAndDate(ctx context.Context, tradeDate pgtype.Date) ([]CountFxDealsByStatusAndDateRow, error)
	CountMMInterbankDeals(ctx context.Context) (int64, error)
	CountMMOmoRepoDeals(ctx context.Context) (int64, error)
	// Đếm thông báo chưa đọc — badge count
	CountUnreadByUser(ctx context.Context, recipientID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// ============================================================================
	// approval_actions.sql — Queries for approval_actions table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateApprovalAction(ctx context.Context, arg CreateApprovalActionParams) (ApprovalAction, error)
	// ============================================================================
	// audit_logs.sql — Queries for audit_logs table (partitioned)
	// Treasury Management System — KienlongBank
	// ============================================================================
	// Ghi nhật ký kiểm toán — APPEND-ONLY, không sửa/xóa
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// ============================================================================
	// bond_catalog.sql — Queries for bond_catalog table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateBondCatalog(ctx context.Context, arg CreateBondCatalogParams) (BondCatalog, error)
	// ============================================================================
	// bond_deals.sql — Queries for bond_deals table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateBondDeal(ctx context.Context, arg CreateBondDealParams) (BondDeal, error)
	// ============================================================================
	// bond_inventory.sql — Queries for bond_inventory table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateBondInventory(ctx context.Context, arg CreateBondInventoryParams) (BondInventory, error)
	// ============================================================================
	// branches.sql — Queries for branches table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error)
	// ============================================================================
	// business_calendar.sql — Queries for business_calendar table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateBusinessCalendarEntry(ctx context.Context, arg CreateBusinessCalendarEntryParams) (BusinessCalendar, error)
	// ============================================================================
	// counterparties.sql — Queries for counterparties table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateCounterparty(ctx context.Context, arg CreateCounterpartyParams) (Counterparty, error)
	// ============================================================================
	// credit_limits.sql — Queries for credit_limits table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateCreditLimit(ctx context.Context, arg CreateCreditLimitParams) (CreditLimit, error)
	// ============================================================================
	// currencies.sql — Queries for currencies table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	// ============================================================================
	// currency_pairs.sql — Queries for currency_pairs table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateCurrencyPair(ctx context.Context, arg CreateCurrencyPairParams) (CurrencyPair, error)
	// ============================================================================
	// documents.sql — Queries for documents table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	// ============================================================================
	// exchange_rates.sql — Queries for exchange_rates table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error)
	// ============================================================================
	// fx_deals.sql — Queries for fx_deals table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateFxDeal(ctx context.Context, arg CreateFxDealParams) (FxDeal, error)
	// ============================================================================
	// fx_deal_legs.sql — Queries for fx_deal_legs table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateFxDealLeg(ctx context.Context, arg CreateFxDealLegParams) (FxDealLeg, error)
	// ============================================================================
	// international_payments.sql — Queries for international_payments table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateInternationalPayment(ctx context.Context, arg CreateInternationalPaymentParams) (InternationalPayment, error)
	// ============================================================================
	// limit_approvals.sql — Queries for limit_approval_records table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateLimitApproval(ctx context.Context, arg CreateLimitApprovalParams) (LimitApprovalRecord, error)
	// ============================================================================
	// limit_snapshots.sql — Queries for limit_utilization_snapshots table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateLimitSnapshot(ctx context.Context, arg CreateLimitSnapshotParams) (LimitUtilizationSnapshot, error)
	// ============================================================================
	// mm_interbank_deals.sql — Queries for mm_interbank_deals table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateMMInterbankDeal(ctx context.Context, arg CreateMMInterbankDealParams) (MmInterbankDeal, error)
	// ============================================================================
	// mm_omo_repo_deals.sql — Queries for mm_omo_repo_deals table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateMMOmoRepoDeal(ctx context.Context, arg CreateMMOmoRepoDealParams) (MmOmoRepoDeal, error)
	// ============================================================================
	// notifications.sql — Queries for notifications table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// ============================================================================
	// permissions.sql — Queries for permissions + role_permissions tables
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	// ============================================================================
	// roles.sql — Queries for roles table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	// ============================================================================
	// sessions.sql — Queries for user_sessions table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	// ============================================================================
	// settlement_instructions.sql — Queries for settlement_instructions table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateSettlementInstruction(ctx context.Context, arg CreateSettlementInstructionParams) (SettlementInstruction, error)
	// Tạo rule mới — admin config
	CreateTransitionRule(ctx context.Context, arg CreateTransitionRuleParams) (StatusTransitionRule, error)
	// ============================================================================
	// users.sql — Queries for users table
	// Treasury Management System — KienlongBank
	// ============================================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// SCD Type 2: đóng bản ghi hiện tại lại khi có update
	DeactivateCurrentLimit(ctx context.Context, arg DeactivateCurrentLimitParams) (CreditLimit, error)
	// Vô hiệu hóa rule — soft disable
	DeactivateTransitionRule(ctx context.Context, id uuid.UUID) error
	// Giảm tồn kho khi bán — OPTIMISTIC LOCKING qua version check
	// Nếu version không khớp → row không được update → application retry
	// Nếu available_quantity < sell_quantity → CHECK constraint fail → error
	DecrementBondQuantity(ctx context.Context, arg DecrementBondQuantityParams) (BondInventory, error)
	// Xóa tất cả legs — dùng khi thay đổi deal type (e.g. Swap → Spot)
	DeleteFxDealLegsByDealID(ctx context.Context, dealID uuid.UUID) error
	// Xóa thông báo cũ hơn N ngày — cleanup job
	DeleteOldNotifications(ctx context.Context, retentionDays int32) error
	GetAuditLogByID(ctx context.Context, arg GetAuditLogByIDParams) (AuditLog, error)
	// Lấy số lượng khả dụng — dùng cho validation trước khi bán
	GetAvailableQuantity(ctx context.Context, arg GetAvailableQuantityParams) (int64, error)
	GetBondCatalogByCode(ctx context.Context, bondCode string) (BondCatalog, error)
	GetBondCatalogByID(ctx context.Context, id uuid.UUID) (BondCatalog, error)
	GetBondDealByID(ctx context.Context, id uuid.UUID) (BondDeal, error)
	// Lấy tồn kho theo bond_code + category + portfolio
	GetBondInventoryByBondCode(ctx context.Context, arg GetBondInventoryByBondCodeParams) (BondInventory, error)
	GetBondInventoryByID(ctx context.Context, id uuid.UUID) (BondInventory, error)
	GetBranchByCode(ctx context.Context, code string) (Branch, error)
	GetBranchByID(ctx context.Context, id uuid.UUID) (Branch, error)
	GetCounterpartyByCode(ctx context.Context, code string) (Counterparty, error)
	GetCounterpartyByID(ctx context.Context, id uuid.UUID) (Counterparty, error)
	GetCreditLimitByID(ctx context.Context, id uuid.UUID) (CreditLimit, error)
	GetCurrencyByCode(ctx context.Context, code string) (Currency, error)
	GetCurrencyByID(ctx context.Context, id uuid.UUID) (Currency, error)
	GetCurrencyPairByCode(ctx context.Context, pairCode string) (CurrencyPair, error)
	// Tìm cặp tiền tệ theo base + quote currency
	GetCurrencyPairByCurrencies(ctx context.Context, arg GetCurrencyPairByCurrenciesParams) (CurrencyPair, error)
	GetCurrencyPairByID(ctx context.Context, id uuid.UUID) (CurrencyPair, error)
	// Lấy hạn mức hiện tại cho đối tác + loại
	GetCurrentLimit(ctx context.Context, arg GetCurrentLimitParams) (CreditLimit, error)
	// Xem sequence hiện tại mà không tăng — dùng cho báo cáo/monitoring
	GetCurrentSequence(ctx context.Context, arg GetCurrentSequenceParams) (DealSequence, error)
	// Lấy summary 11 cột theo BRD
	// Query này rất phức tạp và cần snapshot để có performance tốt
	// Dưới đây là query mẫu, trong thực tế sẽ chạy trên bảng snapshot
	GetDailyLimitSummary(ctx context.Context, arg GetDailyLimitSummaryParams) ([]GetDailyLimitSummaryRow, error)
	// Lấy SSI mặc định cho counterparty + currency + owner_type
	GetDefaultSSI(ctx context.Context, arg GetDefaultSSIParams) (SettlementInstruction, error)
	GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error)
	// Tìm document theo storage key — dùng khi cần verify
	GetDocumentByStorageKey(ctx context.Context, storageKey string) (Document, error)
	GetExchangeRateByID(ctx context.Context, id uuid.UUID) (ExchangeRate, error)
	GetFxDealByID(ctx context.Context, id uuid.UUID) (FxDeal, error)
	// Lấy leg cụ thể của deal (near=1, far=2)
	GetFxDealLegByDealIDAndLeg(ctx context.Context, arg GetFxDealLegByDealIDAndLegParams) (FxDealLeg, error)
	GetFxDealLegByID(ctx context.Context, id uuid.UUID) (FxDealLeg, error)
	// Lấy tất cả legs của một deal (1 for Spot/Fwd, 2 for Swap)
	GetFxDealLegsByDealID(ctx context.Context, dealID uuid.UUID) ([]FxDealLeg, error)
	// Lấy deal header kèm tất cả legs — dùng cho chi tiết deal
	GetFxDealWithLegs(ctx context.Context, id uuid.UUID) ([]GetFxDealWithLegsRow, error)
	GetInternationalPaymentByID(ctx context.Context, id uuid.UUID) (InternationalPayment, error)
	// Tìm payment theo deal gốc (và leg nếu là swap)
	GetInternationalPaymentBySourceDeal(ctx context.Context, arg GetInternationalPaymentBySourceDealParams) (InternationalPayment, error)
	// Hành động phê duyệt gần nhất — xác định trạng thái hiện tại
	GetLatestApprovalActionByDeal(ctx context.Context, arg GetLatestApprovalActionByDealParams) (GetLatestApprovalActionByDealRow, error)
	// Lấy phiên bản mới nhất của tài liệu theo tên file
	GetLatestDocumentVersion(ctx context.Context, arg GetLatestDocumentVersionParams) (Document, error)
	// Lấy tỷ giá mới nhất cho một currency tính đến ngày chỉ định
	// Logic "ngày làm việc trước đó": ứng dụng tính previous business day rồi truyền vào
	GetLatestRateByDate(ctx context.Context, arg GetLatestRateByDateParams) (ExchangeRate, error)
	// Lấy snapshot mới nhất của đối tác
	GetLatestSnapshotByCounterparty(ctx context.Context, arg GetLatestSnapshotByCounterpartyParams) (LimitUtilizationSnapshot, error)
	// Lấy record phê duyệt hạn mức theo deal
	GetLimitApprovalByDealID(ctx context.Context, arg GetLimitApprovalByDealIDParams) (LimitApprovalRecord, error)
	GetLimitApprovalByID(ctx context.Context, id uuid.UUID) (LimitApprovalRecord, error)
	// Lấy lịch sử thay đổi hạn mức của đối tác
	GetLimitHistory(ctx context.Context, arg GetLimitHistoryParams) ([]CreditLimit, error)
	GetMMInterbankDealByID(ctx context.Context, id uuid.UUID) (MmInterbankDeal, error)
	GetMMOmoRepoDealByID(ctx context.Context, id uuid.UUID) (MmOmoRepoDeal, error)
	// Lấy mid rate cho quy đổi credit limit
	GetMidRate(ctx context.Context, arg GetMidRateParams) (pgtype.Numeric, error)
	// Lấy deal code tiếp theo để sinh prefix: G (Govi) hoặc F (FI/CD)
	// Application logic: bond_category = 'GOVERNMENT' → prefix 'G', else 'F'
	GetNextBondDealCode(ctx context.Context, dollar_1 interface{}) (string, error)
	// Lấy ngày làm việc tiếp theo — dùng cho tính settlement date T+1, T+2
	GetNextBusinessDay(ctx context.Context, arg GetNextBusinessDayParams) (pgtype.Date, error)
	// ============================================================================
	// deal_sequences.sql — Queries for deal_sequences table
	// Treasury Management System — KienlongBank
	// ============================================================================
	// Lấy và tăng sequence number — PHẢI chạy trong transaction
	// Pattern: SELECT FOR UPDATE → UPDATE → return new value
	// Tạo row mới nếu chưa tồn tại (first deal of the day)
	GetNextSequence(ctx context.Context, arg GetNextSequenceParams) (DealSequence, error)
	GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error)
	// Lấy ngày làm việc thứ N sau một ngày — T+N calculation
	// Ví dụ: T+2 = GetNthBusinessDayAfter(trade_date, 2)
	GetNthBusinessDayAfter(ctx context.Context, arg GetNthBusinessDayAfterParams) (pgtype.Date, error)
	GetPermissionByCode(ctx context.Context, code string) (Permission, error)
	GetPermissionByID(ctx context.Context, id uuid.UUID) (Permission, error)
	// Lấy ngày làm việc trước đó — dùng cho tra cứu tỷ giá "ngày làm việc liền trước"
	GetPreviousBusinessDay(ctx context.Context, arg GetPreviousBusinessDayParams) (pgtype.Date, error)
	GetRoleByCode(ctx context.Context, code string) (Role, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error)
	// Tìm session active theo token hash — dùng cho middleware authentication
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetSettlementInstructionByID(ctx context.Context, id uuid.UUID) (SettlementInstruction, error)
	GetSnapshotByCounterpartyAndDate(ctx context.Context, arg GetSnapshotByCounterpartyAndDateParams) (LimitUtilizationSnapshot, error)
	// Dùng khi AUTH_MODE=zitadel: match user từ JWT claim
	GetUserByExternalID(ctx context.Context, externalID *string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// ============================================================================
	// status_transitions.sql — Queries for status_transition_rules table
	// Treasury Management System — KienlongBank
	// ============================================================================
	// Lấy danh sách trạng thái đích hợp lệ từ trạng thái hiện tại
	// Dùng để hiển thị các action buttons trên UI
	GetValidTransitions(ctx context.Context, arg GetValidTransitionsParams) ([]StatusTransitionRule, error)
	// Lấy transitions mà role cụ thể được phép thực hiện
	// Dùng để filter UI buttons theo quyền user
	GetValidTransitionsForRole(ctx context.Context, arg GetValidTransitionsForRoleParams) ([]StatusTransitionRule, error)
	// Tăng tồn kho khi mua hoàn thành
	IncrementBondQuantity(ctx context.Context, arg IncrementBondQuantityParams) (BondInventory, error)
	// Kiểm tra một ngày có phải ngày làm việc không
	IsBusinessDay(ctx context.Context, arg IsBusinessDayParams) (bool, error)
	ListActiveCounterparties(ctx context.Context, arg ListActiveCounterpartiesParams) ([]Counterparty, error)
	ListActiveCurrencies(ctx context.Context) ([]Currency, error)
	ListActiveCurrencyPairs(ctx context.Context) ([]CurrencyPair, error)
	ListActiveSessionsByUser(ctx context.Context, userID uuid.UUID) ([]UserSession, error)
	// Liệt kê users đang hoạt động theo role code — dùng cho assign approval
	ListActiveUsersByRole(ctx context.Context, arg ListActiveUsersByRoleParams) ([]User, error)
	// Liệt kê toàn bộ rules — trang quản trị config
	ListAllTransitionRules(ctx context.Context, dealModule string) ([]StatusTransitionRule, error)
	// Lịch sử phê duyệt theo khoảng thời gian — báo cáo quản lý
	ListApprovalActionsByDateRange(ctx context.Context, arg ListApprovalActionsByDateRangeParams) ([]ListApprovalActionsByDateRangeRow, error)
	// Lịch sử phê duyệt theo deal — timeline hiển thị trên UI
	ListApprovalActionsByDeal(ctx context.Context, arg ListApprovalActionsByDealParams) ([]ListApprovalActionsByDealRow, error)
	// Lịch sử phê duyệt của user — báo cáo cá nhân
	ListApprovalActionsByUser(ctx context.Context, arg ListApprovalActionsByUserParams) ([]ApprovalAction, error)
	// Nhật ký theo khoảng thời gian — báo cáo kiểm toán định kỳ
	// Partition pruning tự động khi filter theo performed_at
	ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]AuditLog, error)
	// Lịch sử kiểm toán theo deal — audit trail trên deal detail
	ListAuditLogsByDeal(ctx context.Context, arg ListAuditLogsByDealParams) ([]AuditLog, error)
	// Lịch sử theo module — báo cáo theo nghiệp vụ
	ListAuditLogsByModule(ctx context.Context, arg ListAuditLogsByModuleParams) ([]AuditLog, error)
	// Lịch sử thao tác của user — user activity report
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	// Lịch sử user trên module cụ thể — compliance check
	ListAuditLogsByUserAndModule(ctx context.Context, arg ListAuditLogsByUserAndModuleParams) ([]AuditLog, error)
	ListBondCatalog(ctx context.Context, arg ListBondCatalogParams) ([]BondCatalog, error)
	// Tìm trái phiếu theo khoảng ngày đáo hạn
	ListBondCatalogByMaturityRange(ctx context.Context, arg ListBondCatalogByMaturityRangeParams) ([]BondCatalog, error)
	ListBondCatalogByType(ctx context.Context, arg ListBondCatalogByTypeParams) ([]BondCatalog, error)
	ListBondDeals(ctx context.Context, arg ListBondDealsParams) ([]BondDeal, error)
	// Lọc theo loại: GOVERNMENT (TPCP), FINANCIAL_INSTITUTION (TCTC), CERTIFICATE_OF_DEPOSIT (GTCG)
	ListBondDealsByCategory(ctx context.Context, arg ListBondDealsByCategoryParams) ([]BondDeal, error)
	ListBondDealsByStatus(ctx context.Context, arg ListBondDealsByStatusParams) ([]BondDeal, error)
	// View cho KTTC: deals chờ hạch toán (L1 hoặc L2)
	ListBondDealsPendingBooking(ctx context.Context, arg ListBondDealsPendingBookingParams) ([]BondDeal, error)
	ListBondInventory(ctx context.Context, arg ListBondInventoryParams) ([]BondInventory, error)
	ListBondInventoryByCategory(ctx context.Context, arg ListBondInventoryByCategoryParams) ([]BondInventory, error)
	ListBranches(ctx context.Context, arg ListBranchesParams) ([]Branch, error)
	ListBranchesByType(ctx context.Context, branchType string) ([]Branch, error)
	// Liệt kê ngày làm việc trong khoảng — dùng cho tính tenor
	ListBusinessDaysByRange(ctx context.Context, arg ListBusinessDaysByRangeParams) ([]BusinessCalendar, error)
	ListByCounterparty(ctx context.Context, counterpartyID uuid.UUID) ([]SettlementInstruction, error)
	// Lấy SSI theo đối tác + tiền tệ — dùng cho dropdown chọn pay code
	ListByCounterpartyAndCurrency(ctx context.Context, arg ListByCounterpartyAndCurrencyParams) ([]SettlementInstruction, error)
	ListByCounterpartyCurrencyAndOwner(ctx context.Context, arg ListByCounterpartyCurrencyAndOwnerParams) ([]SettlementInstruction, error)
	// Lấy danh sách chi nhánh con trực tiếp
	ListChildBranches(ctx context.Context, parentBranchID pgtype.UUID) ([]Branch, error)
	ListCounterparties(ctx context.Context, arg ListCounterpartiesParams) ([]Counterparty, error)
	// Liệt kê đối tác kèm hạn mức hiện tại — dùng cho màn hình credit limit
	ListCounterpartiesWithLimits(ctx context.Context, arg ListCounterpartiesWithLimitsParams) ([]ListCounterpartiesWithLimitsRow, error)
	ListCurrencies(ctx context.Context) ([]Currency, error)
	ListCurrencyPairs(ctx context.Context) ([]CurrencyPair, error)
	// Liệt kê tất cả hạn mức hiện tại
	ListCurrentLimits(ctx context.Context, arg ListCurrentLimitsParams) ([]CreditLimit, error)
	// Lấy tất cả version của một file — version history
	ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]ListDocumentVersionsRow, error)
	// Lấy tất cả tài liệu của deal — chỉ version hiện tại
	ListDocumentsByDeal(ctx context.Context, arg ListDocumentsByDealParams) ([]ListDocumentsByDealRow, error)
	ListFxDeals(ctx context.Context, arg ListFxDealsParams) ([]FxDeal, error)
	ListFxDealsByCounterpartyAndDateRange(ctx context.Context, arg ListFxDealsByCounterpartyAndDateRangeParams) ([]FxDeal, error)
	ListFxDealsByStatus(ctx context.Context, arg ListFxDealsByStatusParams) ([]FxDeal, error)
	ListFxDealsByTradeDate(ctx context.Context, arg ListFxDealsByTradeDateParams) ([]FxDeal, error)
	// Deals cần thanh toán quốc tế — chỉ deals đã qua phê duyệt booking
	ListFxDealsForSettlement(ctx context.Context, arg ListFxDealsForSettlementParams) ([]FxDeal, error)
	// Deals chờ phê duyệt — view cho Desk Head / Director / Accountant
	ListFxDealsPendingApproval(ctx context.Context, arg ListFxDealsPendingApprovalParams) ([]FxDeal, error)
	// Liệt kê ngày nghỉ/lễ trong năm — dùng cho admin quản lý lịch
	ListHolidaysByYear(ctx context.Context, arg ListHolidaysByYearParams) ([]BusinessCalendar, error)
	// Legs cần thanh toán quốc tế theo ngày settlement — BP.TTQT xử lý
	ListLegsRequiringSettlement(ctx context.Context, settlementDate pgtype.Date) ([]ListLegsRequiringSettlementRow, error)
	ListMMInterbankDeals(ctx context.Context, arg ListMMInterbankDealsParams) ([]MmInterbankDeal, error)
	// Giám sát đáo hạn — deal sắp đáo hạn trong khoảng ngày
	ListMMInterbankDealsByMaturityDate(ctx context.Context, arg ListMMInterbankDealsByMaturityDateParams) ([]MmInterbankDeal, error)
	ListMMInterbankDealsByStatus(ctx context.Context, arg ListMMInterbankDealsByStatusParams) ([]MmInterbankDeal, error)
	// View cho QLRR: deals chờ phê duyệt rủi ro
	ListMMInterbankPendingRiskApproval(ctx context.Context, arg ListMMInterbankPendingRiskApprovalParams) ([]ListMMInterbankPendingRiskApprovalRow, error)
	// View cho TTQT: deals cần thanh toán quốc tế
	// Logic: direction (PLACE/LEND → KLB chuyển tiền ra; TAKE/BORROW → nhận tiền vào)
	// Chỉ hiển thị deals có requires_international_settlement = true
	ListMMInterbankPendingSettlement(ctx context.Context, arg ListMMInterbankPendingSettlementParams) ([]ListMMInterbankPendingSettlementRow, error)
	ListMMOmoRepoDeals(ctx context.Context, arg ListMMOmoRepoDealsParams) ([]MmOmoRepoDeal, error)
	ListMMOmoRepoDealsByStatus(ctx context.Context, arg ListMMOmoRepoDealsByStatusParams) ([]MmOmoRepoDeal, error)
	// Lọc theo loại: OMO (với NHNN) hoặc STATE_REPO (với KBNN)
	ListMMOmoRepoDealsBySubtype(ctx context.Context, arg ListMMOmoRepoDealsBySubtypeParams) ([]MmOmoRepoDeal, error)
	// View cho KTTC
	ListMMOmoRepoPendingBooking(ctx context.Context, arg ListMMOmoRepoPendingBookingParams) ([]MmOmoRepoDeal, error)
	// Lấy thông báo liên quan đến deal — deal detail page
	ListNotificationsByDeal(ctx context.Context, arg ListNotificationsByDealParams) ([]ListNotificationsByDealRow, error)
	// Lấy tất cả thông báo (đã đọc + chưa đọc) — notification center
	ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error)
	// Tìm kiếm payment theo khoảng ngày
	ListPaymentsByDateRange(ctx context.Context, arg ListPaymentsByDateRangeParams) ([]ListPaymentsByDateRangeRow, error)
	ListPaymentsByStatus(ctx context.Context, arg ListPaymentsByStatusParams) ([]ListPaymentsByStatusRow, error)
	// Danh sách deal đang chờ role cụ thể phê duyệt
	// Join status_transition_rules để biết role nào cần duyệt tiếp
	ListPendingApprovalsByRole(ctx context.Context, arg ListPendingApprovalsByRoleParams) ([]ListPendingApprovalsByRoleRow, error)
	// Lấy notifications chờ gửi — email worker
	ListPendingDelivery(ctx context.Context, limit int32) ([]Notification, error)
	// Lấy danh sách các deal chờ QLRR duyệt hạn mức
	ListPendingLimitApprovals(ctx context.Context, arg ListPendingLimitApprovalsParams) ([]ListPendingLimitApprovalsRow, error)
	// Lấy danh sách payment cần xử lý hôm nay
	ListPendingPaymentsToday(ctx context.Context, arg ListPendingPaymentsTodayParams) ([]ListPendingPaymentsTodayRow, error)
	// Lấy tài liệu chờ quét virus — antivirus worker
	ListPendingScanDocuments(ctx context.Context, limit int32) ([]Document, error)
	ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]Permission, error)
	ListPermissionsByResource(ctx context.Context, resource string) ([]Permission, error)
	// Lấy tất cả permissions của một role
	ListPermissionsByRole(ctx context.Context, roleID uuid.UUID) ([]Permission, error)
	// Lấy tất cả permissions của user (qua user_roles + role_permissions)
	ListPermissionsByUser(ctx context.Context, userID uuid.UUID) ([]Permission, error)
	ListRatesByCurrencyAndDateRange(ctx context.Context, arg ListRatesByCurrencyAndDateRangeParams) ([]ExchangeRate, error)
	// Lấy tất cả tỷ giá của một ngày
	ListRatesByDate(ctx context.Context, effectiveDate pgtype.Date) ([]ExchangeRate, error)
	ListRoles(ctx context.Context) ([]Role, error)
	// Lấy tất cả roles được gán cho user
	ListRolesByUser(ctx context.Context, userID uuid.UUID) ([]Role, error)
	// Liệt kê tất cả sequence trong ngày — monitoring dashboard
	ListSequencesByDate(ctx context.Context, datePartition pgtype.Date) ([]DealSequence, error)
	// Lịch sử sequence theo module — dùng cho báo cáo
	ListSequencesByModule(ctx context.Context, arg ListSequencesByModuleParams) ([]DealSequence, error)
	// Lấy lịch sử snapshot của đối tác
	ListSnapshotsByCounterparty(ctx context.Context, arg ListSnapshotsByCounterpartyParams) ([]LimitUtilizationSnapshot, error)
	// Tất cả transitions mà role được phép — authorization matrix
	ListTransitionRulesByRole(ctx context.Context, requiredRole string) ([]StatusTransitionRule, error)
	// Lấy thông báo chưa đọc — bell icon + dropdown
	ListUnreadByUser(ctx context.Context, arg ListUnreadByUserParams) ([]Notification, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByBranch(ctx context.Context, arg ListUsersByBranchParams) ([]User, error)
	ListUsersByDepartment(ctx context.Context, arg ListUsersByDepartmentParams) ([]User, error)
	// Đánh dấu tất cả đã đọc — "Mark all as read" button
	MarkAllAsRead(ctx context.Context, recipientID uuid.UUID) error
	// Đánh dấu đã đọc khi user click
	MarkAsRead(ctx context.Context, arg MarkAsReadParams) error
	// Cập nhật kết quả quét virus
	MarkDocumentScanned(ctx context.Context, arg MarkDocumentScannedParams) (Document, error)
	// Đánh dấu các version cũ khi upload version mới
	MarkOldVersions(ctx context.Context, arg MarkOldVersionsParams) error
	// BP.TTQT từ chối thanh toán
	RejectPayment(ctx context.Context, arg RejectPaymentParams) (InternationalPayment, error)
	// Thu hồi tất cả sessions của user (force logout all devices)
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error
	RevokeRoleFromUser(ctx context.Context, arg RevokeRoleFromUserParams) error
	// Thu hồi một session (logout)
	RevokeSession(ctx context.Context, id uuid.UUID) error
	// Tìm theo loại hành động — vd: tất cả REJECT trong tháng
	SearchAuditLogsByAction(ctx context.Context, arg SearchAuditLogsByActionParams) ([]AuditLog, error)
	// Tìm kiếm theo mã hoặc tổ chức phát hành
	SearchBondCatalog(ctx context.Context, arg SearchBondCatalogParams) ([]BondCatalog, error)
	// Tìm kiếm đối tác theo tên (ILIKE — case insensitive)
	SearchCounterpartiesByName(ctx context.Context, arg SearchCounterpartiesByNameParams) ([]Counterparty, error)
	SetBondDealCancelRequest(ctx context.Context, arg SetBondDealCancelRequestParams) (BondDeal, error)
	// Dealer yêu cầu hủy deal đã hoàn thành
	SetFxDealCancelRequest(ctx context.Context, arg SetFxDealCancelRequestParams) (FxDeal, error)
	// Interest calculation formula (for reference — computed in application):
	// ACT_365: interest = principal × rate/100 × tenor_days / 365
	// ACT_360: interest = principal × rate/100 × tenor_days / 360
	// ACT_ACT: interest = principal × rate/100 × tenor_days / year_basis
	//          (year_basis = 365 or 366, depending on whether period spans Feb 29)
	SetMMInterbankCancelRequest(ctx context.Context, arg SetMMInterbankCancelRequestParams) (MmInterbankDeal, error)
	SetMMOmoRepoCancelRequest(ctx context.Context, arg SetMMOmoRepoCancelRequestParams) (MmOmoRepoDeal, error)
	SoftDeleteBondDeal(ctx context.Context, arg SoftDeleteBondDealParams) error
	SoftDeleteCounterparty(ctx context.Context, arg SoftDeleteCounterpartyParams) error
	// Xóa mềm tài liệu
	SoftDeleteDocument(ctx context.Context, id uuid.UUID) error
	SoftDeleteFxDeal(ctx context.Context, arg SoftDeleteFxDealParams) error
	SoftDeleteMMInterbankDeal(ctx context.Context, arg SoftDeleteMMInterbankDealParams) error
	SoftDeleteMMOmoRepoDeal(ctx context.Context, arg SoftDeleteMMOmoRepoDealParams) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateBondCatalog(ctx context.Context, arg UpdateBondCatalogParams) (BondCatalog, error)
	// Chỉ cập nhật khi OPEN
	UpdateBondDeal(ctx context.Context, arg UpdateBondDealParams) (BondDeal, error)
	// Optimistic status update
	UpdateBondDealStatus(ctx context.Context, arg UpdateBondDealStatusParams) (BondDeal, error)
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error)
	UpdateCounterparty(ctx context.Context, arg UpdateCounterpartyParams) (Counterparty, error)
	UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error)
	UpdateCurrencyPair(ctx context.Context, arg UpdateCurrencyPairParams) (CurrencyPair, error)
	// Cập nhật trạng thái gửi — email worker callback
	UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error
	// Chỉ cập nhật khi deal ở trạng thái OPEN
	UpdateFxDeal(ctx context.Context, arg UpdateFxDealParams) (FxDeal, error)
	UpdateFxDealLeg(ctx context.Context, arg UpdateFxDealLegParams) (FxDealLeg, error)
	// Optimistic status transition: chỉ cập nhật nếu status hiện tại khớp
	// Application phải kiểm tra status_transition_rules trước khi gọi
	UpdateFxDealStatus(ctx context.Context, arg UpdateFxDealStatusParams) (FxDeal, error)
	// Cập nhật trạng thái phê duyệt từ QLRR
	UpdateLimitApprovalStatus(ctx context.Context, arg UpdateLimitApprovalStatusParams) (LimitApprovalRecord, error)
	// Chỉ cập nhật khi OPEN
	UpdateMMInterbankDeal(ctx context.Context, arg UpdateMMInterbankDealParams) (MmInterbankDeal, error)
	// Optimistic status transition
	UpdateMMInterbankDealStatus(ctx context.Context, arg UpdateMMInterbankDealStatusParams) (MmInterbankDeal, error)
	UpdateMMOmoRepoDeal(ctx context.Context, arg UpdateMMOmoRepoDealParams) (MmOmoRepoDeal, error)
	UpdateMMOmoRepoDealStatus(ctx context.Context, arg UpdateMMOmoRepoDealStatusParams) (MmOmoRepoDeal, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateSettlementInstruction(ctx context.Context, arg UpdateSettlementInstructionParams) (SettlementInstruction, error)
	// Cập nhật rule — admin config
	UpdateTransitionRule(ctx context.Context, arg UpdateTransitionRuleParams) (StatusTransitionRule, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	// Insert hoặc update tồn kho — dùng khi mua bond mới chưa có record
	UpsertBondInventory(ctx context.Context, arg UpsertBondInventoryParams) (BondInventory, error)
	// Insert or update tỷ giá — unique on (currency_code, effective_date)
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) (ExchangeRate, error)
	// Tạo hoặc cập nhật snapshot cho ngày
	UpsertLimitSnapshot(ctx context.Context, arg UpsertLimitSnapshotParams) (LimitUtilizationSnapshot, error)
	// Kiểm tra transition có hợp lệ không (from_status + to_status + role)
	// Return NULL nếu không hợp lệ → application deny action
	ValidateTransition(ctx context.Context, arg ValidateTransitionParams) (StatusTransitionRule, error)
}

var _ Querier = (*Queries)(nil)
