// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM user_sessions
WHERE expires_at < NOW() - INTERVAL '30 days'
`

// Dọn dẹp sessions đã hết hạn quá 30 ngày
func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :one

INSERT INTO user_sessions (id, user_id, token_hash, ip_address, user_agent, expires_at, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, NOW())
RETURNING id, user_id, token_hash, ip_address, user_agent, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	IpAddress string    `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
	ExpiresAt time.Time `json:"expires_at"`
}

// ============================================================================
// sessions.sql — Queries for user_sessions table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, token_hash, ip_address, user_agent, expires_at, revoked_at, created_at FROM user_sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.ip_address, s.user_agent, s.expires_at, s.revoked_at, s.created_at, u.username, u.full_name, u.is_active AS user_is_active
FROM user_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > NOW()
  AND s.revoked_at IS NULL
  AND u.deleted_at IS NULL
`

type GetSessionByTokenHashRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TokenHash    string             `json:"token_hash"`
	IpAddress    string             `json:"ip_address"`
	UserAgent    *string            `json:"user_agent"`
	ExpiresAt    time.Time          `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt    time.Time          `json:"created_at"`
	Username     string             `json:"username"`
	FullName     string             `json:"full_name"`
	UserIsActive bool               `json:"user_is_active"`
}

// Tìm session active theo token hash — dùng cho middleware authentication
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Username,
		&i.FullName,
		&i.UserIsActive,
	)
	return i, err
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT id, user_id, token_hash, ip_address, user_agent, expires_at, revoked_at, created_at FROM user_sessions
WHERE user_id = $1
  AND expires_at > NOW()
  AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, userID uuid.UUID) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE user_sessions SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

// Thu hồi tất cả sessions của user (force logout all devices)
func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE user_sessions SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

// Thu hồi một session (logout)
func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}
