// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settlement_instructions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSettlementInstruction = `-- name: CreateSettlementInstruction :one

INSERT INTO settlement_instructions (
    id, counterparty_id, currency_code, owner_type,
    account_number, bank_name, swift_code, citad_code,
    description, is_default, is_active,
    created_at, created_by, updated_at, updated_by
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, true,
    NOW(), $10, NOW(), $10
)
RETURNING id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, citad_code, description, is_default, is_active, created_at, created_by, updated_at, updated_by
`

type CreateSettlementInstructionParams struct {
	CounterpartyID uuid.UUID   `json:"counterparty_id"`
	CurrencyCode   string      `json:"currency_code"`
	OwnerType      string      `json:"owner_type"`
	AccountNumber  string      `json:"account_number"`
	BankName       string      `json:"bank_name"`
	SwiftCode      *string     `json:"swift_code"`
	CitadCode      *string     `json:"citad_code"`
	Description    *string     `json:"description"`
	IsDefault      bool        `json:"is_default"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

// ============================================================================
// settlement_instructions.sql — Queries for settlement_instructions table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateSettlementInstruction(ctx context.Context, arg CreateSettlementInstructionParams) (SettlementInstruction, error) {
	row := q.db.QueryRow(ctx, createSettlementInstruction,
		arg.CounterpartyID,
		arg.CurrencyCode,
		arg.OwnerType,
		arg.AccountNumber,
		arg.BankName,
		arg.SwiftCode,
		arg.CitadCode,
		arg.Description,
		arg.IsDefault,
		arg.CreatedBy,
	)
	var i SettlementInstruction
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.CurrencyCode,
		&i.OwnerType,
		&i.AccountNumber,
		&i.BankName,
		&i.SwiftCode,
		&i.CitadCode,
		&i.Description,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getDefaultSSI = `-- name: GetDefaultSSI :one
SELECT id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, citad_code, description, is_default, is_active, created_at, created_by, updated_at, updated_by FROM settlement_instructions
WHERE counterparty_id = $1
  AND currency_code = $2
  AND owner_type = $3
  AND is_default = true
  AND is_active = true
LIMIT 1
`

type GetDefaultSSIParams struct {
	CounterpartyID uuid.UUID `json:"counterparty_id"`
	CurrencyCode   string    `json:"currency_code"`
	OwnerType      string    `json:"owner_type"`
}

// Lấy SSI mặc định cho counterparty + currency + owner_type
func (q *Queries) GetDefaultSSI(ctx context.Context, arg GetDefaultSSIParams) (SettlementInstruction, error) {
	row := q.db.QueryRow(ctx, getDefaultSSI, arg.CounterpartyID, arg.CurrencyCode, arg.OwnerType)
	var i SettlementInstruction
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.CurrencyCode,
		&i.OwnerType,
		&i.AccountNumber,
		&i.BankName,
		&i.SwiftCode,
		&i.CitadCode,
		&i.Description,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getSettlementInstructionByID = `-- name: GetSettlementInstructionByID :one
SELECT id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, citad_code, description, is_default, is_active, created_at, created_by, updated_at, updated_by FROM settlement_instructions WHERE id = $1
`

func (q *Queries) GetSettlementInstructionByID(ctx context.Context, id uuid.UUID) (SettlementInstruction, error) {
	row := q.db.QueryRow(ctx, getSettlementInstructionByID, id)
	var i SettlementInstruction
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.CurrencyCode,
		&i.OwnerType,
		&i.AccountNumber,
		&i.BankName,
		&i.SwiftCode,
		&i.CitadCode,
		&i.Description,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listByCounterparty = `-- name: ListByCounterparty :many
SELECT id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, citad_code, description, is_default, is_active, created_at, created_by, updated_at, updated_by FROM settlement_instructions
WHERE counterparty_id = $1 AND is_active = true
ORDER BY owner_type ASC, currency_code ASC
`

func (q *Queries) ListByCounterparty(ctx context.Context, counterpartyID uuid.UUID) ([]SettlementInstruction, error) {
	rows, err := q.db.Query(ctx, listByCounterparty, counterpartyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementInstruction{}
	for rows.Next() {
		var i SettlementInstruction
		if err := rows.Scan(
			&i.ID,
			&i.CounterpartyID,
			&i.CurrencyCode,
			&i.OwnerType,
			&i.AccountNumber,
			&i.BankName,
			&i.SwiftCode,
			&i.CitadCode,
			&i.Description,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByCounterpartyAndCurrency = `-- name: ListByCounterpartyAndCurrency :many
SELECT id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, citad_code, description, is_default, is_active, created_at, created_by, updated_at, updated_by FROM settlement_instructions
WHERE counterparty_id = $1
  AND currency_code = $2
  AND is_active = true
ORDER BY is_default DESC, owner_type ASC
`

type ListByCounterpartyAndCurrencyParams struct {
	CounterpartyID uuid.UUID `json:"counterparty_id"`
	CurrencyCode   string    `json:"currency_code"`
}

// Lấy SSI theo đối tác + tiền tệ — dùng cho dropdown chọn pay code
func (q *Queries) ListByCounterpartyAndCurrency(ctx context.Context, arg ListByCounterpartyAndCurrencyParams) ([]SettlementInstruction, error) {
	rows, err := q.db.Query(ctx, listByCounterpartyAndCurrency, arg.CounterpartyID, arg.CurrencyCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementInstruction{}
	for rows.Next() {
		var i SettlementInstruction
		if err := rows.Scan(
			&i.ID,
			&i.CounterpartyID,
			&i.CurrencyCode,
			&i.OwnerType,
			&i.AccountNumber,
			&i.BankName,
			&i.SwiftCode,
			&i.CitadCode,
			&i.Description,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByCounterpartyCurrencyAndOwner = `-- name: ListByCounterpartyCurrencyAndOwner :many
SELECT id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, citad_code, description, is_default, is_active, created_at, created_by, updated_at, updated_by FROM settlement_instructions
WHERE counterparty_id = $1
  AND currency_code = $2
  AND owner_type = $3
  AND is_active = true
ORDER BY is_default DESC
`

type ListByCounterpartyCurrencyAndOwnerParams struct {
	CounterpartyID uuid.UUID `json:"counterparty_id"`
	CurrencyCode   string    `json:"currency_code"`
	OwnerType      string    `json:"owner_type"`
}

func (q *Queries) ListByCounterpartyCurrencyAndOwner(ctx context.Context, arg ListByCounterpartyCurrencyAndOwnerParams) ([]SettlementInstruction, error) {
	rows, err := q.db.Query(ctx, listByCounterpartyCurrencyAndOwner, arg.CounterpartyID, arg.CurrencyCode, arg.OwnerType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementInstruction{}
	for rows.Next() {
		var i SettlementInstruction
		if err := rows.Scan(
			&i.ID,
			&i.CounterpartyID,
			&i.CurrencyCode,
			&i.OwnerType,
			&i.AccountNumber,
			&i.BankName,
			&i.SwiftCode,
			&i.CitadCode,
			&i.Description,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettlementInstruction = `-- name: UpdateSettlementInstruction :one
UPDATE settlement_instructions SET
    account_number = COALESCE($3, account_number),
    bank_name = COALESCE($4, bank_name),
    swift_code = COALESCE($5, swift_code),
    citad_code = COALESCE($6, citad_code),
    description = COALESCE($7, description),
    is_default = COALESCE($8, is_default),
    is_active = COALESCE($9, is_active),
    updated_by = $1
WHERE id = $2
RETURNING id, counterparty_id, currency_code, owner_type, account_number, bank_name, swift_code, citad_code, description, is_default, is_active, created_at, created_by, updated_at, updated_by
`

type UpdateSettlementInstructionParams struct {
	UpdatedBy     pgtype.UUID `json:"updated_by"`
	ID            uuid.UUID   `json:"id"`
	AccountNumber *string     `json:"account_number"`
	BankName      *string     `json:"bank_name"`
	SwiftCode     *string     `json:"swift_code"`
	CitadCode     *string     `json:"citad_code"`
	Description   *string     `json:"description"`
	IsDefault     *bool       `json:"is_default"`
	IsActive      *bool       `json:"is_active"`
}

func (q *Queries) UpdateSettlementInstruction(ctx context.Context, arg UpdateSettlementInstructionParams) (SettlementInstruction, error) {
	row := q.db.QueryRow(ctx, updateSettlementInstruction,
		arg.UpdatedBy,
		arg.ID,
		arg.AccountNumber,
		arg.BankName,
		arg.SwiftCode,
		arg.CitadCode,
		arg.Description,
		arg.IsDefault,
		arg.IsActive,
	)
	var i SettlementInstruction
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.CurrencyCode,
		&i.OwnerType,
		&i.AccountNumber,
		&i.BankName,
		&i.SwiftCode,
		&i.CitadCode,
		&i.Description,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
