// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: status_transitions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTransitionRule = `-- name: CreateTransitionRule :one
INSERT INTO status_transition_rules (
    id, deal_module, from_status, to_status,
    required_role, requires_reason, requires_confirmation, is_active
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, true
)
RETURNING id, deal_module, from_status, to_status, required_role, requires_reason, requires_confirmation, is_active
`

type CreateTransitionRuleParams struct {
	DealModule           string `json:"deal_module"`
	FromStatus           string `json:"from_status"`
	ToStatus             string `json:"to_status"`
	RequiredRole         string `json:"required_role"`
	RequiresReason       bool   `json:"requires_reason"`
	RequiresConfirmation bool   `json:"requires_confirmation"`
}

// Tạo rule mới — admin config
func (q *Queries) CreateTransitionRule(ctx context.Context, arg CreateTransitionRuleParams) (StatusTransitionRule, error) {
	row := q.db.QueryRow(ctx, createTransitionRule,
		arg.DealModule,
		arg.FromStatus,
		arg.ToStatus,
		arg.RequiredRole,
		arg.RequiresReason,
		arg.RequiresConfirmation,
	)
	var i StatusTransitionRule
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.FromStatus,
		&i.ToStatus,
		&i.RequiredRole,
		&i.RequiresReason,
		&i.RequiresConfirmation,
		&i.IsActive,
	)
	return i, err
}

const deactivateTransitionRule = `-- name: DeactivateTransitionRule :exec
UPDATE status_transition_rules SET is_active = false
WHERE id = $1
`

// Vô hiệu hóa rule — soft disable
func (q *Queries) DeactivateTransitionRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateTransitionRule, id)
	return err
}

const getValidTransitions = `-- name: GetValidTransitions :many

SELECT id, deal_module, from_status, to_status, required_role, requires_reason, requires_confirmation, is_active FROM status_transition_rules
WHERE deal_module = $1
  AND from_status = $2
  AND is_active = true
ORDER BY to_status ASC
`

type GetValidTransitionsParams struct {
	DealModule string `json:"deal_module"`
	FromStatus string `json:"from_status"`
}

// ============================================================================
// status_transitions.sql — Queries for status_transition_rules table
// Treasury Management System — KienlongBank
// ============================================================================
// Lấy danh sách trạng thái đích hợp lệ từ trạng thái hiện tại
// Dùng để hiển thị các action buttons trên UI
func (q *Queries) GetValidTransitions(ctx context.Context, arg GetValidTransitionsParams) ([]StatusTransitionRule, error) {
	rows, err := q.db.Query(ctx, getValidTransitions, arg.DealModule, arg.FromStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusTransitionRule{}
	for rows.Next() {
		var i StatusTransitionRule
		if err := rows.Scan(
			&i.ID,
			&i.DealModule,
			&i.FromStatus,
			&i.ToStatus,
			&i.RequiredRole,
			&i.RequiresReason,
			&i.RequiresConfirmation,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidTransitionsForRole = `-- name: GetValidTransitionsForRole :many
SELECT id, deal_module, from_status, to_status, required_role, requires_reason, requires_confirmation, is_active FROM status_transition_rules
WHERE deal_module = $1
  AND from_status = $2
  AND required_role = $3
  AND is_active = true
ORDER BY to_status ASC
`

type GetValidTransitionsForRoleParams struct {
	DealModule   string `json:"deal_module"`
	FromStatus   string `json:"from_status"`
	RequiredRole string `json:"required_role"`
}

// Lấy transitions mà role cụ thể được phép thực hiện
// Dùng để filter UI buttons theo quyền user
func (q *Queries) GetValidTransitionsForRole(ctx context.Context, arg GetValidTransitionsForRoleParams) ([]StatusTransitionRule, error) {
	rows, err := q.db.Query(ctx, getValidTransitionsForRole, arg.DealModule, arg.FromStatus, arg.RequiredRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusTransitionRule{}
	for rows.Next() {
		var i StatusTransitionRule
		if err := rows.Scan(
			&i.ID,
			&i.DealModule,
			&i.FromStatus,
			&i.ToStatus,
			&i.RequiredRole,
			&i.RequiresReason,
			&i.RequiresConfirmation,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTransitionRules = `-- name: ListAllTransitionRules :many
SELECT id, deal_module, from_status, to_status, required_role, requires_reason, requires_confirmation, is_active FROM status_transition_rules
WHERE deal_module = $1
ORDER BY from_status ASC, to_status ASC
`

// Liệt kê toàn bộ rules — trang quản trị config
func (q *Queries) ListAllTransitionRules(ctx context.Context, dealModule string) ([]StatusTransitionRule, error) {
	rows, err := q.db.Query(ctx, listAllTransitionRules, dealModule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusTransitionRule{}
	for rows.Next() {
		var i StatusTransitionRule
		if err := rows.Scan(
			&i.ID,
			&i.DealModule,
			&i.FromStatus,
			&i.ToStatus,
			&i.RequiredRole,
			&i.RequiresReason,
			&i.RequiresConfirmation,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransitionRulesByRole = `-- name: ListTransitionRulesByRole :many
SELECT id, deal_module, from_status, to_status, required_role, requires_reason, requires_confirmation, is_active FROM status_transition_rules
WHERE required_role = $1 AND is_active = true
ORDER BY deal_module ASC, from_status ASC
`

// Tất cả transitions mà role được phép — authorization matrix
func (q *Queries) ListTransitionRulesByRole(ctx context.Context, requiredRole string) ([]StatusTransitionRule, error) {
	rows, err := q.db.Query(ctx, listTransitionRulesByRole, requiredRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusTransitionRule{}
	for rows.Next() {
		var i StatusTransitionRule
		if err := rows.Scan(
			&i.ID,
			&i.DealModule,
			&i.FromStatus,
			&i.ToStatus,
			&i.RequiredRole,
			&i.RequiresReason,
			&i.RequiresConfirmation,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransitionRule = `-- name: UpdateTransitionRule :one
UPDATE status_transition_rules SET
    requires_reason = COALESCE($2, requires_reason),
    requires_confirmation = COALESCE($3, requires_confirmation),
    is_active = COALESCE($4, is_active)
WHERE id = $1
RETURNING id, deal_module, from_status, to_status, required_role, requires_reason, requires_confirmation, is_active
`

type UpdateTransitionRuleParams struct {
	ID                   uuid.UUID `json:"id"`
	RequiresReason       *bool     `json:"requires_reason"`
	RequiresConfirmation *bool     `json:"requires_confirmation"`
	IsActive             *bool     `json:"is_active"`
}

// Cập nhật rule — admin config
func (q *Queries) UpdateTransitionRule(ctx context.Context, arg UpdateTransitionRuleParams) (StatusTransitionRule, error) {
	row := q.db.QueryRow(ctx, updateTransitionRule,
		arg.ID,
		arg.RequiresReason,
		arg.RequiresConfirmation,
		arg.IsActive,
	)
	var i StatusTransitionRule
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.FromStatus,
		&i.ToStatus,
		&i.RequiredRole,
		&i.RequiresReason,
		&i.RequiresConfirmation,
		&i.IsActive,
	)
	return i, err
}

const validateTransition = `-- name: ValidateTransition :one
SELECT id, deal_module, from_status, to_status, required_role, requires_reason, requires_confirmation, is_active FROM status_transition_rules
WHERE deal_module = $1
  AND from_status = $2
  AND to_status = $3
  AND required_role = $4
  AND is_active = true
`

type ValidateTransitionParams struct {
	DealModule   string `json:"deal_module"`
	FromStatus   string `json:"from_status"`
	ToStatus     string `json:"to_status"`
	RequiredRole string `json:"required_role"`
}

// Kiểm tra transition có hợp lệ không (from_status + to_status + role)
// Return NULL nếu không hợp lệ → application deny action
func (q *Queries) ValidateTransition(ctx context.Context, arg ValidateTransitionParams) (StatusTransitionRule, error) {
	row := q.db.QueryRow(ctx, validateTransition,
		arg.DealModule,
		arg.FromStatus,
		arg.ToStatus,
		arg.RequiredRole,
	)
	var i StatusTransitionRule
	err := row.Scan(
		&i.ID,
		&i.DealModule,
		&i.FromStatus,
		&i.ToStatus,
		&i.RequiredRole,
		&i.RequiresReason,
		&i.RequiresConfirmation,
		&i.IsActive,
	)
	return i, err
}
