// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    id, external_id, username, password_hash, full_name, email,
    branch_id, department, position, is_active, created_at, updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, true, NOW(), NOW()
)
RETURNING id, external_id, username, password_hash, full_name, email, branch_id, department, position, is_active, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ExternalID   *string     `json:"external_id"`
	Username     string      `json:"username"`
	PasswordHash *string     `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Email        string      `json:"email"`
	BranchID     pgtype.UUID `json:"branch_id"`
	Department   *string     `json:"department"`
	Position     *string     `json:"position"`
}

// ============================================================================
// users.sql — Queries for users table
// Treasury Management System — KienlongBank
// ============================================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ExternalID,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Email,
		arg.BranchID,
		arg.Department,
		arg.Position,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.BranchID,
		&i.Department,
		&i.Position,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, external_id, username, password_hash, full_name, email, branch_id, department, position, is_active, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE external_id = $1 AND deleted_at IS NULL
`

// Dùng khi AUTH_MODE=zitadel: match user từ JWT claim
func (q *Queries) GetUserByExternalID(ctx context.Context, externalID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalID, externalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.BranchID,
		&i.Department,
		&i.Position,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, external_id, username, password_hash, full_name, email, branch_id, department, position, is_active, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.BranchID,
		&i.Department,
		&i.Position,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, external_id, username, password_hash, full_name, email, branch_id, department, position, is_active, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.BranchID,
		&i.Department,
		&i.Position,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveUsersByRole = `-- name: ListActiveUsersByRole :many
SELECT u.id, u.external_id, u.username, u.password_hash, u.full_name, u.email, u.branch_id, u.department, u.position, u.is_active, u.last_login_at, u.created_at, u.updated_at, u.deleted_at FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles r ON r.id = ur.role_id
WHERE r.code = $1
  AND u.is_active = true
  AND u.deleted_at IS NULL
ORDER BY u.full_name ASC
LIMIT $2 OFFSET $3
`

type ListActiveUsersByRoleParams struct {
	Code   string `json:"code"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

// Liệt kê users đang hoạt động theo role code — dùng cho assign approval
func (q *Queries) ListActiveUsersByRole(ctx context.Context, arg ListActiveUsersByRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsersByRole, arg.Code, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Email,
			&i.BranchID,
			&i.Department,
			&i.Position,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, external_id, username, password_hash, full_name, email, branch_id, department, position, is_active, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY full_name ASC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Email,
			&i.BranchID,
			&i.Department,
			&i.Position,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByBranch = `-- name: ListUsersByBranch :many
SELECT id, external_id, username, password_hash, full_name, email, branch_id, department, position, is_active, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE branch_id = $1 AND deleted_at IS NULL AND is_active = true
ORDER BY full_name ASC
LIMIT $2 OFFSET $3
`

type ListUsersByBranchParams struct {
	BranchID pgtype.UUID `json:"branch_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListUsersByBranch(ctx context.Context, arg ListUsersByBranchParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByBranch, arg.BranchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Email,
			&i.BranchID,
			&i.Department,
			&i.Position,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByDepartment = `-- name: ListUsersByDepartment :many
SELECT id, external_id, username, password_hash, full_name, email, branch_id, department, position, is_active, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE department = $1 AND deleted_at IS NULL AND is_active = true
ORDER BY full_name ASC
LIMIT $2 OFFSET $3
`

type ListUsersByDepartmentParams struct {
	Department *string `json:"department"`
	Limit      int32   `json:"limit"`
	Offset     int32   `json:"offset"`
}

func (q *Queries) ListUsersByDepartment(ctx context.Context, arg ListUsersByDepartmentParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByDepartment, arg.Department, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Email,
			&i.BranchID,
			&i.Department,
			&i.Position,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    full_name = COALESCE($2, full_name),
    email = COALESCE($3, email),
    branch_id = COALESCE($4, branch_id),
    department = COALESCE($5, department),
    position = COALESCE($6, position),
    is_active = COALESCE($7, is_active),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, external_id, username, password_hash, full_name, email, branch_id, department, position, is_active, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID         uuid.UUID   `json:"id"`
	FullName   *string     `json:"full_name"`
	Email      *string     `json:"email"`
	BranchID   pgtype.UUID `json:"branch_id"`
	Department *string     `json:"department"`
	Position   *string     `json:"position"`
	IsActive   *bool       `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.BranchID,
		arg.Department,
		arg.Position,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.BranchID,
		&i.Department,
		&i.Position,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}
